### ISSUE TITLE
Playlist Not Working

### ISSUE THREAD

**Issue by chicagoandy** [KoljaWindeler/ytube_music_player#107]
Logfile and Config are listed below, but I am getting an error while trying to play a playlist.

2021-05-24 16:45:08 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source(living_room_display)
2021-05-24 16:45:08 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.living_room_display/ current )
2021-05-24 16:45:08 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_update_remote_player
2021-05-24 16:45:08 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.living_room_display as player
2021-05-24 16:45:08 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack passed
2021-05-24 16:45:08 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source
2021-05-24 16:45:10 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] play_media, media_type: playlist, media_id: VLPLkRM3S4Q5c5F3OB8z_8usCfVlaiUNBwrp-A17Kp3jZfg6pg
2021-05-24 16:45:10 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_prepare_play
2021-05-24 16:45:10 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api
2021-05-24 16:45:10 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_check_api
2021-05-24 16:45:10 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current media_player.living_room_display)
2021-05-24 16:45:10 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_update_remote_player
2021-05-24 16:45:10 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_on_media_player
2021-05-24 16:45:10 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_turn_on_media_player
2021-05-24 16:45:10 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher
2021-05-24 16:45:11 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_cipher
2021-05-24 16:45:11 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_prepare_play
2021-05-24 16:45:11 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] get_playlist(playlistId=VLPLkRM3S4Q5c5F3OB8z_8usCfVlaiUNBwrp-A17Kp3jZfg6pg)
2021-05-24 16:45:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
============= ytube_music_player Integration Error ================
2021-05-24 16:45:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2021-05-24 16:45:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2021-05-24 16:45:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:
2021-05-24 16:45:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1234, in async_play_media
playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ytube_music_player/media_player.py", line 1234, in
playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 66, in get_playlist
response = self._send_request(endpoint, body)
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 133, in _send_request
raise Exception(message + error)
Exception: Server returned HTTP 400: Bad Request.
Request contains an invalid argument.
2021-05-24 16:45:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2021-05-24 16:45:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================

I'm using a simple mini-music-player to kick things off:
type: 'custom:mini-media-player'
entity: media_player.living_room_music_player
artwork: cover
hide:
shuffle: false
icon_state: false
shortcuts:
columns: 2
buttons:
- name: speaker
type: source
id: living_room_display
- name: rockabye
type: playlist
id: VLPLkRM3S4Q5c5F3OB8z_8usCfVlaiUNBwrp-A17Kp3jZfg6pg
name: test

Thank you

**Comment by KoljaWindeler** [comment]
Hi, are you running the latest version?

**Comment by chicagoandy** [comment]
I am running 20210523/01

Thanks!

**Comment by stboch** [comment]
there have been several releases since then try to update to 20210603.01

**Comment by doughecka** [comment]
I'm having the same issue, with the latest version. 

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1650
Integration: yTubeMediaPlayer (documentation, issues)
First occurred: 9:31:06 PM (4 occurrences)
Last logged: 9:53:19 PM

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 944, in async_update_playlists self._playlists = await self.hass.async_add_executor_job(self._api.get_library_playlists,self._trackLimit) File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py", line 39, in get_library_playlists get_continuations(results, 'gridContinuation', limit - len(playlists), File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 64, in get_continuations contents = get_continuation_contents(results, parse_func) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 113, in get_continuation_contents return parse_func(continuation[term]) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py", line 37, in <lambda> parse_func = lambda contents: parse_content_list(contents, parse_playlist) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/browsing.py", line 158, in parse_content_list contents.append(parse_func(result['musicTwoRowItemRenderer'])) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/browsing.py", line 195, in parse_playlist 'title': nav(data, TITLE_TEXT), File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav raise err File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav root = root[k] KeyError: 'runs'

**Comment by wisamarrakee2** [comment]
Hi Doughecka and Stboch, have you managed to find the solution to the Playlist issue please? I'm facing exactly the same issue. Thanks.

**Comment by doughecka** [comment]
Nope, no playlists load.

**Comment by konradwalsh** [comment]
does anyone know which version worked with playlists so I can go back?

**Comment by KoljaWindeler** [comment]
What issue do you have exactly?

**Comment by konradwalsh** [comment]
The above.. Playlists stopped working a few versions back..

**Comment by KoljaWindeler** [comment]
@chicagoandy used a very old version that isn't longer compatible to the youtube music api and @doughecka has likely a wrong cookie .. please use the latest version, activate the debug log, describe the issue and copy the log into this ticket and I'll try to help

**Comment by konradwalsh** [comment]
OK, will do so.. I didnt want to open another thread in case... I will do this on a separate issue

**Comment by KoljaWindeler** [comment]
no worries .. :)
