### ISSUE TITLE
Error - Config flow cant load

### ISSUE THREAD

**Issue by umutcelebi** [KoljaWindeler/ytube_music_player#111]
![image](https://user-images.githubusercontent.com/85175718/125793308-a0c3263f-25b1-444f-9b7f-8e6d6bfc824d.png)

I cant even load the file.
Raspberry PI 3B on HA core-2021.7.2

What for info do you need more to help you out?

**Comment by KoljaWindeler** [comment]
Are you using the latest version of the integration? 
Please copy the error from the log into this ticket

**Comment by umutcelebi** [comment]
I cannot even install it. How do i show you that?

**Comment by KoljaWindeler** [comment]
What do you mean by "install" ... Do you use hacs?

**Comment by umutcelebi** [comment]
Yes, and then you need to add it from at integrations but that step gives this error to me.

**Comment by KoljaWindeler** [comment]
Ok, so you made sure that the integration is up to date in hacs, correct? 
If that's the case simply try to add it (like you did) an once you see the error go to config -> logs ... (Maybe go there, clear, add the integration, go back to the log)

**Comment by umutcelebi** [comment]
I have done what you said but same error. Unfortunately there is nothing in the log that refers to the integration either. It seems it does not accept it. I have deleted it in hacs and restarted ha and then added again and then restart but no difference...

**Comment by KoljaWindeler** [comment]
Hmm but there should really be an error in the log. Maybe "load full log" ?

**Comment by umutcelebi** [comment]
Something like this?

2021-07-16 14:29:53 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-07-16 14:29:53 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-07-16 14:29:53 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-07-16 14:29:53 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-07-16 14:29:53 WARNING (SyncWorker_5) [homeassistant.loader] We found a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-07-16 14:29:53 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration multizone_controller which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-07-16 14:29:53 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-07-16 14:29:53 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2021-07-16 14:29:53 ERROR (SyncWorker_4) [homeassistant.loader] The custom integration 'eufy_security' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

2021-07-16 14:30:12 ERROR (MainThread) [homeassistant.components.rest] Unexpected error fetching rest data data: Invalid type for url. Expected str or httpx.URL, got <class 'NoneType'>: None

Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh

self.data = await self._async_update_data()

File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data

return await self.update_method()

File "/usr/src/homeassistant/homeassistant/components/rest/data.py", line 56, in async_update

response = await self._async_client.request(

File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1415, in request

request = self.build_request(

File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 317, in build_request

url = self._merge_url(url)

File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 338, in _merge_url

merge_url = URL(url)

File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 150, in __init__

raise TypeError(

TypeError: Invalid type for url. Expected str or httpx.URL, got <class 'NoneType'>: None

2021-07-16 14:30:13 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform afvalbeheer is taking over 10 seconds.

2021-07-16 14:30:13 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform hassio is taking over 10 seconds.

2021-07-16 14:30:13 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform hassio is taking over 10 seconds.

2021-07-16 14:30:23 WARNING (MainThread) [homeassistant.components.xiaomi_miio.vacuum] Loading Xiaomi Miio Vacuum via platform setup is deprecated; Please remove it from your configuration

2021-07-16 14:30:23 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.

2021-07-16 14:30:23 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.

2021-07-16 14:30:23 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.

2021-07-16 14:30:39 ERROR (MainThread) [custom_components.localtuya.common] [512...66d] Connect to 192.168.40.23 failed

Traceback (most recent call last):

File "/config/custom_components/localtuya/common.py", line 139, in _make_connection

self._interface = await pytuya.connect(

File "/config/custom_components/localtuya/pytuya/__init__.py", line 637, in connect

_, protocol = await loop.create_connection(

File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection

raise exceptions[0]

File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection

sock = await self._connect_sock(

File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock

await self.sock_connect(sock, address)

File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect

return await fut

File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb

raise OSError(err, f'Connect call failed {address}')

ConnectionResetError: [Errno 104] Connect call failed ('192.168.40.23', 6668)

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform androidtv is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform rpi_power is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform islamic_prayer_times is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.light] Setup of light platform tuya is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform tuya is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.light] Setup of light platform localtuya is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform localtuya is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.light] Setup of light platform group is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.light] Setup of light platform group is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.light] Setup of light platform group is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.light] Setup of light platform group is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.components.light] Setup of light platform group is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.setup] Setup of zeroconf is taking over 10 seconds.

2021-07-16 14:30:40 WARNING (MainThread) [homeassistant.config_entries] Config entry 'EPSON WF-3540 Series' for ipp integration not ready yet: Invalid response from API: Timeout occurred while connecting to IPP server.; Retrying in background

2021-07-16 14:30:41 ERROR (MainThread) [homeassistant.components.updater] Error requesting Home Assistant update data: [Errno 32] Broken pipe

2021-07-16 14:30:42 WARNING (MainThread) [androidtv.adb_manager.adb_manager_async] Couldn't connect to 192.168.40.55:5555. TcpTimeoutException: Connecting to 192.168.40.55:5555 timed out (1.0 seconds)

2021-07-16 14:30:42 WARNING (MainThread) [homeassistant.components.androidtv.media_player] Could not connect to Philips Android TV at 192.168.40.55:5555 using Python ADB implementation with adbkey='/config/.storage/androidtv_adbkey'

2021-07-16 14:30:43 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Roborock S6 Pure for xiaomi_miio

Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/config_entries.py", line 432, in async_unload

result = await component.async_unload_entry(hass, self) # type: ignore

File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 180, in async_unload_entry

hass.data[DOMAIN].pop(config_entry.entry_id)

KeyError: 'd6b2e4b67d7cc69c2537d9374f78195e'

2021-07-16 14:30:45 WARNING (MainThread) [homeassistant.components.media_player] Platform androidtv not ready yet: None; Retrying in background in 30 seconds

2021-07-16 14:30:49 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Configuration.yaml for nest

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn

conn = connection.create_connection(

File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection

raise err

File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection

sock.connect(sa)

ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen

httplib_response = self._make_request(

File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request

self._validate_conn(conn)

File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn

conn.connect()

File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect

conn = self._new_conn()

File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn

raise NewConnectionError(

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f961387f0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send

resp = conn.urlopen(

File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen

retries = retries.increment(

File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment

raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /oauth2/v4/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f961387f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/google/auth/transport/requests.py", line 183, in __call__

response = self.session.request(

File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request

resp = self.send(prep, **send_kwargs)

File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send

r = adapter.send(request, **kwargs)

File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send

raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /oauth2/v4/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f961387f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup

result = await component.async_setup_entry(hass, self) # type: ignore

File "/usr/src/homeassistant/homeassistant/components/nest/__init__.py", line 166, in async_setup_entry

await subscriber.start_async()

File "/usr/local/lib/python3.9/site-packages/google_nest_sdm/google_nest_subscriber.py", line 148, in start_async

await self._subscriber_factory.async_new_subscriber(

File "/usr/local/lib/python3.9/site-packages/google_nest_sdm/google_nest_subscriber.py", line 64, in async_new_subscriber

return await loop.run_in_executor(

File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run

result = self.fn(*self.args, **self.kwargs)

File "/usr/local/lib/python3.9/site-packages/google_nest_sdm/google_nest_subscriber.py", line 76, in _new_subscriber

creds.refresh(Request())

File "/usr/local/lib/python3.9/site-packages/google/oauth2/credentials.py", line 228, in refresh

) = reauth.refresh_grant(

File "/usr/local/lib/python3.9/site-packages/google/oauth2/reauth.py", line 318, in refresh_grant

response_status_ok, response_data = _client._token_endpoint_request_no_throw(

File "/usr/local/lib/python3.9/site-packages/google/oauth2/_client.py", line 115, in _token_endpoint_request_no_throw

response = request(method="POST", url=token_uri, headers=headers, body=body)

File "/usr/local/lib/python3.9/site-packages/google/auth/transport/requests.py", line 189, in __call__

six.raise_from(new_exc, caught_exc)

File "<string>", line 3, in raise_from

google.auth.exceptions.TransportError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: /oauth2/v4/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f961387f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

2021-07-16 14:30:51 WARNING (MainThread) [homeassistant.components.vacuum] Setup of vacuum platform xiaomi_miio is taking over 10 seconds.

2021-07-16 14:30:53 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds

2021-07-16 14:30:59 ERROR (MainThread) [homeassistant.components.automation] Platform automation does not generate unique IDs. ID 1626169514813 already exists - ignoring automation.woonkamer_1_21_00_00_00

2021-07-16 14:30:59 ERROR (Thread-6) [pychromecast.socket_client] [55PUS7101/12(40.40.40.93):8009] Failed to connect to service ServiceInfo(type='mdns', data='QM163E-21edac8a5bee6e1b203ea63da7b2b67c._googlecast._tcp.local.'), retrying in 5.0s

2021-07-16 14:31:22 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05

2021-07-16 14:31:25 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform androidtv is taking over 10 seconds.

2021-07-16 14:31:53 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'linkquality' when rendering '{{ value_json.linkquality }}'

2021-07-16 14:31:53 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'

2021-07-16 14:31:53 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'

2021-07-16 14:31:54 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'

2021-07-16 14:31:54 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'

2021-07-16 14:31:54 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'

2021-07-16 14:31:54 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'

2021-07-16 14:31:54 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'linkquality' when rendering '{{ value_json.linkquality }}'

2021-07-16 14:31:54 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'linkquality' when rendering '{{ value_json.linkquality }}'

2021-07-16 14:31:54 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'

2021-07-16 14:31:54 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'requested_brightness_level' when rendering '{{ value_json.requested_brightness_level }}'

2021-07-16 14:31:54 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'requested_brightness_percent' when rendering '{{ value_json.requested_brightness_percent }}'

2021-07-16 14:32:06 ERROR (MainThread) [homeassistant.components.androidtv.media_player] Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: [Errno 104] Connection reset by peer

2021-07-16 14:32:38 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'

2021-07-16 14:32:38 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'

2021-07-16 14:33:02 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05

2021-07-16 14:33:05 WARNING (Thread-8) [pychromecast.socket_client] [Meyra Duha(192.168.40.12):8009] Heartbeat timeout, resetting connection

2021-07-16 14:33:05 WARNING (Thread-10) [pychromecast.socket_client] [Slaapkamer(192.168.40.14):8009] Heartbeat timeout, resetting connection

2021-07-16 14:33:07 WARNING (Thread-9) [pychromecast.socket_client] [Werkplek(192.168.40.10):8009] Heartbeat timeout, resetting connection

2021-07-16 14:33:07 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds

2021-07-16 14:33:07 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05

2021-07-16 14:33:07 WARNING (SyncWorker_8) [custom_components.xiaomi_cloud_map_extractor.camera] Got exception while fetching the state: Unable to discover the device 192.168.40.13

2021-07-16 14:33:07 WARNING (Thread-12) [pychromecast.socket_client] [Home(192.168.40.10):32017] Heartbeat timeout, resetting connection

2021-07-16 14:33:08 ERROR (Thread-12) [pychromecast.socket_client] [Home(192.168.40.10):32017] Failed to connect to service ServiceInfo(type='mdns', data='Google-Cast-Group-15a7c01fa07e4c6d9da06a4d8dd6197b-1._googlecast._tcp.local.'), retrying in 5.0s

2021-07-16 14:33:12 ERROR (Thread-9) [pychromecast.socket_client] [Werkplek([::ffff:c0a8:280a]):8009] Failed to connect to service ServiceInfo(type='host', data=('[::ffff:c0a8:280a]', 8009)), retrying in 5.0s

2021-07-16 14:33:14 WARNING (Thread-7) [pychromecast.socket_client] [Woonkamer(192.168.40.11):8009] Heartbeat timeout, resetting connection

2021-07-16 14:33:18 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05

2021-07-16 14:34:24 WARNING (Thread-9) [pychromecast.socket_client] [Werkplek(192.168.40.10):8009] Heartbeat timeout, resetting connection

2021-07-16 14:34:29 ERROR (Thread-9) [pychromecast.socket_client] [Werkplek([::ffff:c0a8:280a]):8009] Failed to connect to service ServiceInfo(type='host', data=('[::ffff:c0a8:280a]', 8009)), retrying in 5.0s

2021-07-16 14:34:32 WARNING (Thread-12) [pychromecast.socket_client] [Home(192.168.40.10):32017] Heartbeat timeout, resetting connection

2021-07-16 14:35:02 WARNING (Thread-9) [pychromecast.socket_client] [Werkplek(192.168.40.10):8009] Heartbeat timeout, resetting connection

2021-07-16 14:35:07 ERROR (Thread-9) [pychromecast.socket_client] [Werkplek([::ffff:c0a8:280a]):8009] Failed to connect to service ServiceInfo(type='host', data=('[::ffff:c0a8:280a]', 8009)), retrying in 5.0s

2021-07-16 14:35:36 WARNING (Thread-9) [pychromecast.socket_client] [Werkplek(192.168.40.10):8009] Heartbeat timeout, resetting connection

2021-07-16 14:35:39 WARNING (Thread-12) [pychromecast.socket_client] [Home(192.168.40.10):32017] Heartbeat timeout, resetting connection

2021-07-16 14:35:41 ERROR (Thread-9) [pychromecast.socket_client] [Werkplek([::ffff:c0a8:280a]):8009] Failed to connect to service ServiceInfo(type='host', data=('[::ffff:c0a8:280a]', 8009)), retrying in 5.0s

2021-07-16 14:46:02 WARNING (Thread-12) [pychromecast.socket_client] [Home(192.168.40.10):32017] Heartbeat timeout, resetting connection

2021-07-16 14:48:26 WARNING (Thread-9) [pychromecast.socket_client] [Werkplek(192.168.40.10):8009] Heartbeat timeout, resetting connection

2021-07-16 14:50:16 WARNING (Thread-12) [pychromecast.socket_client] [Home(192.168.40.10):32017] Heartbeat timeout, resetting connection

2021-07-16 14:52:55 WARNING (MainThread) [homeassistant.components.automation.hal_12_00_18_00] Hal 12:00 - 18:00: Already running

2021-07-16 14:53:20 WARNING (MainThread) [homeassistant.components.automation.hal_12_00_18_00] Hal 12:00 - 18:00: Already running

2021-07-16 14:53:56 WARNING (Thread-9) [pychromecast.socket_client] [Werkplek(192.168.40.10):8009] Heartbeat timeout, resetting connection

2021-07-16 14:54:00 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05

2021-07-16 14:54:05 WARNING (Thread-12) [pychromecast.socket_client] [Home(192.168.40.10):32017] Heartbeat timeout, resetting connection

2021-07-16 14:54:28 WARNING (Thread-12) [pychromecast.socket_client] [Home(192.168.40.10):32017] Heartbeat timeout, resetting connection

2021-07-16 14:56:13 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'

2021-07-16 14:56:13 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'

2021-07-16 14:56:13 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'

2021-07-16 14:56:13 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'

2021-07-16 14:57:32 WARNING (Thread-9) [pychromecast.socket_client] [Werkplek(192.168.40.10):8009] Heartbeat timeout, resetting connection

2021-07-16 15:01:09 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'

2021-07-16 15:01:09 WARNING (MainThread) [homea

**Comment by KoljaWindeler** [comment]
Jep you're right. Nothing that relatest to this integration. 
Whats the last couple off message after you try to add the integration? 
And why do you have so many "can't connect" is that pc offline?

**Comment by umutcelebi** [comment]
Yes my pc and tv are having issues. Couldnt find out yet why they are going on connection error. Probably they are sleeping..

**Comment by KoljaWindeler** [comment]
just disconnected my dev-setup .. integration setup loads fine .. failes to test the cookie but that 2 steps further from where you are

**Comment by umutcelebi** [comment]
Shall i try another version from hacs? If yes which should i try.

**Comment by KoljaWindeler** [comment]
No

Whats the last couple off message after you try to add the integration?

**Comment by umutcelebi** [comment]
You mean the error? Just config flow cant load

The other logs are other hacs integrations.

**Comment by KoljaWindeler** [comment]
Sure that there is nothing ahead? Usually Homeassistent print pretty many details

**Comment by umutcelebi** [comment]
I have checked again and yes cant find anything suspicious

**Comment by KoljaWindeler** [comment]
Sorry .. but I don't think I can help .. maybe switch you language to English and fix the connection issue ...

**Comment by umutcelebi** [comment]
What do you mean by change the language? It is already english? Sadly this is the only not working integration😔

**Comment by KoljaWindeler** [comment]
Well your error message in the screenshot was in dutch? So I thought you're running HA in non_english

**Comment by umutcelebi** [comment]
Oh yes, the language is english but the view is translated.

**Comment by KoljaWindeler** [comment]
Might be an idea to set the view to English just for testing

**Comment by umutcelebi** [comment]
No difference unfortunately. And no changes in the log...
![image](https://user-images.githubusercontent.com/85175718/125997923-77fa5eb5-be61-4ff3-aaa9-56669cb98130.png)

**Comment by umutcelebi** [comment]
Problem is solved. I am not sure what did it make to work but after 1 week it is working now.

**Comment by KoljaWindeler** [comment]
Strange but. . ok
