### ISSUE TITLE
Can't call music from my Lovelace frontend using a script

### ISSUE THREAD

**Issue by GSLaaitie** [KoljaWindeler/ytube_music_player#116]
Hi!

When trying to play music using a script, the speaker just turns on for a sec and then turns off without playing anything.

The log said I must open an issue here and paste this:

Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request six.raise_from(e, None) File "<string>", line 3, in raise_from File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request httplib_response = conn.getresponse() File "/usr/local/lib/python3.9/http/client.py", line 1345, in getresponse response.begin() File "/usr/local/lib/python3.9/http/client.py", line 307, in begin version, status, reason = self._read_status() File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/usr/local/lib/python3.9/socket.py", line 704, in readinto return self._sock.recv_into(b) File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into return self.read(nbytes, buffer) File "/usr/local/lib/python3.9/ssl.py", line 1099, in read return self._sslobj.read(len, buffer) ConnectionResetError: [Errno 104] Connection reset by peer During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send resp = conn.urlopen( File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen retries = retries.increment( File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment raise six.reraise(type(error), error, _stacktrace) File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise raise value.with_traceback(tb) File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request six.raise_from(e, None) File "<string>", line 3, in raise_from File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request httplib_response = conn.getresponse() File "/usr/local/lib/python3.9/http/client.py", line 1345, in getresponse response.begin() File "/usr/local/lib/python3.9/http/client.py", line 307, in begin version, status, reason = self._read_status() File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/usr/local/lib/python3.9/socket.py", line 704, in readinto return self._sock.recv_into(b) File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into return self.read(nbytes, buffer) File "/usr/local/lib/python3.9/ssl.py", line 1099, in read return self._sslobj.read(len, buffer) urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1326, in async_play_media playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1326, in <lambda> playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/playlists.py", line 66, in get_playlist response = self._send_request(endpoint, body) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 124, in _send_request response = self._session.post(YTM_BASE_API + endpoint + YTM_PARAMS + additionalParams, File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post return self.request('POST', url, data=data, json=json, **kwargs) File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Tell me is is just something stupid I'm doing?
The script I'm using is: 
`  play_time_without_consequence:
    alias: Time Without Consequence
    sequence:
      - service: media_player.select_source
        data:
          source: media_player.kombuis_speaker
          entity_id: media_player.ytube_music_player
      - service: media_player.shuffle_set
        data:
          shuffle: false
          entity_id: media_player.ytube_music_player
      - service: media_player.play_media
        data:
          entity_id: media_player.ytube_music_player
          media_content_id: OLAK5uy_mzyZiozaLklR3tm-RQvbYCbfGtoiTx_0A
          media_content_type: playlist
    mode: single  `

**Comment by KoljaWindeler** [comment]
Could you please format you yaml script so we can read it.
Use \```yaml [your script] \```
Thanks

**Comment by GSLaaitie** [comment]
Sure, sorry my bad. First time using Github for posting:
```yaml play_time_without_consequence:
    alias: Time Without Consequence
    sequence:
      - service: media_player.select_source
        data:
          source: media_player.kombuis_speaker
          entity_id: media_player.ytube_music_player
      - service: media_player.shuffle_set
        data:
          shuffle: false
          entity_id: media_player.ytube_music_player
      - service: media_player.play_media
        data:
          entity_id: media_player.ytube_music_player
          media_content_id: OLAK5uy_mzyZiozaLklR3tm-RQvbYCbfGtoiTx_0A
          media_content_type: playlist
     mode: single
```

**Comment by KoljaWindeler** [comment]
Hmm that looks alright. 
And regular playback works? Triggered by the media_browser?

**Comment by GSLaaitie** [comment]
Thanks for the response. Yes, it seems to work only when:

1. Called through one of the shortcut buttons on custom:mini-media-player
2. Selected through the custom:mini-media-player's lovelace media browser (which correctly displays all my personal playlists and albums)

**Comment by KoljaWindeler** [comment]
And you've retrieved the playlist id after selecting a playlist via the media_browser? Have you tried another playlist just as test?

**Comment by GSLaaitie** [comment]
Yup. Tried with a number of playlists / albums. Similar response.
Does the pasted info from the log contain anything noteworthy?

**Comment by GSLaaitie** [comment]
Just tried with a different playlist. I see the log shows something slightly different:
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1326, in async_play_media playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1326, in <lambda> playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/playlists.py", line 69, in get_playlist playlist = {'id': results['playlistId']} KeyError: 'playlistId'
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1331, in async_play_media self._tracks = await self.hass.async_add_executor_job(self._api.get_album,media_id) # no limit needed File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/browsing.py", line 478, in get_album response = self._send_request(endpoint, body) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 133, in _send_request raise Exception(message + error) Exception: Server returned HTTP 400: Bad Request. Request contains an invalid argument.
Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request six.raise_from(e, None) File "<string>", line 3, in raise_from File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request httplib_response = conn.getresponse() File "/usr/local/lib/python3.9/http/client.py", line 1345, in getresponse response.begin() File "/usr/local/lib/python3.9/http/client.py", line 307, in begin version, status, reason = self._read_status() File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/usr/local/lib/python3.9/socket.py", line 704, in readinto return self._sock.recv_into(b) File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into return self.read(nbytes, buffer) File "/usr/local/lib/python3.9/ssl.py", line 1099, in read return self._sslobj.read(len, buffer) ConnectionResetError: [Errno 104] Connection reset by peer During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send resp = conn.urlopen( File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen retries = retries.increment( File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment raise six.reraise(type(error), error, _stacktrace) File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise raise value.with_traceback(tb) File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request six.raise_from(e, None) File "<string>", line 3, in raise_from File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request httplib_response = conn.getresponse() File "/usr/local/lib/python3.9/http/client.py", line 1345, in getresponse response.begin() File "/usr/local/lib/python3.9/http/client.py", line 307, in begin version, status, reason = self._read_status() File "/usr/local/lib/python3.9/http/client.py", line 268, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/usr/local/lib/python3.9/socket.py", line 704, in readinto return self._sock.recv_into(b) File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into return self.read(nbytes, buffer) File "/usr/local/lib/python3.9/ssl.py", line 1099, in read return self._sslobj.read(len, buffer) urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1326, in async_play_media playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1326, in <lambda> playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/playlists.py", line 66, in get_playlist response = self._send_request(endpoint, body) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 124, in _send_request response = self._session.post(YTM_BASE_API + endpoint + YTM_PARAMS + additionalParams, File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post return self.request('POST', url, data=data, json=json, **kwargs) File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send raise ConnectionError(err, request=request) requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by KoljaWindeler** [comment]
That's super strange. 
Have you limited your script to just that one service call that starts the playback ?

The errorlog doesn't really help me, at least I don't clearly understand it. Some ssl error during the connection. But I don't understand how calling via service is different from calling via media_browser. That should be 100% the same for the integration

**Comment by KoljaWindeler** [comment]
Try this id ... 
RDCLAK5uy_l6lSnRziP_Qt6EA5-nmhXZ3uQz76JRZw4
Just as a test.

**Comment by GSLaaitie** [comment]
Thanks, that was my thinking too: If it works from browser, it should work from a service.

Looks like your id worked. But sometimes it works on mine too if the speaker is "awake"
I'll play around and provide feedback once I have more info to share.

**Comment by KoljaWindeler** [comment]
Exactly. Actually: the media_browser calls those services. Same thing.

If your argument are copied from playable playlist then calling the service with the exact same argument should totally work ... Strange
