### ISSUE TITLE
Something with your cookie wasn't right. Format and fields are ok but the login failed

### ISSUE THREAD

**Issue by apkraven** [KoljaWindeler/ytube_music_player#128]
STR: 
1. Add the integration via HACS
2. Go to Settings-Integrations and add "ytube_music_player"
3. Setup. Use the provided guide to log in to youtube music under incognito mode (same under the normal user). Copy contents to form.
ER: Integration should get installed.
AR: "Something with your cookie wasn't right. Format and fields are ok but the login failed"

Logger: custom_components.ytube_music_player.config_flow
Source: custom_components/ytube_music_player/config_flow.py:198
Integration: ytube_music_player (documentation, issues)
First occurred: 15:23:10 (11 occurrences)
Last logged: 17:37:23

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/config_flow.py", line 188, in async_check_data YTMusic.setup(filepath = user_input[CONF_HEADER_PATH], headers_raw = c) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 156, in setup return setup(filepath, headers_raw) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/setup.py", line 36, in setup raise Exception( Exception: The following entries are missing in your headers: x-goog-authuser, cookie. Please try a different request (such as /browse) and make sure you are logged in.

**Comment by apkraven** [comment]
Apologize, I have just seen the pictures, where it's clearly stated that not only the "cookie" value is required, but fields up to x-goog-visitor-id. Closed this one.
