### ISSUE TITLE
KeyError traceback (Music doesn't start)

### ISSUE THREAD

**Issue by samhed** [KoljaWindeler/ytube_music_player#133]
**Describe the bug**
The music doens't start and this is written to the log:

```
2021-09-20 06:26:55 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

============= ytube_music_player Integration Error ================
2021-09-20 06:26:55 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2021-09-20 06:26:55 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2021-09-20 06:26:55 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2021-09-20 06:26:55 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1417, in async_play_media
    self._tracks = await self.hass.async_add_executor_job(lambda:self._api.get_watch_playlist(r_track['videoId'], limit=self._trackLimit))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1417, in <lambda>
    self._tracks = await self.hass.async_add_executor_job(lambda:self._api.get_watch_playlist(r_track['videoId'], limit=self._trackLimit))
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/watch.py", line 78, in get_watch_playlist
    results = nav(watchNextRenderer,
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav
    raise err
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav
    root = root[k]
KeyError: 'content'

2021-09-20 06:26:55 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2021-09-20 06:26:55 ERROR (MainThread) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================
```

**Version**
20210818.01

**To Reproduce**
Unknown, happened when trying to start music from an automation. The same automation has worked in the past but seems to have broken since a few days back.

I haven't seen the error when starting the music manually.

**Additional context**
Home Assistant 2021.8.8

Thanks

**Comment by KoljaWindeler** [comment]
Hi, sorry I somehow didn't see this until now. Is this still an issue?

**Comment by samhed** [comment]
No problem, I haven't seen this in a while actually. I will close this, if it happens again I'll reopen.
