### ISSUE TITLE
 <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by GGI1982** [KoljaWindeler/ytube_music_player#139]
**Describe the bug**
Even after trying to reset cookie setting I get a 'connection refused' error while trying to cast, everything was working fine before. I m not sure but I think I have this problem since my last update (there had several of them core/supervisor and even OS). I can browse throught my library  can find all my playlists and stuff but just cannot play anymore. I tried to remove completly the plugin (from HACS) /reboot/reinstall/reconfigure => same issue. Even tried to stream to different source => not better. 

**Versions**
version of ytube music player : 20210818.01
version of core : core-2021.10.5
version of host : Home Assistant OS 6.5
version of supervisor : supervisor-2021.10.0

**To Reproduce**
Try to play some stream 

**Additional context**

** error log **
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/media_player.py:661
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:36:55 (1 occurrences)
Last logged: 21:36:55

[547444130144] <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1034, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.9/http/client.py", line 1441, in connect
    super().connect()
  File "/usr/local/lib/python3.9/http/client.py", line 945, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/ytube_music_player/media_player.py", line 1409, in async_play_media
    if(not(await self.async_prepare_play())):
  File "/config/custom_components/ytube_music_player/media_player.py", line 545, in async_prepare_play
    await self.async_get_cipher('BB2mjBuAtiQ')
  File "/config/custom_components/ytube_music_player/media_player.py", line 661, in async_get_cipher
    self._js = await self.hass.async_add_executor_job(request.get, js_url)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pytube/request.py", line 42, in get
    return _execute_request(url, headers=extra_headers).read().decode("utf-8")
  File "/usr/local/lib/python3.9/site-packages/pytube/request.py", line 26, in _execute_request
    return urlopen(request)  # nosec
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

Thanks

**Comment by GGI1982** [comment]
also found this log that might be related : 

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:225
Integration: YouTube Music Player (documentation, issues)
First occurred: 21:58:07 (1 occurrences)
Last logged: 21:58:07

async_get_cipher failed

**Comment by GGI1982** [comment]
2021-10-17 22:01:50 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source(groupe_hp)
2021-10-17 22:01:50 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.groupe_hp/ current media_player.shield) [E]
2021-10-17 21:58:07 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher
2021-10-17 21:58:07 ERROR (MainThread) [custom_components.ytube_music_player.media_player] async_get_cipher failed
2021-10-17 21:58:07 DEBUG (MainThread) [custom_components.ytube_music_player.const] - login without brand ID
2021-10-17 21:58:07 INFO (SyncWorker_0) [homeassistant.loader] Loaded discovery from homeassistant.components.discovery
2021-10-17 21:58:09 INFO (MainThread) [custom_components.hacs] Loading known repositories
2021-10-17 21:58:10 INFO (SyncWorker_3) [homeassistant.loader] Loaded zha from homeassistant.components.zha
2021-10-17 21:58:11 INFO (MainThread) [homeassistant.components.netatmo] Register Netatmo webhook: https://ggirard-home.duckdns.org/api/webhook/2da5fd984ad90eb28f3529ebe29a925259853940e58696965a40aecb0c52934c
2021-10-17 21:58:14 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api ... - no valid API, try to login ... YouTube Api initialized ok, version: 0.19.1 [E]
2021-10-17 21:58:14 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_selects
2021-10-17 21:58:14 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - playlist: input_select.ytube_music_player_playlist not found
2021-10-17 21:58:14 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - playmode: input_select.ytube_music_player_playmode not found
2021-10-17 21:58:14 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - playContinuous: input_boolean.ytube_music_player_playcontinuous not found
2021-10-17 21:58:14 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - mediaPlayer: input_select.ytube_music_player_speakers not found
2021-10-17 21:58:14 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Source: input_select.ytube_music_player_source not found
2021-10-17 21:58:15 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Drop down for media player not found
2021-10-17 21:58:15 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input shield/ current ) [E]
2021-10-17 21:58:15 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.shield as player
2021-10-17 21:58:15 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_playlists
2021-10-17 21:58:15 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - no playlist select field, exit
2021-10-17 21:58:15 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_update_selects
2021-10-17 21:58:15 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_playmode
2021-10-17 21:58:15 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_update_playmode 2
2021-10-17 21:58:15 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_startup
2021-10-17 22:01:50 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.groupe_hp as player
2021-10-17 22:01:50 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source
2021-10-17 22:01:51 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] play_media, media_type: channel, media_id: LM
2021-10-17 22:01:51 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_prepare_play
2021-10-17 22:01:51 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2021-10-17 22:01:51 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current media_player.groupe_hp) [E]
2021-10-17 22:01:51 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_on_media_player [E]
2021-10-17 22:01:51 INFO (SyncWorker_2) [pychromecast.controllers] Receiver:Launching app CC1AD845
2021-10-17 22:01:51 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher
2021-10-17 22:01:51 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.groupe_hp: off -> unknown ... not playing [E]
2021-10-17 22:01:51 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548120543680] <urlopen error [Errno 111] Connection refused>
Traceback (most recent call last):
File "/usr/local/lib/python3.9/urllib/request.py", line 1346, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1325, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1274, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1034, in _send_output
self.send(msg)
File "/usr/local/lib/python3.9/http/client.py", line 974, in send
self.connect()
File "/usr/local/lib/python3.9/http/client.py", line 1441, in connect
super().connect()
File "/usr/local/lib/python3.9/http/client.py", line 945, in connect
self.sock = self._create_connection(
File "/usr/local/lib/python3.9/socket.py", line 844, in create_connection
raise err
File "/usr/local/lib/python3.9/socket.py", line 832, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/config/custom_components/ytube_music_player/media_player.py", line 1409, in async_play_media
if(not(await self.async_prepare_play())):
File "/config/custom_components/ytube_music_player/media_player.py", line 545, in async_prepare_play
await self.async_get_cipher('BB2mjBuAtiQ')
File "/config/custom_components/ytube_music_player/media_player.py", line 661, in async_get_cipher
self._js = await self.hass.async_add_executor_job(request.get, js_url)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/pytube/request.py", line 42, in get
return _execute_request(url, headers=extra_headers).read().decode("utf-8")
File "/usr/local/lib/python3.9/site-packages/pytube/request.py", line 26, in _execute_request
return urlopen(request) # nosec
File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "/usr/local/lib/python3.9/urllib/request.py", line 517, in open
response = self._open(req, data)
File "/usr/local/lib/python3.9/urllib/request.py", line 534, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
result = func(*args)
File "/usr/local/lib/python3.9/urllib/request.py", line 1389, in https_open
return self.do_open(http.client.HTTPSConnection, req,
File "/usr/local/lib/python3.9/urllib/request.py", line 1349, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
2021-10-17 22:01:51 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.groupe_hp: unknown -> unknown ... not playing [E]
2021-10-17 22:01:52 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.groupe_hp: unknown -> unknown ... not playing [E]
2021-10-17 22:01:52 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.groupe_hp: unknown -> idle ... not playing [E]
2021-10-17 22:01:52 ERROR (Thread-11) [homeassistant.components.cast.media_player] Failed to cast media https://www.home-assistant.io/images/cast/splash.png. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
2021-10-17 22:01:52 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.groupe_hp: idle -> idle ... not playing [E]

**Comment by GGI1982** [comment]
Ok gues what I Just found the problem .... I m using Pi-hole and it s blocking something in the flow ... As soon as I disabled pi-hole your plugin started again to work
