### ISSUE TITLE
Can't navigate the playlist

### ISSUE THREAD

**Issue by WarC0zes** [KoljaWindeler/ytube_music_player#146]
**Enable DEBUG Output**
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/browse_media.py:67
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 07:46:27 (5 occurrences)
Last logged: 10:18:37

[548218638496] Error handling message: Unknown error
[547828924480] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1147, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1822, in async_browse_media
    response = await build_item_response(self, payload)
  File "/config/custom_components/ytube_music_player/browse_media.py", line 67, in build_item_response
    media = await hass.async_add_executor_job(media_library.get_library_playlists,BROWSER_LIMIT)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/library.py", line 27, in get_library_playlists
    response = self._send_request(endpoint, body)
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 134, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 401: Unauthorized.
You must be signed in to perform this operation.
```

**Describe the bug**
Can't browse the playlist to select an audio track. 

**Version**
core-2021.11.0
supervisor-2021.10.8
Home Assistant OS 6.6
RPi 3B

**To Reproduce**
1. Go to 'browse the media'
2. Click on 'Library paylist'
3. See error

**Additional context**
![bug](https://user-images.githubusercontent.com/91471397/140292056-1a01dd13-687a-48be-a50f-cb5adf7d1374.jpg)

Thanks

**Comment by WarC0zes** [comment]
Problem solved, it was the cookies that bugged.
I redid the cookies and access to the playlist is working again. 
Sorry for inconvenience
