### ISSUE TITLE
Cannot play Album

### ISSUE THREAD

**Issue by hermann1514** [KoljaWindeler/ytube_music_player#155]
Hi,

i have setup the ytube_music_player in Homeassistant. 
Now i can Play playlists but when i would play an album i receive the following Error:

============ ytube_music_player Integration Error ================
2021-12-08 18:53:49 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2021-12-08 18:53:49 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2021-12-08 18:53:49 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:
2021-12-08 18:53:49 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
 File "/config/custom_components/ytube_music_player/media_player.py", line 1385, in async_play_media
   self._tracks = await self.hass.async_add_executor_job(self._api.get_album,media_id) # no limit needed
 File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
   result = self.fn(*self.args, **self.kwargs)
 File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/browsing.py", line 459, in get_album
   response = self._send_request(endpoint, body)
 File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 134, in _send_request
   raise Exception(message + error)
Exception: Server returned HTTP 400: Bad Request.
Request contains an invalid argument.
thanks, Kolja

any ideas?
Regards
Hermann

**Comment by KoljaWindeler** [comment]
Hi, how did you start that album? Your other question makes me believe that you didn't use the media_browser.
Jkw

**Comment by hermann1514** [comment]
I use NodeRed and the call Service Node.
Some Playlists i can start, some not.
The same with Albums.

**Comment by KoljaWindeler** [comment]
Well consider trying to use the media browser at least once with those albums to distinguish between "the integration isn't working"  and "your service call isn't right"

**Comment by hermann1514** [comment]
okay. i can play this via the Medialibrary.

So i will show on my service_call for this.

Regards
Hermann
