### ISSUE TITLE
Error when requesting youtube content

### ISSUE THREAD

**Issue by sgueniot** [KoljaWindeler/ytube_music_player#158]
Hello, 
thanks for this great media player. I have an issue in one of my two home assistant instances.
**DEBUG Output enabled **

**Describe the bug**
 Youtube music content is not visible, when i click on a media library category like Library albums, i have an error popup with text Unknown error .
Log : 
```
2021-12-10 17:08:51 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Posting debug messages as error until restart
2021-12-10 17:08:51 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_call_method
2021-12-10 17:09:25 ERROR (MainThread) [custom_components.ytube_music_player.media_player] async_browse_media
2021-12-10 17:09:25 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2021-12-10 17:09:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] async_browse_media
2021-12-10 17:09:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2021-12-10 17:09:27 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2779479536] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1168, in websocket_browse_media
payload = await player.async_browse_media(media_content_type, media_content_id)
File "/config/custom_components/ytube_music_player/media_player.py", line 1929, in async_browse_media
response = await build_item_response(self, payload)
File "/config/custom_components/ytube_music_player/browse_media.py", line 114, in build_item_response
media = await hass.async_add_executor_job(media_library.get_library_albums, BROWSER_LIMIT)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/library.py", line 126, in get_library_albums
response = self._send_request(endpoint, body)
File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 133, in _send_request
response = self._session.post(YTM_BASE_API + endpoint + YTM_PARAMS + additionalParams,
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1320, in _send_request
self.putheader(hdr, value)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader
_HTTPConnection.putheader(self, header, *values)
File "/usr/local/lib/python3.9/http/client.py", line 1247, in putheader
raise ValueError('Invalid header name %r' % (header,))
ValueError: Invalid header name b''
```

**Version**
20211209.01

**To Reproduce**
1. in Media Library click on one category (Library Playlists for example)

**Additional context**
home assistant in docker witch nginx reverse proxy

Thanks

**Comment by KoljaWindeler** [comment]
hi, could you try to update the cookie? I'm not sure what's causing the issue but likely this is caused by the cookie

**Comment by sgueniot** [comment]
Hi, thanks for your answer.
I updated the cookie from a yt music page on my chrome profile, and i have the same error.
But I try with a new connection from a private navigation page and it's working.
Thanks again for the lead !
