### ISSUE TITLE
Problem Setup

### ISSUE THREAD

**Issue by Mick51** [KoljaWindeler/ytube_music_player#166]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
Something with your cookie wasn't right. Format and fields are ok but the login failed
**Version**
please provide the version you are using (see HACS)
Home Assistant 2021.12.8
**To Reproduce**
There is a problem with the integration and the latest version of home assistant, I cannot install it, it does not want my cookie
`
Logger: custom_components.ytube_music_player.config_flow
Source: custom_components/ytube_music_player/config_flow.py:201
Integration: YouTube Music Player (documentation, issues)
First occurred: 00:09:39 (33 occurrences)
Last logged: 01:11:02

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/config_flow.py", line 191, in async_check_data YTMusic.setup(filepath = user_input[CONF_HEADER_PATH], headers_raw = c) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 164, in setup return setup(filepath, headers_raw) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/setup.py", line 36, in setup raise Exception( Exception: The following entries are missing in your headers: x-goog-authuser, cookie. Please try a different request (such as /browse) and make sure you are logged in.
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/config_flow.py", line 191, in async_check_data YTMusic.setup(filepath = user_input[CONF_HEADER_PATH], headers_raw = c) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 164, in setup return setup(filepath, headers_raw) File "/usr/local/lib/python3.9/site-packages/ytmusicapi/setup.py", line 36, in setup raise Exception( Exception: The following entries are missing in your headers: x-goog-authuser. Please try a different request (such as /browse) and make sure you are logged in.
`

**Additional context**

Thanks

**Comment by KoljaWindeler** [comment]
hi, did you grab the cookie in an incognito session?

**Comment by mckochan** [comment]
I had the same issue, when searching "browse" I had two items come up, only the second one works for me.

**Comment by dico** [comment]
I get "YouTube returned a 403 error, meaning that you login data are not longer valid. Please update the cookie".

Tried multiple times with a fresh new incognito session.
Not sure how long the cookie is valid, but I tried to paste it just a few seconds after login.

Browser: Versjon 97.0.4692.99 (64-bit)
OS: Windows 11


Here is what I tried to copy/paste:
`accept: */*
accept-encoding: gzip, deflate, br
accept-language: nb-NO,nb;q=0.9
authorization: SAPISIDHASH xxx
cache-control: no-cache
content-length: 1905
content-type: application/json
cookie: YSC=xxx; VISITOR_INFO1_LIVE=xxx; CONSENT=PENDING+514; SID=xxx; __Secure-1PSID=xxx; __Secure-3PSID=xxx; HSID=xxx; SSID=xxx; APISID=xxx; SAPISID=xxx; __Secure-1PAPISID=xxx; __Secure-xxx; LOGIN_INFO=xxx; PREF=f6=40000080&tz=Europe.Oslo; SIDCC=xxx; __Secure-xxx
origin: https://www.youtube.com
pragma: no-cache
referer: https://www.youtube.com/signin_prompt?app=desktop&next=https%3A%2F%2Fmusic.youtube.com%2F
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"
sec-ch-ua-arch: "x86"
sec-ch-ua-bitness: "64"
sec-ch-ua-full-version: "97.0.4692.99"
sec-ch-ua-mobile: ?0
sec-ch-ua-model
sec-ch-ua-platform: "Windows"
sec-ch-ua-platform-version: "14.0.0"
sec-fetch-dest: empty
sec-fetch-mode: same-origin
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
x-goog-authuser: 0
x-goog-visitor-id: xxx`
