### ISSUE TITLE
Unable to play a particular playlist

### ISSUE THREAD

**Issue by riz-iqb** [KoljaWindeler/ytube_music_player#167]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
Following error was in the log when I try to start a playlist. This happens to most of the albums/playlists by this artist. My other playlists work without an issue.

2022-01-09 09:46:04 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] play_media, media_type: playlist, media_id: OLAK5uy_k4DXiqmZ95wwpkuHuXfKLbN99b02ZOqFY
2022-01-09 09:46:04 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_prepare_play
2022-01-09 09:46:04 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2022-01-09 09:46:04 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current media_player.april) [E]
2022-01-09 09:46:04 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_on_media_player [E]
2022-01-09 09:46:04 INFO (SyncWorker_9) [pychromecast] Starting app CC1AD845
2022-01-09 09:46:04 INFO (SyncWorker_9) [pychromecast.controllers] Receiver:Launching app CC1AD845
2022-01-09 09:46:04 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher
2022-01-09 09:46:04 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.april: off -> idle ... not playing [E]
2022-01-09 09:46:04 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.april: idle -> idle ... not playing [E]
2022-01-09 09:46:04 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.april: idle -> idle ... not playing [E]
2022-01-09 09:46:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_cipher
2022-01-09 09:46:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_prepare_play
2022-01-09 09:46:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] get_playlist(playlistId=OLAK5uy_k4DXiqmZ95wwpkuHuXfKLbN99b02ZOqFY)
2022-01-09 09:46:05 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
== == == == == == = ytube_music_player Integration Error == == == == == == == ==
2022-01-09 09:46:05 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2022-01-09 09:46:05 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2022-01-09 09:46:05 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:
2022-01-09 09:46:05 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1443, in async_play_media
playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ytube_music_player/media_player.py", line 1443, in <lambda>
playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/playlists.py", line 69, in get_playlist
playlist = {'id': results['playlistId']}
KeyError: 'playlistId'
2022-01-09 09:46:05 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2022-01-09 09:46:05 ERROR (MainThread) [custom_components.ytube_music_player.media_player] == == == == == == = ytube_music_player Integration Error == == == == == == == ==
2022-01-09 09:46:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_off_media_player [E]

**Version**
20211213.01

**To Reproduce**
Pretty much try to play the above playlist. Playlist ID is available in the error log

**Additional context**
I am trying to use this from Australia, in case there is some region issues.

Thanks

**Comment by KoljaWindeler** [comment]
Hi, that can't work .. when i open https://music.youtube.com/playlist?list=OLAK5uy_k4DXiqmZ95wwpkuHuXfKLbN99b02ZOqFY it shows me that I'm looking at a ALBUM not a playlist .. try playing the album with the media_type: album 
JKW
