### ISSUE TITLE
Unable to play a playlist.

### ISSUE THREAD

**Issue by WarC0zes** [KoljaWindeler/ytube_music_player#170]
**Enable DEBUG Output**
```
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:234
Integration: YouTube Music Player (documentation, issues)
First occurred: 07:45:30 (1 occurrences)
Last logged: 07:45:30

async_check_api failed
```
```
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] YtubeMediaPlayer config:
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Header path: /config/.storage/ytube_header.json
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - playlist: input_select.ytube_music_player_playlist
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - mediaplayer: input_select.ytube_music_player_speakers
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - source: input_select.ytube_music_player_source
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - speakerlist: ['media_player.nest_mini']
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - playModes: input_select.ytube_music_player_playmode
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - playContinuous: input_boolean.ytube_music_player_playcontinuous
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - shuffle: False
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - shuffle_mode: 1
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - like_in_name: True
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - track_limit: 25
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - legacy_radio: False
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update
2022-01-18 18:19:26 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_startup
2022-01-18 18:19:26 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.ytube_music_player_extra (<class 'custom_components.ytube_music_player.sensor.yTubeMusicSensor'>) implements device_state_attributes. Please report it to the custom component author.
2022-01-18 18:19:32 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher [E]
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api ... - no valid API, try to login
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] async_check_api failed
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_selects
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - playlist: input_select.ytube_music_player_playlist not found
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - playmode: input_select.ytube_music_player_playmode not found
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - playContinuous: input_boolean.ytube_music_player_playcontinuous not found
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - mediaPlayer: input_select.ytube_music_player_speakers not found
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Source: input_select.ytube_music_player_source not found
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Drop down for media player not found
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input nest_mini/ current ) [E]
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.nest_mini as player
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_playlists
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - no playlist select field, exit
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_update_selects
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_playmode
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_update_playmode 2
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_startup
2022-01-18 18:19:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_update
2022-01-18 18:19:36 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] play_media, media_type: playlist, media_id: PLGskOcLXu5mzKkR0iWyHbwZDKztTsr92t
2022-01-18 18:19:36 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_prepare_play
2022-01-18 18:19:36 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2022-01-18 18:19:36 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current media_player.nest_mini) [E]
2022-01-18 18:19:36 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_on_media_player [E]
2022-01-18 18:19:36 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher
2022-01-18 18:19:36 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.nest_mini: off -> idle ... not playing [E]
2022-01-18 18:19:37 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.nest_mini: idle -> idle ... not playing [E]
2022-01-18 18:19:43 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_cipher
2022-01-18 18:19:43 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_prepare_play
2022-01-18 18:19:43 ERROR (MainThread) [custom_components.ytube_music_player.media_player] get_playlist(playlistId=PLGskOcLXu5mzKkR0iWyHbwZDKztTsr92t)
2022-01-18 18:19:43 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
== == == == == == = ytube_music_player Integration Error == == == == == == == ==
2022-01-17 11:12:25 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2022-01-17 11:12:25 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2022-01-17 11:12:25 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:
2022-01-17 11:12:25 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1443, in async_play_media
playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ytube_music_player/media_player.py", line 1443, in <lambda>
playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/playlists.py", line 66, in get_playlist
response = self._send_request(endpoint, body)
File "/usr/local/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 133, in _send_request
response = self._session.post(YTM_BASE_API + endpoint + YTM_PARAMS + additionalParams,
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/lib/python3.9/http/client.py", line 1279, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1320, in _send_request
self.putheader(hdr, value)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader
_HTTPConnection.putheader(self, header, *values)
File "/usr/local/lib/python3.9/http/client.py", line 1247, in putheader
raise ValueError('Invalid header name %r' % (header,))
ValueError: Invalid header name b''
2022-01-17 11:12:25 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2022-01-17 11:12:25 ERROR (MainThread) [custom_components.ytube_music_player.media_player] == == == == == == = ytube_music_player Integration Error == == == == == == == ==
```

**Describe the bug**
Unable to access or launch a playlist.

**Version**
20211213.01

**To Reproduce**
1.Launch a playlist.

**Additional context**
I redid the cookies thinking that was the problem, but no.

Thanks

**Comment by WarC0zes** [comment]
after the 20220120.01 update, everything works again. thank you
