### ISSUE TITLE
media player not working "__init__: could not find match for ^\w+\W"

### ISSUE THREAD

**Issue by marcomow** [KoljaWindeler/ytube_music_player#171]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/media_player.py:672
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:52:19 (1 occurrences)
Last logged: 19:52:19

[2704441936] __init__: could not find match for ^\w+\W
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/config/custom_components/ytube_music_player/media_player.py", line 1428, in async_play_media
    if(not(await self.async_prepare_play())):
  File "/config/custom_components/ytube_music_player/media_player.py", line 555, in async_prepare_play
    await self.async_get_cipher('BB2mjBuAtiQ')
  File "/config/custom_components/ytube_music_player/media_player.py", line 672, in async_get_cipher
    self._cipher = Cipher(js=self._js)
  File "/usr/local/lib/python3.9/site-packages/pytube/cipher.py", line 39, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W

**Comment by Dillton** [comment]
Hello. 

I am supporting this issue, something is broken. I have exctly the same problem and I was also just opening the issue. @marcomow Thanks to you I dont have to :)

**Comment by samhed** [comment]
I have the exact same issue too

**Comment by KoljaWindeler** [comment]
Damn, here as well .. popped up just a few minutes ago. I'll see what I can do ...

**Comment by KoljaWindeler** [comment]
Already known https://github.com/pytube/pytube/issues/1199 we have to wait for a solution

**Comment by Sonpozy** [comment]
I have the exact same issue too

**Comment by tylerweston** [comment]
> Already known [pytube/pytube#1199](https://github.com/pytube/pytube/issues/1199) we have to wait for a solution

there is a fix posted in that thread now and a pr for the fix submitted. if you need it fixed now though, in pytube>cipher.py change the regex on line 30 from "^\w+\W" to "^\$*\w+\W" seems to solve the problem

**Comment by KoljaWindeler** [comment]
Thanks, I'm watching the thread. I'm loading pytube as dependency and have to wait for a release that contains the fix.

**Comment by CeeWeasel** [comment]
I'm facing the same issue and am watching this thread.

**Comment by Lucho99se** [comment]
I have the exact same issue too

**Comment by KoljaWindeler** [comment]
Hey everyone .. it might take some time until the real fix is implemented at PyTube and I didn't want to wait :D 
So I've published a hot fix, that will be removed once PyTube merged the real fix.
https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20220120.01
Let me know if that works (does here)

**Comment by marcomow** [comment]
I was going to create a pr for this purpose, good job and great user service, thanks a lot!

And all is working fine now, thanks!

**Comment by Dillton** [comment]
> Hey everyone .. it might take some time until the real fix is implemented at PyTube and I didn't want to wait :D So I've published a hot fix, that will be removed once PyTube merged the real fix. https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20220120.01 Let me know if that works (does here)

Hello Kolja. Thank you very much everything is working like a charm :)
