### ISSUE TITLE
Number of Playlists Limit?

### ISSUE THREAD

**Issue by jsermer** [KoljaWindeler/ytube_music_player#172]
At this point this is more of a question, but is there a limit to the number of playlists that are visible in the drop down (input_select.ytube_music_player_playlist)?  My system is only showing 25 and I have quite a few more than 25.

**Comment by jsermer** [comment]
There is an `error` in the logs that might be contributing to it, so I'll paste it here jic:

```
2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1098, in async_update_playlists
    extra_info = await self.hass.async_add_executor_job(self._api.get_playlist, playlist['playlistId'])
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/playlists.py", line 104, in get_playlist
    playlist['tracks'].extend(parse_playlist_items(results['contents']))
KeyError: 'contents'

2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == == 


2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1098, in async_update_playlists
    extra_info = await self.hass.async_add_executor_job(self._api.get_playlist, playlist['playlistId'])
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/playlists.py", line 90, in get_playlist
    playlist['year'] = nav(header, SUBTITLE3)
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav
    raise err
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav
    root = root[k]
IndexError: list index out of range

2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2022-01-20 08:06:31 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == == 


2022-01-20 08:06:32 WARNING (MainThread) [homeassistant.components.input_select] Current option: loading no longer valid (possible options: '00s Alternative Hits, '00s Indie Scene, '10s Alternative, '10s Americana, '90s Alternative Rock Hits, '90s Frat BBQ, 2021 Recap, Ain't No Rest for the Wicked, Artists to Watch 2017, Beach Grooves, Blogged 50, Blues & Garage Rock Revival, By the Blaze of the Bonfire, Chill Supermix, Chilled Soul and Jazz Remixed, Classic Rock Summer, Classic Rock Wake-Up Call, Classic Rock Workout, Classic Rock's Greatest Hits, Country Beach Vacay, Country Rock , Country Tailgate, Discover Mix, Essential '00s Hip Hop, Your Likes)
```

**Comment by KoljaWindeler** [comment]
Hi, that's indeed hardcoded to 25 at the moment .. I'll check if I can convert that to the generic limit that you can change (in the configuration of the integration) ... 

can you give me more background info to the 2nd entry. what works, what not, when does it happen etc

**Comment by jsermer** [comment]
Thanks for the quick response.  A configurable limit would be great...I'll continue watching this space for new developments.

The other error messages occur every time I restart HA but do not seem to prevent me from using your integration.  If there wasn't a limit, then I thought maybe the errors could be contributing to only seeing 25 playlists, but that's not the case.  If you want more info on the errors, I can enable debug mode...just let me know.

Thanks

**Comment by KoljaWindeler** [comment]
That would indeed help .. so you can listen to music, correct? and you can see you playlists (in part in the dropdown and in the media_browser) correct?
JKW

**Comment by jsermer** [comment]
Yep, I can listen to music (and do...awesome integration btw) and see max 25 playlists.  I'll put things in debug mode and get a bigger dump of what's going on...standby

**Comment by jsermer** [comment]
```
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Config via Storage/UI
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] YtubeMediaPlayer config: 
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Header path: /config/.storage/ytube_header.json
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - playlist: input_select.ytube_music_player_playlist
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - mediaplayer: input_select.ytube_music_player_speakers
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - source: input_select.ytube_music_player_source
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - speakerlist: ['media_player.kitchen_display']
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - playModes: input_select.ytube_music_player_playmode
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - playContinuous: input_boolean.ytube_music_player_playcontinuous
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - shuffle: False
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - shuffle_mode: 1
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - like_in_name: True
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - track_limit: 99
2022-01-21 09:10:05 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - legacy_radio: True
2022-01-21 09:10:06 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update [E]
2022-01-21 09:10:14 DEBUG (MainThread) [custom_components.ytube_music_player.sensor] Config via Storage/UI
2022-01-21 09:10:14 DEBUG (MainThread) [custom_components.ytube_music_player.sensor] init ytube sensor done
2022-01-21 09:10:15 DEBUG (MainThread) [custom_components.ytube_music_player.sensor] updating ytube sensor
2022-01-21 09:10:31 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_startup
2022-01-21 09:10:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher [E]
2022-01-21 09:10:34 DEBUG (MainThread) [custom_components.ytube_music_player.const] - login without brand ID
2022-01-21 09:10:36 WARNING (SyncWorker_39) [charset_normalizer] Trying to detect encoding from a tiny portion of (9) byte(s).
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api ... - no valid API, try to login ... YouTube Api initialized ok, version: 0.19.5 [E]
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_selects
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Adding 23 player to the dropdown
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_playlists
2022-01-21 09:10:39 WARNING (MainThread) [homeassistant.components.input_select] Current option: loading no longer valid (possible options: Kitchen Display, Playroom Speaker, Shop Speaker, Roku Streaming Stick+, Main Floor Group, Denon DLNA, Backyard Group, Basement TV, Basement Speaker, Murphy Room Home, Backyard Speaker, Madelyn's Speaker, Shield TV, Nvidia Shield TV, Upstairs Group, Entire House Group, Living Room Home, Entire Property Group, Living Room TV, Murphy Room Speaker, Master Bedroom Speaker, denon, denon)
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source_helper
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Translated friendly name Kitchen Display to entity id kitchen_display
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source_helper
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source(kitchen_display)
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.kitchen_display/ current )  [E]
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.kitchen_display as player
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack passed
2022-01-21 09:10:39 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source
2022-01-21 09:10:40 DEBUG (MainThread) [custom_components.ytube_music_player.media_player]  - 25 Playlists loaded
2022-01-21 09:10:40 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get_playlist count for playlist ID 'LM' setting it to 25
2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1098, in async_update_playlists
    extra_info = await self.hass.async_add_executor_job(self._api.get_playlist, playlist['playlistId'])
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/playlists.py", line 104, in get_playlist
    playlist['tracks'].extend(parse_playlist_items(results['contents']))
KeyError: 'contents'

2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == == 


2022-01-21 09:10:40 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get_playlist count for playlist ID 'LRYRY34Y0e2XuvgHUUTbmEf0jhDue-zaAMqiw' setting it to 25
2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1098, in async_update_playlists
    extra_info = await self.hass.async_add_executor_job(self._api.get_playlist, playlist['playlistId'])
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/mixins/playlists.py", line 90, in get_playlist
    playlist['year'] = nav(header, SUBTITLE3)
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav
    raise err
  File "/usr/local/lib/python3.9/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav
    root = root[k]
IndexError: list index out of range

2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2022-01-21 09:10:40 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == == 


2022-01-21 09:10:42 DEBUG (MainThread) [custom_components.ytube_music_player.sensor] updating ytube sensor
2022-01-21 09:10:42 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_extra_sensor [E]
2022-01-21 09:10:42 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_update_playlists
2022-01-21 09:10:42 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_update_selects
2022-01-21 09:10:42 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_playmode
2022-01-21 09:10:42 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Selection field input_select.ytube_music_player_playmode not found, skipping
2022-01-21 09:10:42 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_update_playmode 2
2022-01-21 09:10:42 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_startup
2022-01-21 09:10:42 WARNING (MainThread) [homeassistant.components.input_select] Current option: loading no longer valid (possible options: '00s Alternative Hits, '00s Indie Scene, '10s Alternative, '10s Americana, '90s Alternative Rock Hits, '90s Frat BBQ, 2021 Recap, Ain't No Rest for the Wicked, Artists to Watch 2017, Beach Grooves, Blogged 50, Blues & Garage Rock Revival, By the Blaze of the Bonfire, Chill Supermix, Chilled Soul and Jazz Remixed, Classic Rock Summer, Classic Rock Wake-Up Call, Classic Rock Workout, Classic Rock's Greatest Hits, Country Beach Vacay, Country Rock , Country Tailgate, Discover Mix, Essential '00s Hip Hop, Your Likes)
2022-01-21 09:10:42 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack resub
```

**Comment by jsermer** [comment]
The `LRYRY34Y0e2XuvgHUUTbmEf0jhDue-zaAMqiw` playlist is my 2021 recap playlist fwiw and `LM` is my likes (which is empty by design).

Also, the following message:

```
Selection field input_select.ytube_music_player_playmode not found, skipping
```

I confirmed that I do in fact have that input_select in my list of entities, so I'm not sure why it says 'not found'

**Comment by jsermer** [comment]
Just updated and I can now see all of my playlists... Thanks for the quick enhancement
