### ISSUE TITLE
Add support for brand accounts

### ISSUE THREAD

**Issue by simonmannsfeld** [KoljaWindeler/ytube_music_player#18]
I reinstalled ytube_music_player but I get the same error.

```
Logger: homeassistant
Source: custom_components/ytube_music_player/media_player.py:387
First occurred: 19:07:51 (1 occurrences)
Last logged: 19:07:51

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 356, in _update_sources
    self._update_playlists()
  File "/config/custom_components/ytube_music_player/media_player.py", line 387, in _update_playlists
    self._playlists = self._api.get_library_playlists(limit = 99)
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py", line 29, in get_library_playlists
    results = find_object_by_key(nav(response, SINGLE_COLUMN_TAB + SECTION_LIST),
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 148, in nav
    raise err
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 142, in nav
    root = root[k]
KeyError: 'contents'
```

**Comment by simonmannsfeld** [comment]
Sometimes this error occures. I guess this means more or less the same.

```
Logger: homeassistant
Source: core.py:1405
First occurred: 23:19:35 (1 occurrences)
Last logged: 23:19:35

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 356, in _update_sources
    self._update_playlists()
  File "/config/custom_components/ytube_music_player/media_player.py", line 407, in _update_playlists
    self.hass.services.call(input_select.DOMAIN, input_select.SERVICE_SET_OPTIONS, data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1363, in call
    return asyncio.run_coroutine_threadsafe(
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/core.py", line 1405, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: length of value must be at least 1 for dictionary value @ data['options']
```

**Comment by KoljaWindeler** [comment]
This is something from way down the api. Could you try to repeat the cookies generation process? Basically my suspicion is that your cookie isn't correct or complete and thus the api generates some errors.

**Comment by simonmannsfeld** [comment]
Thank you @KoljaWindeler for your quick answer. I faced the problem and now it works.

Cookie was good.

This problem occured if you got no playlists and no given likes to any song. Recently and in the past I ever used a "brand account".

**Issue 1: No playlists causes this error.**

I guess it would be great to receive a better error for this.

**Issue 2: "Brand accounts" are not supported by your integration.**

It would be great if you could add an input field to the UI (Integrations->Options) for "brand account id".

[Brand account support with ytmusicapi](https://ytmusicapi.readthedocs.io/en/latest/usage.html#brand-accounts)
This helped me out. I just hardcoded my "brand account id" to your code and it works! There is a litte issue at the linked docs. The "brand account id" have to be a string.

So

`self._api = YTMusic(config.get(CONF_HEADER_PATH, default_header_file), "123456789012345678901")`

works instead of

`self._api = YTMusic(config.get(CONF_HEADER_PATH, default_header_file), 123456789012345678901)`

**Comment by KoljaWindeler** [comment]
great work, will add support for bran accounts !

**Comment by KoljaWindeler** [comment]
Hi, please try the latest commit https://github.com/KoljaWindeler/ytube_music_player/commit/6a3df9188da76172a9eae9e1de9664f2648c4c77
this will add support for brand accounts. 

Please provide this in the yaml:

```
media_player:
  - platform: ytube_music_player
    brand_id: "asdf"
```

**Comment by simonmannsfeld** [comment]
It is just working! Great job, @KoljaWindeler. Issue closed.

I will watch your development. Great component!
