### ISSUE TITLE
Speakers "loading"

### ISSUE THREAD

**Issue by Nemesis24** [KoljaWindeler/ytube_music_player#183]
**Describe the bug**
I've got this error:

yTubeMediaPlayer error
Please select a player before start playing, e.g. via the 'media_player.select_source' method or in the settings/config_flow

No player selected or the selected player isn't available (media_player.loading/), you will not be able to play music, please set the default player in the settings/config_flow or call media_player.select_source

**Version**
Home Assistant 2022.3.0b2

**To Reproduce**
 - play something

**Additional context**

Thanks

**Comment by Nemesis24** [comment]
Hi, yes it works, everyday this is my best way to awake the house 😜.

**Comment by KoljaWindeler** [comment]
So it works but you constantly get that error?

**Comment by Nemesis24** [comment]
Yes constantly.

**Comment by KoljaWindeler** [comment]
Strange. Could you enable debug, start the playback and copy the output into this ticket?

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player#1-reroute-debug-output-to-error-via-service

**Comment by Nemesis24** [comment]
ok with service:

`Please select a player before start playing, e.g. via the 'media_player.select_source' method or in the settings/config_flow`

 with configuration.yaml, I've got:

```
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:265
Integration: YouTube Music Player ([documentation](https://github.com/KoljaWindeler/ytube_music_player), [issues](https://github.com/KoljaWindeler/ytube_music_player/issues))
First occurred: 09:45:16 (2 occurrences)
Last logged: 10:07:48

No player selected or the selected player isn't available (media_player.loading/), you will not be able to play music, please set the default player in the settings/config_flow or call media_player.select_source
```

**Comment by Nemesis24** [comment]
![Sans titre](https://user-images.githubusercontent.com/25956796/155876238-d6d68864-e6e3-4c0e-802c-980f3af3eaa4.png)

**Comment by KoljaWindeler** [comment]
Ok, but you do have a Mediaplayer to play the music on, like a Chromecast or something in Homeassistent, right ?

**Comment by Nemesis24** [comment]
![Sans titre](https://user-images.githubusercontent.com/25956796/155876939-3974c434-0e3f-44d0-8639-24184f2f97cd.png)
Yes

**Comment by KoljaWindeler** [comment]
Strange. Could you enable debug like this https://github.com/KoljaWindeler/ytube_music_player#2-let-homeassistant-show-debug-information
Restart Homeassistent and copy all lines to this ticket?

**Comment by Nemesis24** [comment]
I think this is linked
```
Logger: homeassistant.core
Source: components/input_select/__init__.py:354
First occurred: 10:43:53 (1 occurrences)
Last logged: 10:43:53

Error executing service: <ServiceCall input_select.set_options (c:ef855fef8f1e452cc7909d4c72e8eae9): options=['Ecran', 'Enceinte', 'Enceinte', 'Enceinte', 'Ecran', 'Enceinte', 'Maison', 'Enceinte', 'Mibox Parents', 'Enceinte', 'Mibox Iban', 'Salon-TV', 'Mibox Salon', 'Mibox Orlan', 'Ecran', 'Cellier', 'Clé TV Mi', 'Iban-MI'], entity_id=['input_select.ytube_music_player_speakers']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1654, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/input_select/__init__.py", line 354, in async_set_options
    raise HomeAssistantError(f"Duplicated options: {options}")
homeassistant.exceptions.HomeAssistantError: Duplicated options: ['Ecran', 'Enceinte', 'Enceinte', 'Enceinte', 'Ecran', 'Enceinte', 'Maison', 'Enceinte', 'Mibox Parents', 'Enceinte', 'Mibox Iban', 'Salon-TV', 'Mibox Salon', 'Mibox Orlan', 'Ecran', 'Cellier', 'Clé TV Mi', 'Iban-MI']

```

**Comment by Nemesis24** [comment]
```
Logger: homeassistant.components.input_select
Source: components/input_select/__init__.py:295
Integration: Sélection ([documentation](https://rc.home-assistant.io/integrations/input_select), [issues](https://github.com/home-assistant/home-assistant/issues?
```q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+input_select%22))
First occurred: 10:43:53 (1 occurrences)
Last logged: 10:43:53

Invalid option: Ecran (possible options: loading)

**Comment by Nemesis24** [comment]
```
Logger: homeassistant.components.input_select
Source: components/input_select/__init__.py:359
Integration: Sélection ([documentation](https://rc.home-assistant.io/integrations/input_select), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+input_select%22))
First occurred: 10:43:54 (1 occurrences)
Last logged: 10:43:54

Current option: loading no longer valid (possible options: Basque, Matin, Melissa & Marina Doya, Pmj, Sab, Sympa, Your Likes)
```

**Comment by KoljaWindeler** [comment]
Spot on ... I'll see what I can do ..

**Comment by Nemesis24** [comment]
ok for me it's ok I change the name of my speakers to be unique, and all works fine.
Thanks for all.
