### ISSUE TITLE
Airplay devices as speaker

### ISSUE THREAD

**Issue by rimonhanna** [KoljaWindeler/ytube_music_player#188]
`**Enable` DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
I can’t seam to be able to set an airplay device as the destination speaker, i tried Apple TV (with youtube app installed and logged in as the same user), Homepod mini, Marantz receiver with no luck

**Version**
20220303.01

**To Reproduce**
1. play anything with the addon
2. set speaker/source to an airplay device
3. nothing happens

Logs:
```
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/apple_tv/media_player.py:292 
Integration: Apple TV 
First occurred: 08:55:53 (6 occurrences) 
Last logged: 09:30:21

Error executing service: <ServiceCall media_player.play_media (c:32a6b2117c382562ca85567d6b4cfc02): entity_id=['media_player.living_room'], extra=metadata=metadataType=3, title=Amarain, artist=Amr Diab, images=[{'url': 'https://lh3.googleusercontent.com/cxpXP1W58hFGRUGS4edrkU1Wqdz6uDXi-snNa8cNHiaNilA3fKBeuUgrYr1prL7cvwHpTr-SCpVxGaM-=w120-h120-l90-rj'}], media_type=music, media_id=https://rr1---sn-5hne6nzs.googlevideo.com/videoplayback?expire=1649508835&ei=gy1RYqjGGbSWx_APo_uQ4A4&ip=80.56.156.81&id=o-AC-MxAnOGKAgcXca6LzB4RlZmusqEDHvpgAKfeukiSOM&itag=141&source=youtube&requiressl=yes&mh=fY&mm=31%2C26&mn=sn-5hne6nzs%2Csn-4g5lznek&ms=au%2Conr&mv=m&mvi=1&pl=17&ctier=A&pfa=5&gcr=nl&initcwndbps=2200000&hightc=yes&spc=4ocVCzlfx4NfvgUw1cmgHNajDz3tDuHww0lByz5Dqw&vprv=1&mime=audio%2Fmp4&ns=cIJGFJSEDo5t9pk81Dkt9iYG&gir=yes&clen=8639611&dur=268.319&lmt=1565903399285828&mt=1649486972&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB_REMIX&txp=5431432&n=8D1EKEYS0P9g_BFXQM&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKDcX1Un0jrtS24wJDgZ6gj6A5lgaciTr3XaGrk2ElzvAiAidTUGodMPTsuBAFZYj9DIBFsNcOU_yIvynYPHuJNG_g%3D%3D&sig=AOq0QJ8wRQIhAJgyBXIctKC608AIBt56VHBriBf7mfZJ_ijmdOq1-XUGAiAk9YURhfpP200wDq1_aQ5qnP-4-cMH0MOvzTQROOjIbw==>
Error executing service: <ServiceCall media_player.play_media (c:c2c6c84006d49aa6138f57adeecc4869): entity_id=['media_player.living_room_apple_tv'], extra=metadata=metadataType=3, title=Fever, artist=Peggy Lee, images=[{'url': 'https://lh3.googleusercontent.com/oTxZ0aqMdW3Isvyqxw0PsttYS8NRX9x83wL6k07wkQMiVx9z3A9qBPkitp_ukZfliq2FxKh75xlKpARE=w120-h120-l90-rj'}], media_type=music, media_id=https://rr4---sn-5hnekn7s.googlevideo.com/videoplayback?expire=1649509507&ei=IzBRYqviIoHQ1wKOw63IDw&ip=80.56.156.81&id=o-AAGqngH-J8MFQt2CO7zbcVVI1A7W4ok5yVCELCOrTLmp&itag=141&source=youtube&requiressl=yes&mh=Ys&mm=31%2C29&mn=sn-5hnekn7s%2Csn-5hne6nzs&ms=au%2Crdu&mv=m&mvi=4&pl=17&ctier=A&pfa=5&gcr=nl&initcwndbps=2158750&hightc=yes&spc=4ocVC3u9yH5TVK3AcnrCAv_VnCZ6xr3A_uXfu3Spdw&vprv=1&mime=audio%2Fmp4&ns=WdNfJFk611_GqyYvK56-PhEG&gir=yes&clen=6550082&dur=203.439&lmt=1635586896565058&mt=1649487418&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB_REMIX&txp=5432434&n=iJBKM4By-z4biSKl7k&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgL5v1K7P9u4cwCy2JdMwGmy-mqHfQadQut6URlBI19R0CIBVHsxzzvElZ0H8AbXqM4rclPP1AfWL6mmHgjjMx8k2t&sig=AOq0QJ8wRQIhANHwQYqoXioIr-gHYZT5iI_e4159dukEso7-bdnwziB9AiA2nfyj1EJtHEaRIWe5b1VrBRv6Lt0KaPLm5txCUmbJQQ==>
Error executing service: <ServiceCall media_player.play_media (c:9dfd40602949cfe02f07c0d55531914f): entity_id=['media_player.living_room_apple_tv'], extra=metadata=metadataType=3, title=Cheek to Cheek, artist=Steve Tyrell, images=[{'url': 'https://lh3.googleusercontent.com/oNmvDM9ECg0WVhYncTZcJkffiFn2GXlweQMHXeFZAxjzN5wpwglnxcsGZCFWCt-H3WOEPBROmBSLBvzl=w120-h120-l90-rj'}], media_type=music, media_id=https://rr5---sn-5hnekn7k.googlevideo.com/videoplayback?expire=1649509979&ei=-zFRYrTEK6qG6dsP76am8As&ip=80.56.156.81&id=o-AEJA16ev7JqJX7cO4W9l19qvyR_qnUTTcqaTY0BNLNDk&itag=141&source=youtube&requiressl=yes&mh=JN&mm=31%2C29&mn=sn-5hnekn7k%2Csn-5hne6nzk&ms=au%2Crdu&mv=m&mvi=5&pl=17&ctier=A&pfa=5&gcr=nl&initcwndbps=2380000&hightc=yes&spc=4ocVCygqUy2uQpKeEyyQEkrbZuSz3KVOQhESfwRrqA&vprv=1&mime=audio%2Fmp4&ns=5nhj7NcOeypWmGz1oomGPlEG&gir=yes&clen=7270165&dur=225.799&lmt=1565946785404821&mt=1649487902&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB_REMIX&txp=1311222&n=xMQITSRyegeNpVO13r&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIhddi_7Za3T8j1ULbJzPtSVgXNTwhmVzzEfkAhwd7tZAiEA1ugPvhTdOk2Y3Pu66mGaorqxHxk4lCscGdcAO6oO-jw%3D&sig=AOq0QJ8wRQIhAPZOMEW-HbEfZa7_TFGelIpmhWOSRBBbvEtEvXGsw6saAiA-09uJ-IrB1qD-ASqLpDnsLd6gj9ARXqK4WSrMrEkCFA==>
Error executing service: <ServiceCall media_player.play_media (c:f4131e3ed5dfbee686430ecd29c91c10): entity_id=['media_player.living_room_apple_tv'], extra=metadata=metadataType=3, title=The Very Thought Of You, artist=Nat King Cole, images=[{'url': 'https://lh3.googleusercontent.com/mi-haESDF_9Tp7Rcj5Cv0FhfhrAeBiG-La1G19RUl0lUtsqX9dzsm_4sVLrNq-HOU7o7KG2OnHalgPi3=w120-h120-l90-rj'}], media_type=music, media_id=https://rr1---sn-5hnedn7e.googlevideo.com/videoplayback?expire=1649510307&ei=QjNRYq3vPILA8gPZ1IfgAg&ip=80.56.156.81&id=o-AAplnAa1oThbEoUlfq9lI8BuxFuMjz327rEh0cVtERIn&itag=141&source=youtube&requiressl=yes&mh=ZI&mm=31%2C29&mn=sn-5hnedn7e%2Csn-5hne6ns6&ms=au%2Crdu&mv=m&mvi=1&pl=17&ctier=A&pfa=5&gcr=nl&initcwndbps=2095000&hightc=yes&spc=4ocVC8qX9N_NAEN8YGgaaeZNpyXO0j5LTXiken67dw&vprv=1&mime=audio%2Fmp4&ns=j_LefCJstm0VcXOnzV7T1jgG&gir=yes&clen=7364004&dur=228.693&lmt=1581788650843563&mt=1649488395&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB_REMIX&txp=5531432&n=_cAnkYMyUZxYjmRCUI&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIh0SZHL3NztlHPXJEJo209zt7QVuJm5mWwr0theCzHNAiEA01H7wTH641Vr5I__TLPHYbxakFjkowaHPRp4BjAQnfA%3D&sig=AOq0QJ8wRQIgGyNha4c8pNI0vYdD3gMmChPXOtAaqT7AS3g-Cru3sc4CIQC5_lbFgVbDIOTH1Oau_60NQNCoBBD9PWt5kXwM-5Yvog==>
Error executing service: <ServiceCall media_player.play_media (c:857d6e41530b4700ec67b06f1b09f788): entity_id=['media_player.living_room_apple_tv'], extra=metadata=metadataType=3, title=Autumn Leaves, artist=New York Jazz Lounge, images=[{'url': 'https://lh3.googleusercontent.com/YvXUtDfSzt_iTqXvBPVaNXA0wkF8LDuRA_kdjU7XxGVR8F6fQOGWCcn3iP-wBR1s9ksvmcuKYE97WjlT=w120-h120-l90-rj'}], media_type=music, media_id=https://rr4---sn-5hne6nzk.googlevideo.com/videoplayback?expire=1649510770&ei=ETVRYr6KOdiF6dsPlYOD-AU&ip=80.56.156.81&id=o-AHt1H16WVyHUiAKhlXTxa4u6ZwunG0pQcQhceyPsDeD9&itag=141&source=youtube&requiressl=yes&mh=1m&mm=31%2C26&mn=sn-5hne6nzk%2Csn-4g5e6nz7&ms=au%2Conr&mv=m&mvi=4&pl=17&ctier=A&pfa=5&gcr=nl&initcwndbps=2068750&hightc=yes&spc=4ocVCx75ib8mZ1Bdnrs0aqQfRHZtk09Oqs9xDSdNWQ&vprv=1&mime=audio%2Fmp4&ns=foBh-9Tp731IOeYS28wDvnMG&gir=yes&clen=11665397&dur=362.371&lmt=1600393227662820&mt=1649488885&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB_REMIX&txp=1311222&n=d3qwiZ0SjPhXpHnStR&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgNB2Jj5Kw2RfP4x-QFIoAK4KUOkJ2lWkLDJOEwG-ak0wCIQD0suvEWjFkE1DPcPzzaiZKfH-l2uzc6n4yHYLsr-4zJg%3D%3D&sig=AOq0QJ8wRAIgKn9E_XcfljSjNaBJbhYOA4PkKQ2m_LV5fzcDPqXlQBkCIA7GU1X4j_T-DN3gshU9oO_ehjzounzLEkGy2R2WxMfI>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1652, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/apple_tv/media_player.py", line 292, in async_play_media
    await self.atv.stream.stream_file(media_id)
  File "/usr/local/lib/python3.9/site-packages/pyatv/core/facade.py", line 382, in stream_file
    await self.relay("stream_file")(file, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/__init__.py", line 371, in stream_file
    audio_file = await open_source(
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/audio_source.py", line 483, in open_source
    return await InternetSource.open(source, sample_rate, channels, sample_size)
  File "/usr/local/lib/python3.9/site-packages/pyatv/protocols/raop/audio_source.py", line 362, in open
    stream_generator = await loop.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/miniaudio.py", line 1216, in stream_any
    raise DecodeError("failed to init decoder", result)
miniaudio.DecodeError: ('failed to init decoder', -17)

```

Thanks

**Comment by esteban-uo** [comment]
facing same

**Comment by nitylouta** [comment]
same, redirects to server on my Musiccast integration

**Comment by KoljaWindeler** [comment]
please test this https://github.com/KoljaWindeler/ytube_music_player?tab=readme-ov-file#method-2-owntone-server-as-proxy and reopen if it isn't working
