### ISSUE TITLE
Can't view library albums

### ISSUE THREAD

**Issue by samhed** [KoljaWindeler/ytube_music_player#210]
**Describe the bug**

When using the media browser to try to view library albums I get the a red box saying "Unkown Error". The following appears in the log when this happens:

```
Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response await func(hass, connection, msg) File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1172, in websocket_browse_media payload = await player.async_browse_media(media_content_type, media_content_id) File "/config/custom_components/ytube_music_player/media_player.py", line 1977, in async_browse_media response = await build_item_response(self, payload) File "/config/custom_components/ytube_music_player/browse_media.py", line 555, in build_item_response response.calculate_children_class() File "/usr/src/homeassistant/homeassistant/components/media_player/browse_media.py", line 151, in calculate_children_class proposed_class = self.children[0].media_class IndexError: list index out of range
```

After restarting home assistant I got this in the log, perhaps it's related:

```
https://github.com/KoljaWindeler/ytube_music_player/issues
and paste the following output:
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1517, in async_play_media self._tracks = await self.hass.async_add_executor_job(lambda: self._api.get_watch_playlist(r_track['videoId'], limit=self._trackLimit)) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1517, in <lambda> self._tracks = await self.hass.async_add_executor_job(lambda: self._api.get_watch_playlist(r_track['videoId'], limit=self._trackLimit)) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/watch.py", line 69, in get_watch_playlist response = self._send_request(endpoint, body) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/ytmusic.py", line 142, in _send_request raise Exception(message + error) Exception: Server returned HTTP 404: Not Found. Requested entity was not found.
thanks, Kolja
== == == == == == = ytube_music_player Integration Error == == == == == == == ==
```

**Version**
2022041502

**To Reproduce**
1. Go to Media Browser
2. Select Ytube Media Player
3. Click on Library Albums 

**Additional context**
These above steps have worked for months, and worked as late as yesterday. I didn't upgrade Ytube Music or Home Assistant recently. Perhaps YouTube have changed something on their end?

**Comment by samhed** [comment]
Issue remains with ytube_music_player version 20230321.01 and HA 2023.10.1.

**Comment by KoljaWindeler** [comment]
hi, please reopen if this is still an issue

**Comment by samhed** [comment]
Can not reproduce with ytube_music_player version 20240112.01 and HA 2024.1.3, thanks for fixing this!
