### ISSUE TITLE
IncompleteRead error on start of play

### ISSUE THREAD

**Issue by salleq** [KoljaWindeler/ytube_music_player#212]
I mostly use automations to start play certain playlist, or for instance my personal "Supermix" on a specific device.

For some reason i keep getting these IncompleteRead errors - usually a few times in a row if I try immediately again, but then it works again after a moment.

I'm not sure if this has happened earlier or not, but mostly it's been working so I haven't paid much attention. My HASS installation is 2022.10.4 docker version. The error comes quite fast after running the automation, and the part where it says how many bytes read isn't constant. Sometimes it's something out of something (like in below snippet), othertimes its 0 bytes of 0 bytes.

```
2022-10-18 17:32:22.435 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source(chromecastultra1449)
2022-10-18 17:32:22.436 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - was playing
2022-10-18 17:32:22.436 ERROR (MainThread) [custom_components.ytube_music_player.media_player] async_media_stop
2022-10-18 17:32:22.437 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - player found
2022-10-18 17:32:22.439 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - async_media_stop -> media_player.chromecastultra1449
2022-10-18 17:32:22.439 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.chromecastultra1449/ current media_player.chromecastultra1449) 
2022-10-18 17:32:22.440 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  no change [E]
2022-10-18 17:32:22.440 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.chromecastultra1449 as player
2022-10-18 17:32:22.441 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_track
2022-10-18 17:32:22.441 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Playing track nr 1 / 32
2022-10-18 17:32:22.442 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url
2022-10-18 17:32:22.443 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2022-10-18 17:32:22.443 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - try to find URL on our own
2022-10-18 17:32:22.476 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.chromecastultra1449: playing -> idle ... not playing [E]
2022-10-18 17:32:22.495 INFO (SyncWorker_1) [pychromecast.controllers] Receiver:setting volume to 0.8
2022-10-18 17:32:22.590 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - self decoded URL via cipher
2022-10-18 17:32:22.651 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_url
2022-10-18 17:32:22.652 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - forwarding url to player media_player.chromecastultra1449
2022-10-18 17:32:22.653 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_extra_sensor [E]
2022-10-18 17:32:22.721 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.chromecastultra1449: idle -> idle [E]
2022-10-18 17:32:22.739 INFO (SyncWorker_0) [pychromecast.controllers] Receiver:setting volume to 0.8
2022-10-18 17:32:22.986 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.chromecastultra1449: idle -> playing [E]
2022-10-18 17:32:23.011 INFO (SyncWorker_1) [pychromecast.controllers] Receiver:setting volume to 0.8
2022-10-18 17:32:23.233 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.chromecastultra1449 [E]
2022-10-18 17:32:23.438 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_track
2022-10-18 17:32:23.439 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source
2022-10-18 17:32:23.483 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.chromecastultra1449: playing -> playing [E]
2022-10-18 17:32:23.489 ERROR (MainThread) [custom_components.ytube_music_player.media_player] set_shuffle: True
2022-10-18 17:32:23.490 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] _tracks_to_attribute
2022-10-18 17:32:23.491 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_extra_sensor [E]
2022-10-18 17:32:23.493 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_extra_sensor [E]
2022-10-18 17:32:23.498 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] _tracks_to_attribute
2022-10-18 17:32:23.516 INFO (SyncWorker_8) [pychromecast.controllers] Receiver:setting volume to 0.8
2022-10-18 17:32:23.975 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.chromecastultra1449: playing -> buffering [E]
2022-10-18 17:32:23.991 INFO (SyncWorker_3) [pychromecast.controllers] Receiver:setting volume to 0.8
2022-10-18 17:32:24.478 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.chromecastultra1449: buffering -> playing [E]
2022-10-18 17:32:24.545 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] play_media, media_type: playlist, media_id: PLwm1A6bR-KUC91uXF12MvssfqhM2iqiVe
2022-10-18 17:32:24.545 INFO (SyncWorker_5) [pychromecast.controllers] Receiver:setting volume to 0.8
2022-10-18 17:32:24.546 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_prepare_play
2022-10-18 17:32:24.546 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2022-10-18 17:32:24.547 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current media_player.chromecastultra1449)  [E]
2022-10-18 17:32:24.547 ERROR (MainThread) [custom_components.ytube_music_player.media_player] async_media_stop
2022-10-18 17:32:24.547 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - async_media_stop -> media_player.chromecastultra1449
2022-10-18 17:32:24.621 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher
2022-10-18 17:32:24.622 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.chromecastultra1449: playing -> idle ... not playing [E]
2022-10-18 17:32:24.641 INFO (SyncWorker_0) [pychromecast.controllers] Receiver:setting volume to 0.8
2022-10-18 17:32:24.939 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140637343074336] IncompleteRead(1377356 bytes read, 727260 more expected)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 202, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/ytube_music_player/media_player.py", line 1465, in async_play_media
    if(not(await self.async_prepare_play())):
  File "/config/custom_components/ytube_music_player/media_player.py", line 588, in async_prepare_play
    await self.async_get_cipher('BB2mjBuAtiQ')
  File "/config/custom_components/ytube_music_player/media_player.py", line 704, in async_get_cipher
    self._js = await self.hass.async_add_executor_job(request.get, js_url)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pytube/request.py", line 42, in get
    return _execute_request(url, headers=extra_headers).read().decode("utf-8")
  File "/usr/local/lib/python3.10/http/client.py", line 481, in read
    s = self._safe_read(self.length)
  File "/usr/local/lib/python3.10/http/client.py", line 632, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(1377356 bytes read, 727260 more expected)
2022-10-18 17:32:27.686 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.chromecastultra1449 ... not playing [E]
2022-10-18 17:32:31.066 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.chromecastultra1449 ... not playing [E]
2022-10-18 17:32:38.439 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.chromecastultra1449 ... not playing [E]

```

**Comment by KoljaWindeler** [comment]
hi, please reopen if this is still an issue
