### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '1,224'

### ISSUE THREAD

**Issue by t-ice** [KoljaWindeler/ytube_music_player#22]
```
2020-12-16 20:55:11 ERROR (SyncWorker_4) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 407, in _update_playlists
extra_info = self._api.get_playlist(playlistId=playlist['playlistId'])
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 91, in get_playlist
song_count = to_int(
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/helpers.py", line 71, in to_int
return locale.atoi(number)
File "/usr/local/lib/python3.8/locale.py", line 330, in atoi
return int(delocalize(string))
ValueError: invalid literal for int() with base 10: '1,224'
2020-12-16 20:55:11 ERROR (SyncWorker_4) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2020-12-16 20:55:11 ERROR (SyncWorker_4) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================
```

**Comment by KoljaWindeler** [comment]
https://github.com/sigma67/ytmusicapi/issues/125?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE0MDYyNzMwOTU6NDcxMzE0#event-4129429628
