### ISSUE TITLE
Errors at startup

### ISSUE THREAD

**Issue by mfabiani53** [KoljaWindeler/ytube_music_player#220]
At every startup i get the following errors....
```
2022-11-27 11:47:34.756 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1102, in async_update_playlists
    extra_info = await self.hass.async_add_executor_job(self._api.get_playlist, playlist['playlistId'])
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/playlists.py", line 93, in get_playlist
    unicodedata.normalize("NFKD", header['secondSubtitle']['runs'][0]['text']))
KeyError: 'runs'
```

**Comment by dugurs** [comment]
The same error is occurring.
```
2023-07-06 10:21:11.507 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1102, in async_update_playlists
    extra_info = await self.hass.async_add_executor_job(self._api.get_playlist, playlist['playlistId'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/playlists.py", line 132, in get_playlist
    unicodedata.normalize("NFKD", header['secondSubtitle']['runs'][0]['text']))
                                  ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'runs'
```

**Comment by ch3funio** [comment]
same here
`Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1102, in async_update_playlists extra_info = await self.hass.async_add_executor_job(self._api.get_playlist, playlist['playlistId']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/playlists.py", line 132, in get_playlist unicodedata.normalize("NFKD", header['secondSubtitle']['runs'][0]['text'])) ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^ KeyError: 'runs'
`
