### ISSUE TITLE
Playlists no longer loading

### ISSUE THREAD

**Issue by XalaTheShepard** [KoljaWindeler/ytube_music_player#224]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
A clear and concise description of what the bug is, ideally a homeassistant log with debug enabled
After the update to HA Core 2023.1.4 (not sure if related) the playlists of the integration can no longer be loaded. I have renewed the token, but no success. The integration is able to find the media players.

**Version**
please provide the version you are using (see HACS)
2022041502

**To Reproduce**

**Additional context**

Thanks

**Comment by samhed** [comment]
The past 3 days, I have been having this issue as well. I have not upgraded to HA 2023.1 yet, I'm still at 2022.12.7.

I can't browse library playlists, library albums, library songs, library songs, uploaded albums, or uploaded artists. When trying to do this, the GUI displays a popup saying “Media Browsing Error – Unknown error”.

The only things that work are “Last played songs” and “Moods & Genres”. I can start music fine from these.

I have also refreshed my YouTube Music token using the config flow, but it didn't help.

```
2023-01-13 18:41:24.088 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
== == == == == == = ytube_music_player Integration Error == == == == == == == ==
2023-01-13 18:41:24.092 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2023-01-13 18:41:24.094 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2023-01-13 18:41:24.095 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:
2023-01-13 18:41:24.098 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in async_update_playlists
self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit))
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in <lambda>
self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit))
File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists
results = nav(results, ITEM_SECTION + GRID)
File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav
raise err
File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav
root = root[k]
TypeError: 'NoneType' object is not subscriptable
2023-01-13 18:41:24.100 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2023-01-13 18:41:24.101 ERROR (MainThread) [custom_components.ytube_music_player.media_player] == == == == == == = ytube_music_player Integration Error == == == == == == == ==
2023-01-13 18:41:24.459 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
== == == == == == = ytube_music_player Integration Error == == == == == == == ==
```

**Comment by samhed** [comment]
Yeah, same for me. I had to click ytube_music_player in HACS and then through the three-dots-menu choose "download again" to get the new version. With that it works fine.

Why doesn't HACS show the update?
