### ISSUE TITLE
Submitting because requested - dont know what this is

### ISSUE THREAD

**Issue by edfarr** [KoljaWindeler/ytube_music_player#226]
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in async_play_media playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in <lambda> playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/playlists.py", line 107, in get_playlist playlist = {'id': results['playlistId']} KeyError: 'playlistId'
thanks, Kolja
== == == == == == = ytube_music_player Integration Error == == == == == == == ==

**Comment by khmikkelsen** [comment]
Getting the same error, sometimes it will play, sometimes it wont.

**Comment by KoljaWindeler** [comment]
Hi, this is a very old ticket .. i didn't really work on this integration for some time and some ticket are very old. Please excuse that I didn't respond. I'll close this ticket as the integration recently received some love and I expect that this will fix a lot of issues. Please reopen if this problem still exists
