### ISSUE TITLE
 library playlists or library albums - unknown error

### ISSUE THREAD

**Issue by Yonny24** [KoljaWindeler/ytube_music_player#227]
I've been seeing this issue for a couple of weeks now - cannot open  library playlists or library albums - unknown error.
under the media library tab

![image](https://user-images.githubusercontent.com/64428686/215136997-969d2443-6176-4638-82af-a7a4bf7af77f.png)

I refreshed the cookie token everything else works - on the latest version of hacs and homeassistant.

Any ideas?

Many thanks

**Comment by KoljaWindeler** [comment]
Hi, not at all. I've just setup another player .. everything still working .. really no idea. I'd say it is a cookie issue

**Comment by Yonny24** [comment]
Thanks for the reply. I did try a new cookie - I'll keep trying with new ones. I had seen this about a year ago but resolved itself luckily.

**Comment by ngalatis** [comment]
I have the same exact issue for a couple of weeks as well

**Comment by WarC0zes** [comment]
Hello,
same problem, no access to the playlist for a few weeks.
I redid the cookies with chrome in a private browser and that didn't fix my problem.
I have this error in the logs.

```
.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2023-01-28 12:33:06.768 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:
2023-01-28 12:33:06.772 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in async_update_playlists
self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit))
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in <lambda>
self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit))
File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists
results = nav(results, ITEM_SECTION + GRID)
File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav
raise err
File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav
root = root[k]
TypeError: 'NoneType' object is not subscriptable
2023-01-28 12:33:06.774 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2023-01-28 12:33:06.776 ERROR (MainThread) [custom_components.ytube_music_player.media_player] == == == == == == = ytube_music_player Integration Error == == == == == == == ==
```

**Comment by rillekille** [comment]
Hi,

I'm getting the same error for a while:

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in async_update_playlists self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in <lambda> self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists results = nav(results, ITEM_SECTION + GRID) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav raise err File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav root = root[k] **TypeError: 'NoneType' object is not subscriptable**
thanks, Kolja
== == == == == == = ytube_music_player Integration Error == == == == == == == ==

My automation that starts playing "My Liked Songs" playlist in the morning is still working so the cookie should be alright I guess.
But my Input select in the dahsboard has status "loading" and I can't see any playlists.

**Comment by aguscaba** [comment]
Same here

**Comment by jurgenweber** [comment]
```
2023-02-27 16:48:02.230 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139724087406560] Error handling message: Unknown error (unknown_error) from (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1226, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1977, in async_browse_media
    response = await build_item_response(self, payload)
  File "/config/custom_components/ytube_music_player/browse_media.py", line 67, in build_item_response
    media = await hass.async_add_executor_job(media_library.get_library_playlists, BROWSER_LIMIT)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists
    results = nav(results, ITEM_SECTION + GRID)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav
    raise err
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav
    root = root[k]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jurgenweber** [comment]
give this solution a try; https://github.com/KoljaWindeler/ytube_music_player/issues/228#issuecomment-1458922568

Basically go to the integration and download the 'main' version, restart and try again.

**Comment by WarC0zes** [comment]
> give this solution a try; [#228 (comment)](https://github.com/KoljaWindeler/ytube_music_player/issues/228#issuecomment-1458922568)
> 
> Basically go to the integration and download the 'main' version, restart and try again.

Hi,
it worked for me, thanks for your solution.

**Comment by Yonny24** [comment]
Thanks fixed by using main
