### ISSUE TITLE
There is no playlist entity_id in your configuration or this entity_id does not exist in homeassistant. I don't know what to play, so I'll go. Use a media browser or add a dropdown playlist

### ISSUE THREAD

**Issue by znack14** [KoljaWindeler/ytube_music_player#231]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/browse_media.py:67
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 01:09:43 (2 occurrences)
Last logged: 01:13:28

[1732562416] Error handling message: Unknown error (unknown_error) znachok from 192.168.1.242 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1223, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1979, in async_browse_media
    response = await build_item_response(self, payload)
  File "/config/custom_components/ytube_music_player/browse_media.py", line 67, in build_item_response
    media = await hass.async_add_executor_job(media_library.get_library_playlists, BROWSER_LIMIT)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 27, in get_library_playlists
    response = self._send_request(endpoint, body)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/ytmusic.py", line 134, in _send_request
    response = self._session.post(YTM_BASE_API + endpoint + YTM_PARAMS + additionalParams,
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1323, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/usr/local/lib/python3.10/http/client.py", line 1247, in putheader
    header = header.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-11: ordinal not in range(128)

**Version**
2023.3.5

**To Reproduce**

**Additional context**
Doesn't work at all. Either choice leads to an unknown error. Logged in from two accounts, everything is the same

Thanks

**Comment by SiboutVanLoo** [comment]
I got this, errors started after updating to 2023.3 version.
Log:

2023-03-18 21:32:35.105 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547995655840] Error handling message: Unknown error (unknown_error) Sibout from 192.168.86.30 (Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1223, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1979, in async_browse_media
    response = await build_item_response(self, payload)
  File "/config/custom_components/ytube_music_player/browse_media.py", line 67, in build_item_response
    media = await hass.async_add_executor_job(media_library.get_library_playlists, BROWSER_LIMIT)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 27, in get_library_playlists
    response = self._send_request(endpoint, body)
  File "/usr/local/lib/python3.10/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 401: Unauthorized.
You must be signed in to perform this operation.
2023-03-18 21:32:36.865 WARNING (SyncWorker_16) [homeassistant.components.google_wifi.sensor] Unable to fetch data from Google Wifi
2023-03-18 21:32:39.594 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547995655840] Error handling message: Unknown error (unknown_error) Sibout from 192.168.86.30 (Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1223, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1979, in async_browse_media
    response = await build_item_response(self, payload)
  File "/config/custom_components/ytube_music_player/browse_media.py", line 555, in build_item_response
    response.calculate_children_class()
  File "/usr/src/homeassistant/homeassistant/components/media_player/browse_media.py", line 153, in calculate_children_class
    proposed_class = self.children[0].media_class
IndexError: list index out of range

**Comment by Yonny24** [comment]
Are you referring to the Library Playlists under Media? Mine hasn't worked for months now. Even with a new token cookie applied.

**Comment by KoljaWindeler** [comment]
hi, is this fixed with the oAuth release? please reopen if this is not fixed, thanks
