### ISSUE TITLE
Paste from HA error

### ISSUE THREAD

**Issue by whotookmylogin** [KoljaWindeler/ytube_music_player#232]
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in async_update_playlists self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in <lambda> self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists results = nav(results, ITEM_SECTION + GRID) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav raise err File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav root = root[k] TypeError: 'NoneType' object is not subscriptable

**Comment by jes1417** [comment]
Same issues here I think

```
This error originated from a custom integration.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:336
Integration: yTubeMediaPlayer (documentation, issues)
First occurred: 3:24:04 PM (7 occurrences)
Last logged: 3:24:04 PM

https://github.com/KoljaWindeler/ytube_music_player/issues
and paste the following output:
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in async_update_playlists self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in <lambda> self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/library.py", line 31, in get_library_playlists results = nav(results, ITEM_SECTION + GRID) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 155, in nav raise err File "/usr/local/lib/python3.10/site-packages/ytmusicapi/parsers/utils.py", line 149, in nav root = root[k] TypeError: 'NoneType' object is not subscriptable
thanks, Kolja
== == == == == == = ytube_music_player Integration Error == == == == == == == ==
```

**Comment by bobvmierlo** [comment]
I'm having the same error, any progress on this yet?

**Comment by KoljaWindeler** [comment]
Hi, this is a very old ticket .. i didn't really work on this integration for some time and some ticket are very old. Please excuse that I didn't respond. I'll close this ticket as the integration recently received some love and I expect that this will fix a lot of issues. Please reopen if this problem still exists
