### ISSUE TITLE
ytube_music_player Integration Error

### ISSUE THREAD

**Issue by jdpl-ratel** [KoljaWindeler/ytube_music_player#233]
**Describe the bug**
File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in async_play_media playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in <lambda> playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit)) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/mixins/playlists.py", line 104, in get_playlist response = self._send_request(endpoint, body) File "/usr/local/lib/python3.10/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request raise Exception(message + error) Exception: Server returned HTTP 404: Not Found. Requested entity was not found.

**Version**
20221106

**To Reproduce**
service: media_player.play_media
    target:
      entity_id: media_player.ytube_music_player
    data:
      media_content_id: RDGMEMVs_68jiiAq2tp9FNi2GjtQ
      media_content_type: playlist

**Comment by jurgenweber** [comment]
```
023-06-14 16:04:10.180 ERROR (MainThread) [custom_components.ytube_music_player.media_player]

 == == == == == == = ytube_music_player Integration Error == == == == == == == ==
2023-06-14 16:04:10.182 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2023-06-14 16:04:10.186 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2023-06-14 16:04:10.188 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2023-06-14 16:04:10.191 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in async_play_media
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in <lambda>
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/playlists.py", line 105, in get_playlist
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 404: Not Found.
Requested entity was not found.

2023-06-14 16:04:10.192 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2023-06-14 16:04:10.194 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == ==


2023-06-14 16:04:10.202 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall media_player.turn_off (c:01H2W8282N556D32P8ZV79C3K5): entity_id=['media_player.office_vlc_speaker']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1928, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 788, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity media_player.office_vlc_speaker does not support this service.
```

yeah! I started getting this error recently also!

**Comment by jurgenweber** [comment]
after a bit of playing around, I updated my cookie.. you need to do this from time to time and it works again.

**Comment by KoljaWindeler** [comment]
Hi, this is a very old ticket .. i didn't really work on this integration for some time and some ticket are very old. Please excuse that I didn't respond. I'll close this ticket as the integration recently received some love and I expect that this will fix a lot of issues. Please reopen if this problem still exists
