### ISSUE TITLE
Playback failed on Chromecast speaker group

### ISSUE THREAD

**Issue by benblb** [KoljaWindeler/ytube_music_player#242]
**Enable DEBUG Output**
2023-04-17 16:31:25.694 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2023-04-17 16:31:25.695 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2023-04-17 16:31:25.696 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2023-04-17 16:31:25.697 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:
2023-04-17 16:31:25.700 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in async_play_media
  File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in <lambda>
2023-04-17 16:31:25.701 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
2023-04-17 16:31:25.702 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == == 

-----

2023-04-17 21:55:48.156 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2023-04-17 21:55:48.158 ERROR (MainThread) [custom_components.ytube_music_player.media_player] HTTP Error 410: Gone
2023-04-17 21:55:48.160 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Retry with: (3)
2023-04-17 21:55:48.162 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.ytube_music_player, old_state=<state media_player.ytube_music_player=playing; volume_level=0.43, is_volume_muted=False, media_content_type=music, media_title=Shlohmo - wen uuu, media_artist=StollenGrappa, media_album_name=, shuffle=True, repeat=all, entity_picture_local=/api/media_player_proxy/media_player.ytube_music_player?token=6ac796fbe455b990cb26c4478eeb03bdfb98b25b858ee2072f590dcbca898e5e&cache=880a65fc5ddacd15, remote_player_state=off, likeStatus=INDIFFERENT, current_playlist_title=Downtempo Hotel Lobby, videoId=fBhl8KZM8Jg, _media_type=playlist, _media_id=PL1Om732i_8SDgdfdRFzHGqOxMsmUDV3aZ, current_track=0, remote_player_id=media_player.nests, entity_picture=https://i.ytimg.com/vi/fBhl8KZM8Jg/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3kc0bUpZdrzLflgPTOhzBkIiHfFvA, icon=mdi:music-circle, friendly_name=ytube_music_player, supported_features=450495 @ 2023-04-17T21:55:44.649321-07:00>, new_state=<state media_player.ytube_music_player=playing; volume_level=0.43, is_volume_muted=False, media_content_type=music, media_title=Wildes - Illuminate, media_artist=MrSuicideSheep, media_album_name=, shuffle=True, repeat=all, entity_picture_local=/api/media_player_proxy/media_player.ytube_music_player?token=6ac796fbe455b990cb26c4478eeb03bdfb98b25b858ee2072f590dcbca898e5e&cache=96b530cef7d1b6e0, remote_player_state=off, likeStatus=INDIFFERENT, current_playlist_title=Downtempo Hotel Lobby, videoId=QBPwm9HthKw, _media_type=playlist, _media_id=PL1Om732i_8SDgdfdRFzHGqOxMsmUDV3aZ, current_track=1, remote_player_id=media_player.nests, entity_picture=https://i.ytimg.com/vi/QBPwm9HthKw/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3kZYtD4-JDp4HuwgNHIOo7SK0lm9g, icon=mdi:music-circle, friendly_name=ytube_music_player, supported_features=450495 @ 2023-04-17T21:55:44.649321-07:00>>
2023-04-17 21:55:51.618 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2023-04-17 21:55:51.620 ERROR (MainThread) [custom_components.ytube_music_player.media_player] HTTP Error 410: Gone
2023-04-17 21:55:51.622 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Retry with: (2)
2023-04-17 21:55:51.624 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.ytube_music_player, old_state=<state media_player.ytube_music_player=playing; volume_level=0.43, is_volume_muted=False, media_content_type=music, media_title=Wildes - Illuminate, media_artist=MrSuicideSheep, media_album_name=, shuffle=True, repeat=all, entity_picture_local=/api/media_player_proxy/media_player.ytube_music_player?token=6ac796fbe455b990cb26c4478eeb03bdfb98b25b858ee2072f590dcbca898e5e&cache=96b530cef7d1b6e0, remote_player_state=off, likeStatus=INDIFFERENT, current_playlist_title=Downtempo Hotel Lobby, videoId=QBPwm9HthKw, _media_type=playlist, _media_id=PL1Om732i_8SDgdfdRFzHGqOxMsmUDV3aZ, current_track=1, remote_player_id=media_player.nests, entity_picture=https://i.ytimg.com/vi/QBPwm9HthKw/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3kZYtD4-JDp4HuwgNHIOo7SK0lm9g, icon=mdi:music-circle, friendly_name=ytube_music_player, supported_features=450495 @ 2023-04-17T21:55:44.649321-07:00>, new_state=<state media_player.ytube_music_player=playing; volume_level=0.43, is_volume_muted=False, media_content_type=music, media_title=Evenings - Babe, media_artist=Alpha Pup, media_album_name=, shuffle=True, repeat=all, entity_picture_local=/api/media_player_proxy/media_player.ytube_music_player?token=6ac796fbe455b990cb26c4478eeb03bdfb98b25b858ee2072f590dcbca898e5e&cache=3ed8670712c5a769, remote_player_state=off, likeStatus=INDIFFERENT, current_playlist_title=Downtempo Hotel Lobby, videoId=Eq9xejb2mSM, _media_type=playlist, _media_id=PL1Om732i_8SDgdfdRFzHGqOxMsmUDV3aZ, current_track=2, remote_player_id=media_player.nests, entity_picture=https://i.ytimg.com/vi/Eq9xejb2mSM/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3nR7afk0VAR84dT1j7VYLQjcTyObQ, icon=mdi:music-circle, friendly_name=ytube_music_player, supported_features=450495 @ 2023-04-17T21:55:44.649321-07:00>>
2023-04-17 21:55:53.646 DEBUG (MainThread) [homeassistant.core] Service did not complete before timeout: <ServiceCall media_player.play_media (c:01GY9BFYRW51G8MFRGXWASFDV5): entity_id=['media_player.ytube_music_player'], extra=, media_type=playlist, media_id=PL1Om732i_8SDgdfdRFzHGqOxMsmUDV3aZ>
2023-04-17 21:55:54.416 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2023-04-17 21:55:54.418 ERROR (MainThread) [custom_components.ytube_music_player.media_player] HTTP Error 410: Gone
2023-04-17 21:55:54.420 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Retry with: (1)
2023-04-17 21:55:54.421 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=media_player.ytube_music_player, old_state=<state media_player.ytube_music_player=playing; volume_level=0.43, is_volume_muted=False, media_content_type=music, media_title=Evenings - Babe, media_artist=Alpha Pup, media_album_name=, shuffle=True, repeat=all, entity_picture_local=/api/media_player_proxy/media_player.ytube_music_player?token=6ac796fbe455b990cb26c4478eeb03bdfb98b25b858ee2072f590dcbca898e5e&cache=3ed8670712c5a769, remote_player_state=off, likeStatus=INDIFFERENT, current_playlist_title=Downtempo Hotel Lobby, videoId=Eq9xejb2mSM, _media_type=playlist, _media_id=PL1Om732i_8SDgdfdRFzHGqOxMsmUDV3aZ, current_track=2, remote_player_id=media_player.nests, entity_picture=https://i.ytimg.com/vi/Eq9xejb2mSM/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3nR7afk0VAR84dT1j7VYLQjcTyObQ, icon=mdi:music-circle, friendly_name=ytube_music_player, supported_features=450495 @ 2023-04-17T21:55:44.649321-07:00>, new_state=<state media_player.ytube_music_player=playing; volume_level=0.43, is_volume_muted=False, media_content_type=music, media_title=Imagined Herbal Flows - Autumn Leaves, media_artist=Dealer de Musique, media_album_name=, shuffle=True, repeat=all, entity_picture_local=/api/media_player_proxy/media_player.ytube_music_player?token=6ac796fbe455b990cb26c4478eeb03bdfb98b25b858ee2072f590dcbca898e5e&cache=e86d7bae579fa331, remote_player_state=off, likeStatus=INDIFFERENT, current_playlist_title=Downtempo Hotel Lobby, videoId=xYcOdz-s-sA, _media_type=playlist, _media_id=PL1Om732i_8SDgdfdRFzHGqOxMsmUDV3aZ, current_track=3, remote_player_id=media_player.nests, entity_picture=https://i.ytimg.com/vi/xYcOdz-s-sA/sddefault.jpg?sqp=-oaymwEWCJADEOEBIAQqCghqEJQEGHgg6AJIWg&rs=AMzJL3lOwGTemfLi_FdVDKPcR9ZCYbs0LA, icon=mdi:music-circle, friendly_name=ytube_music_player, supported_features=450495 @ 2023-04-17T21:55:44.649321-07:00>>
2023-04-17 21:55:57.859 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2023-04-17 21:55:57.862 ERROR (MainThread) [custom_components.ytube_music_player.media_player] HTTP Error 410: Gone

**Describe the bug**
Tried to play music on a Chromecast speaker group (one Nest Mini, one Lenovo Smart Clock v2, one Chromecast Audio) and it did not work. Works if use a different speaker group where I swap the Chromecast audio for a Google Home Mini (1st gen). 

**Version**
20230321.01

**To Reproduce**
1. Attempt playback using node red, Playlist ID. 

**Additional context**
Nothing else for this, but playlists not displaying in media browser. 

Thanks!

**Comment by benblb** [comment]
After the failure, I had to delete and re-add the integration in order for the music to play on my "Nests" speaker group (the one without Chromecast Audio).

**Comment by benblb** [comment]
Related to #238 I think. I can play if Chromecast is the only speaker, but if the Chromecast is in a speaker group it does not work. May be unrelated to the Chromecast entirely, but sharing what I experience.

**Comment by KoljaWindeler** [comment]
Hi, I've just tested again. 
One group with Nest mini speakers .. works fine
Another group with Nest mini and chromcasts .. also works fine here ..

Ultimatly: This can't be fixed in this integration. As long as an media_player entity is exposed to Homeassistant it can be used. if it doesn't work then it needs to be fixed in the integration of that device and can't be fixed here. Sorry.
