### ISSUE TITLE
unable to play music

### ISSUE THREAD

**Issue by jurgenweber** [KoljaWindeler/ytube_music_player#253]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
unable to play music

**Version**
20230321.01

**To Reproduce**
```
2023-07-19 13:29:33.297 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140376120406096] get_transform_object: could not find match for var for={(.*?)};
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 1465, in async_play_media
    if(not(await self.async_prepare_play())):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 588, in async_prepare_play
    await self.async_get_cipher('BB2mjBuAtiQ')
  File "/config/custom_components/ytube_music_player/media_player.py", line 706, in async_get_cipher
    self._cipher = pytube.cipher.Cipher(js=self._js)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 51, in patched__init__
    self.transform_map = pytube.cipher.get_transform_map(js, var)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 218, in get_transform_map
    transform_object = get_transform_object(js, var)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/cipher.py", line 200, in get_transform_object
    raise RegexMatchError(caller="get_transform_object", pattern=pattern)
pytube.exceptions.RegexMatchError: get_transform_object: could not find match for var for={(.*?)};
```

**Additional context**
latest hass

Thanks

**Comment by Wireheadbe** [comment]
Same issue here.

**Comment by wisamarrakee** [comment]
Facing same issue, exactly matching DEBUG Output

**Comment by TheWanderingTurkey** [comment]
Same issue, identical debug output.

**Comment by Shawson** [comment]
Same here- I have an automation which triggers to start music for my toddlers bedtime- runs every night but as of this evening seems to complain with the exact same issue:

`get_transform_object: could not find match for var for={(.*?)};`

**Comment by jurgenweber** [comment]
Hi Guys,

I realise everyone here may not be technical or work with GH a lot. Just an FYI, if you have no further information to report but you do have the same problem. A thumbs up emoji is all we need. Try to keep the comments for further investigation/debug and information.

I know it is not my project, but some general GH etiquette. 

Thanks

**Comment by wilkshake** [comment]
Appears that the issue is in the pytube module [https://github.com/pytube/pytube/issues/1728](url)

**Comment by XalaTheShepard** [comment]
Dear all,

I hope this can be of use. 
This are the logs related to the issue: 

[139999069260752] get_transform_object: could not find match for var for={(.*?)};
12:42:35 PM – (ERROR) Home Assistant WebSocket API (custom integration) - message first occurred at 12:35:24 PM and shows up 3 times
async_get_cipher failed
12:32:41 PM – (ERROR) yTubeMediaPlayer (custom integration)
Error while setting up ytube_music_player platform for media_player
12:31:14 PM – (ERROR) Media player (custom integration)

![Error Youtube Music Player](https://github.com/KoljaWindeler/ytube_music_player/assets/69390987/56f145cd-5b95-4ce9-bbda-4d10cdbca0e5)

**Comment by Yonny24** [comment]
same here

**Comment by DravenSA** [comment]
I had the same issue, so all i did was
go to the integration
clicked the Configure
copied out the cookie text
pasted it back in
hit submit

and now my music plays again

or you could maybe just hit configure and then hit submit. 

Hope it helps someone

**Comment by jurgenweber** [comment]
Yeah, I have done nothing and it works again today. Not sure how that works.... :\

**Comment by KoljaWindeler** [comment]
Strange. But my kids also reported that it wasn't working  yesterday. When I came home and tested everything was fine ..

**Comment by Pelerin52** [comment]
It's working ok again for me this morning, I haven't changed anything
