### ISSUE TITLE
Component not working.. it goes in error every time I try to play media

### ISSUE THREAD

**Issue by StefanoGiu** [KoljaWindeler/ytube_music_player#258]
**Enable DEBUG Output**
2023-08-27 14:31:43.839 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2023-08-27 14:31:43.839 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2023-08-27 14:31:43.839 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2023-08-27 14:31:43.845 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2023-08-27 14:31:43.845 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File ".homeassistant\custom_components\ytube_music_player\media_player.py", line 1480, in async_play_media
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".homeassistant\custom_components\ytube_music_player\media_player.py", line 1480, in <lambda>
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".homeassistant\deps\Python311\site-packages\ytmusicapi\mixins\playlists.py", line 105, in get_playlist
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".homeassistant\deps\Python311\site-packages\ytmusicapi\ytmusic.py", line 144, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 404: Not Found.
Requested entity was not found.

**Describe the bug**
2023-08-27 14:31:43.839 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2023-08-27 14:31:43.839 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2023-08-27 14:31:43.839 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2023-08-27 14:31:43.845 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2023-08-27 14:31:43.845 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File ".homeassistant\custom_components\ytube_music_player\media_player.py", line 1480, in async_play_media
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".homeassistant\custom_components\ytube_music_player\media_player.py", line 1480, in <lambda>
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".homeassistant\deps\Python311\site-packages\ytmusicapi\mixins\playlists.py", line 105, in get_playlist
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".homeassistant\deps\Python311\site-packages\ytmusicapi\ytmusic.py", line 144, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 404: Not Found.
Requested entity was not found.

**Version**
20230321.01

**To Reproduce**
media_player.play_media

**Additional context**

Thanks

**Comment by Shawson** [comment]
Just started happening to me yesterday also- same debug output

**Comment by wildoracle** [comment]
Yes, I have had to do this almost every day - go to yt music, press F12, grab that token text, paste it into the field, and submit. It's almost like having my morning coffee at this point. Sure would be nice to have it fixed. :(

**Comment by KoljaWindeler** [comment]
Hi, I guess this is fixed with the oAuth method, right? Please reopen if this still appears
