### ISSUE TITLE
Unable to play from playlist

### ISSUE THREAD

**Issue by eroji** [KoljaWindeler/ytube_music_player#26]
Can't seem to get the player to work after I redid my playlists on Youtube Music. Now it just errors when I try to cast to my speaker group.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/media_player.py:691
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 1:14:16 AM (1 occurrences)
Last logged: 1:14:16 AM

[548279126960] object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 748, in async_toggle
    await self.async_turn_on()
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 550, in async_turn_on
    await self.hass.async_add_executor_job(self.turn_on)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 280, in turn_on
    self._play()
  File "/config/custom_components/ytube_music_player/media_player.py", line 680, in _play
    self._get_track()
  File "/config/custom_components/ytube_music_player/media_player.py", line 691, in _get_track
    _LOGGER.debug("Playing track nr "+str(self._next_track_no)+" / "+str(len(self._tracks)))
TypeError: object of type 'NoneType' has no len()
```

**Comment by KoljaWindeler** [comment]
Hmm could in detail what you've done

**Comment by eroji** [comment]
I added the repo in HACS, installed the latest beta, restarted HA and added the integration. I tried to follow the instructions to retrieve the cookies but could not find any instance in dev tool for /browse. I did look through the various requests and found one that the integration took the cookie input for. Then I added the following block into my configuration.yaml. Restarted HA once again. I'm using `mini-media-player` and when I power on the player in Lovelace, I can hear the chime on the speaker group, but the song/playlist fails to load and the above error is logged.

```
media_player:
  - platform: ytube_music_player
    name: YouTube Music
    speakers:
      - all_speakers

input_select:
  ytube_music_player_source:
    name: Source
    icon: mdi:music-box-multiple
    options: # don't change
    - "Playlist Radio"
    - "Playlist"

  ytube_music_player_speakers:
    name: Speakers
    icon: mdi:speaker
    options: # don't change
    - "loading"

  ytube_music_player_playlist:
    name: Playlist
    icon: mdi:playlist-music
    options: # don't change
    - "loading"

  ytube_music_player_playmode:
    name: Playmode
    icon: mdi:playlist-music
    options: ## don't change
    - "Shuffle"
    - "Random"
    - "Shuffle Random"
    - "Direct"
    - ```

**Comment by KoljaWindeler** [comment]
I'd suggest to try the cookie grabbing process again. 
Very likely that there is something wrong. 
Try e.g. incognito mode and browse around, e.g. open the library.
I'll fix the section that caused the error

**Comment by eroji** [comment]
Re-configured the integration and fetched new cookie/token, but it's still resulting in the same exact error.

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 748, in async_toggle
    await self.async_turn_on()
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 550, in async_turn_on
    await self.hass.async_add_executor_job(self.turn_on)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 255, in turn_on
    self._play()
  File "/config/custom_components/ytube_music_player/media_player.py", line 706, in _play
    self._get_track()
  File "/config/custom_components/ytube_music_player/media_player.py", line 717, in _get_track
    _LOGGER.debug("Playing track nr "+str(self._next_track_no)+" / "+str(len(self._tracks)))
TypeError: object of type 'NoneType' has no len()
```

**Comment by simonmannsfeld** [comment]
@eroji Could you provide us your full configuration.yaml? I guess it could be something with your media_player.

**Comment by eroji** [comment]
This is what I have currently in the `configuration.yaml`.

```
input_select:
  ytube_music_player_source:
    name: Source
    icon: mdi:music-box-multiple
    options: # don't change
    - "Playlist Radio"
    - "Playlist"

  ytube_music_player_speakers:
    name: Speakers
    icon: mdi:speaker
    options: # don't change
    - "loading"

  ytube_music_player_playlist:
    name: Playlist
    icon: mdi:playlist-music
    options: # don't change
    - "loading"

  ytube_music_player_playmode:
    name: Playmode
    icon: mdi:playlist-music
    options: ## don't change
    - "Shuffle"
    - "Random"
    - "Shuffle Random"
    - "Direct"
```

**Comment by KoljaWindeler** [comment]
Please try the latest version. It should provide more information during the login process

**Comment by eroji** [comment]
I'm using the 12/26 version. Not sure if this helps.

```
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1118
Integration: YouTube Music Player (documentation)
First occurred: 2:32:07 AM (2 occurrences)
Last logged: 3:09:18 AM

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 596, in _update_playlists extra_info = self._api.get_playlist(playlistId=playlist['playlistId']) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 100, in get_playlist playlist['tracks'].extend(parse_playlist_items(results['contents'])) KeyError: 'contents'
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 674, in _load_playlist self._tracks = self._api.get_playlist(playlistId = self._playlists[idx]['playlistId'], limit = int(self._playlists[idx]['count']))['tracks'] File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 100, in get_playlist playlist['tracks'].extend(parse_playlist_items(results['contents'])) KeyError: 'contents'
```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/media_player.py:774
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:09:18 AM (1 occurrences)
Last logged: 3:09:18 AM

[547685567456] object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 748, in async_toggle
    await self.async_turn_on()
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 550, in async_turn_on
    await self.hass.async_add_executor_job(self.turn_on)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 254, in turn_on
    self._play()
  File "/config/custom_components/ytube_music_player/media_player.py", line 763, in _play
    self._get_track()
  File "/config/custom_components/ytube_music_player/media_player.py", line 774, in _get_track
    _LOGGER.debug("Playing track nr "+str(self._next_track_no)+" / "+str(len(self._tracks)))
TypeError: object of type 'NoneType' has no len()
```

**Comment by KoljaWindeler** [comment]
I'm really confused that you see those messages. It should either trow an error way earlier or never. 

I don't think that I can help you. I guess the best way would be to remove the integration and start over, new cookies etc.

**Comment by eroji** [comment]
I think I figured out the issue. The code seems to loop through the playlists but if the playlist is empty then it throws that stack trace error. I had removed everything out of my "Your Likes" playlist as I was re-organizing.

**Comment by KoljaWindeler** [comment]
HAH! ok .. thats for sure something that I haven't considered.
The api hits an exception for an empty playlist and the default value of _tracks is None! 
you're completely right! Thanks for tracking it down! I've change the default to an empty list.

https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20201229
