### ISSUE TITLE
KeyError 'playlistId'

### ISSUE THREAD

**Issue by khmikkelsen** [KoljaWindeler/ytube_music_player#264]
**Describe the bug**
Whenever I try to play a playlist, the same errors comes up.

**Version**
20230321.01

**To Reproduce**
1. Follow protocol from github page to play a playlist. 

**Additional context**
Whenever error comes up, I have to reinstall the addon with a new cookie. Just a new cookie does not work, it has to be reinstalled. This happens about every day/second day.

Logs:
```2023-09-26 07:31:15.340 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source(bathroom_speaker)
2023-09-26 07:31:15.343 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.bathroom_speaker/ current media_player.bathroom_speaker) 
2023-09-26 07:31:15.344 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  no change [E]
2023-09-26 07:31:15.345 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.bathroom_speaker as player
2023-09-26 07:31:15.349 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source
2023-09-26 07:31:15.352 INFO (MainThread) [homeassistant.components.automation.gtfo_bed] GTFO bed: If at step 3: Executing step call service
2023-09-26 07:31:15.355 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] play_media, media_type: playlist, media_id: RDTMAK5uy_kset8DisdE7LSD4TNjEVvrKRTmG7a56sY
2023-09-26 07:31:15.362 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_prepare_play
2023-09-26 07:31:15.363 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2023-09-26 07:31:15.367 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current media_player.bathroom_speaker)  [E]
2023-09-26 07:31:15.370 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_on_media_player [E]
2023-09-26 07:31:15.380 INFO (SyncWorker_16) [pychromecast] Starting app CC1AD845
2023-09-26 07:31:15.380 INFO (SyncWorker_16) [pychromecast.controllers] Receiver:Launching app CC1AD845
2023-09-26 07:31:15.438 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher
2023-09-26 07:31:15.441 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.bathroom_speaker: off -> idle ... not playing [E]
2023-09-26 07:31:15.578 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.bathroom_speaker: idle -> idle ... not playing [E]
2023-09-26 07:31:15.587 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.bathroom_speaker: idle -> idle ... not playing [E]
2023-09-26 07:31:17.380 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_cipher
2023-09-26 07:31:17.383 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_prepare_play
2023-09-26 07:31:18.257 ERROR (MainThread) [custom_components.ytube_music_player.media_player] get_playlist(playlistId=RDTMAK5uy_kset8DisdE7LSD4TNjEVvrKRTmG7a56sY)
2023-09-26 07:31:18.259 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2023-09-26 07:31:18.260 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2023-09-26 07:31:18.262 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2023-09-26 07:31:18.264 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2023-09-26 07:31:18.268 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in async_play_media
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in <lambda>
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/playlists.py", line 108, in get_playlist
    playlist = {'id': results['playlistId']}
                      ~~~~~~~^^^^^^^^^^^^^^
KeyError: 'playlistId'

2023-09-26 07:31:18.270 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2023-09-26 07:31:18.272 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == == ```

**Comment by KoljaWindeler** [comment]
Hi, please test again with the latest version that supports oAuth

**Comment by khmikkelsen** [comment]
Works after fresh install, but with old fix it also did. Will close if still functional in a few days.
