### ISSUE TITLE
I saw this message in the logs: == == == == == == = ytube_music_player Integration Error == == == == == == == ==

### ISSUE THREAD

**Issue by Karsak4747** [KoljaWindeler/ytube_music_player#267]
**Describe the bug**
A clear and concise description of what the bug is, ideally a homeassistant log with debug enabled

**Version**
20230321.01

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in async_update_playlists self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/ytube_music_player/media_player.py", line 1085, in <lambda> self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/library.py", line 28, in get_library_playlists response = self._send_request(endpoint, body) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request raise Exception(message + error) Exception: Server returned HTTP 401: Unauthorized. You must be signed in to perform this operation.

Thanks

**Comment by KoljaWindeler** [comment]
Please try the beta version that supports oauth now

**Comment by Karsak4747** [comment]
Thank you very much!)
