### ISSUE TITLE
Error with version 20201221

### ISSUE THREAD

**Issue by slipx06** [KoljaWindeler/ytube_music_player#27]
Hi. Just updated to the new version via HACS. (20201221) The following error shows up in the logs. I've tried to regenerate the header file but did not fix  it.

```
2020-12-21 18:35:28 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.ytube_music_player
2020-12-21 18:35:28 INFO (MainThread) [homeassistant.components.media_player] Setting up media_player.ytube_music_player
2020-12-21 18:35:28 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 3.6 seconds
2020-12-21 18:35:28 ERROR (SyncWorker_19) [custom_components.ytube_music_player.media_player]
============= ytube_music_player Integration Error ================
2020-12-21 18:35:28 ERROR (SyncWorker_19) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2020-12-21 18:35:28 ERROR (SyncWorker_19) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2020-12-21 18:35:28 ERROR (SyncWorker_19) [custom_components.ytube_music_player.media_player] and paste the following output:
2020-12-21 18:35:28 ERROR (SyncWorker_19) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 91, in __init__
self._api = ytmusicapi.YTMusic(config.get(CONF_HEADER_PATH, default_header_file))
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 96, in __init__
self.sapisid = sapisid_from_cookie(self.headers['Cookie'])
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/helpers.py", line 57, in sapisid_from_cookie
return cookie['__Secure-3PAPISID'].value
KeyError: '__Secure-3PAPISID'
2020-12-21 18:35:28 ERROR (SyncWorker_19) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2020-12-21 18:35:28 ERROR (SyncWorker_19) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================
```
Thanks

**Comment by slipx06** [comment]
It was a problem with the cookie file. Fixed it
