### ISSUE TITLE
Trying to play a playlist, but it no longer works after latest update

### ISSUE THREAD

**Issue by alanzhao** [KoljaWindeler/ytube_music_player#272]
**Enable DEBUG Output**

 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2023-11-27 09:54:21.792 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2023-11-27 09:54:21.792 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2023-11-27 09:54:21.793 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2023-11-27 09:54:21.800 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1485, in async_play_media
    self._tracks = await self.hass.async_add_executor_job(self._api.get_album, media_id)  # no limit needed
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/browsing.py", line 412, in get_album
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 156, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 400: Bad Request.
Request contains an invalid argument.

2023-11-27 09:54:21.800 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2023-11-27 09:54:21.801 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == == 

2023-11-27 09:54:45.222 ERROR (MainThread) [homeassistant.components.mobile_app.notify] Requested entity was not found. This message is generated externally to Home Assistant.

**Describe the bug**
Playlist used to play fine, I updated this morning to latest version, then it starts to break.

**Version**
20231119.01

**To Reproduce**
1. copy example from GitHub for starting an album / playlist
2. go the developer settings and trigger ytmusic
3. it should show the error in logs

**Additional context**

Thanks

**Comment by KoljaWindeler** [comment]
Also: did you reconfigure the entity (go from cookie to oauth)? I should work without it .. just curious

**Comment by alanzhao** [comment]
I did reconfigure it by deleting the current config, and re-authed via oauth.

**Comment by alanzhao** [comment]
![Screen Shot 2023-11-27 at 10 58 48 AM](https://github.com/KoljaWindeler/ytube_music_player/assets/1134506/afa55184-fd14-408f-a188-4d0a70d0e8ed)

Music assistant media browser works fine, same account.

**Comment by alanzhao** [comment]
```service: media_player.play_media
data:
  media_content_id: OLAK5uy_ly3CWdPmC4nqLRkABtEm8jTbgx7cQKvco
  media_content_type: album
target:
  entity_id: media_player.ytube_music_player
  ```
  
  ^ payload to service api which used to work.

**Comment by KoljaWindeler** [comment]
Looks alright to me. I'll see what's different

**Comment by KoljaWindeler** [comment]
Thanks .. https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20231128.01
To be honest .. this is just me having bad code management .. I didn't pull the updated line into my development machine as I haven't done anything on the code for almost a year (didn't have to). When moving to oAuth I must have overwrote those lines.

I've reverted the commit. thanks for your support

**Comment by alanzhao** [comment]
np, thank you for the add-on and all the hard work, much appreciated.
