### ISSUE TITLE
Not able to play music on Google Home Mini

### ISSUE THREAD

**Issue by simontribus** [KoljaWindeler/ytube_music_player#273]
When i want to start playing music, i get the connection sound from my Google Home Mini but then nothin happens.

**Version**
20231128.01

**To Reproduce**
1. Browse Media
2. Library Playlists
3. Click play on "Liked Music"
4. Nothing happens

Debug Log:

2023-11-30 15:20:14.825 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in async_play_media
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in <lambda>
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/playlists.py", line 109, in get_playlist
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 156, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 404: Not Found.
Requested entity was not found.

2023-11-30 15:20:14.825 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

Thanks

**Comment by KoljaWindeler** [comment]
Hi have you reconfigure the player after the update? 
Reconfigure= ran the setup of oauth ... It should work without it .. but who knows ;)

**Comment by simontribus** [comment]
Yes I did, I also completely removed and reinstalled it. Same error.
OAuth worked great btw! :)

**Comment by KoljaWindeler** [comment]
Hmm .. is this only happening on that playlist or on all? 
Can you tried on another device? It works here so debugging is tricky

**Comment by simontribus** [comment]
I tried another device and stil nothing, but: When i tried it a fre times, one time in the UI it showed some tracks playing but kept changeing them.

Here are the logs:

== == == == == == = ytube_music_player Integration Error == == == == == == == ==
2023-11-30 18:17:10.376 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2023-11-30 18:17:10.376 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2023-11-30 18:17:10.376 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:
2023-11-30 18:17:10.378 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in async_play_media
playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ytube_music_player/media_player.py", line 1480, in <lambda>
playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/ytmusicapi/mixins/playlists.py", line 109, in get_playlist
response = self._send_request(endpoint, body)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/ytmusicapi/ytmusic.py", line 156, in _send_request
raise Exception(message + error)
Exception: Server returned HTTP 404: Not Found.
Requested entity was not found.
2023-11-30 18:17:10.378 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2023-11-30 18:17:10.378 ERROR (MainThread) [custom_components.ytube_music_player.media_player] == == == == == == = ytube_music_player Integration Error == == == == == == == ==
2023-11-30 18:17:24.432 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2023-11-30 18:17:24.433 ERROR (MainThread) [custom_components.ytube_music_player.media_player] HTTP Error 410: Gone
2023-11-30 18:17:24.434 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Retry with: (3)
2023-11-30 18:17:28.035 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2023-11-30 18:17:28.035 ERROR (MainThread) [custom_components.ytube_music_player.media_player] HTTP Error 410: Gone
2023-11-30 18:17:28.038 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Retry with: (2)
2023-11-30 18:17:31.970 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2023-11-30 18:17:31.971 ERROR (MainThread) [custom_components.ytube_music_player.media_player] HTTP Error 410: Gone
2023-11-30 18:17:31.973 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Retry with: (1)
2023-11-30 18:17:35.267 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2023-11-30 18:17:35.268 ERROR (MainThread) [custom_components.ytube_music_player.media_player] HTTP Error 410: Gone

**Comment by simontribus** [comment]
It is working now, without me changing anything. I didn't even restarted HA, so I assume somethinge other than the integration was faulty.

**Comment by KoljaWindeler** [comment]
YouTube is sometimes acting up ;)
