### ISSUE TITLE
When can_expand and can_play are true, song is not playable

### ISSUE THREAD

**Issue by pathofleastresistor** [KoljaWindeler/ytube_music_player#278]
**Describe the bug**
Some search results are not playable. Specifically those that have `can_expand` and `can_play` as `true`.

**Version**
20231128.01

**To Reproduce**
1. Perform a search service call
2. Find a result where `can_expand` and `can_play` are both true
3. Try to play that result

**Additional context**
```
 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2023-12-22 23:26:31.280 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2023-12-22 23:26:31.280 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2023-12-22 23:26:31.281 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2023-12-22 23:26:31.284 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1487, in async_play_media
    self._tracks = await self.hass.async_add_executor_job(self._api.get_album, media_id)  # no limit needed
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/lsiopy/lib/python3.11/site-packages/ytmusicapi/mixins/browsing.py", line 413, in get_album
    album = parse_album_header(response)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/lsiopy/lib/python3.11/site-packages/ytmusicapi/parsers/albums.py", line 7, in parse_album_header
    header = nav(response, HEADER_DETAIL)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/lsiopy/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 82, in nav
    raise err
  File "/config/lsiopy/lib/python3.11/site-packages/ytmusicapi/navigation.py", line 76, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'header'

2023-12-22 23:26:31.284 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2023-12-22 23:26:31.284 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == == 

```

Thanks

**Comment by pathofleastresistor** [comment]
I played around with the ytmusicapi and found something. If I search for "Best Christmas Songs Playlist 2024", I'll get a result for a Podcast with a browseid `MPSPPLC5ODwG_SFu3xQdn3Rp4HZmfyIFSBfzVe`.

I'm not sure this component supports Podcasts yet, so I would suggest filtering these out until it does.

**Comment by pathofleastresistor** [comment]
For now I'm just filtering to "songs" to avoid complications

**Comment by pathofleastresistor** [comment]
I believe this is partially fixed with https://github.com/KoljaWindeler/ytube_music_player/pull/282

**Comment by pathofleastresistor** [comment]
With the new release, I'm okay to close this out and open a new issue if I find new cases.

**Comment by KoljaWindeler** [comment]
Morning, ytmusicapi 1.4 was released the other day. It shall support podcasts. I'll update and see what I get.
