### ISSUE TITLE
When searching for an artist, no results are returned

### ISSUE THREAD

**Issue by pathofleastresistor** [KoljaWindeler/ytube_music_player#279]
**Describe the bug**
When searching for an artist, no results are returned.

**Version**
20231128.01

**To Reproduce**
1. Make a search service call where the query is an artist name (i.e. Mariah Carey). Do not set the filter value.
2. Go to search results in media browser
3. See "unknown error"
4. See error in logs

**Additional context**
```
2023-12-22 23:30:30.595 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140438861172416] Error handling message: Unknown error (unknown_error) Amit from 192.168.50.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/media_player/__init__.py", line 1233, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 1979, in async_browse_media
    response = await build_item_response(self, payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/browse_media.py", line 392, in build_item_response
    title = helper.get(a['resultType'], "") + a['artist'], # noqa: E251
                                              ~^^^^^^^^^^
KeyError: 'artist'
```

Thanks

**Comment by pathofleastresistor** [comment]
https://github.com/KoljaWindeler/ytube_music_player/pull/282

**Comment by KoljaWindeler** [comment]
So this one is fixed by merge 282 right?

**Comment by pathofleastresistor** [comment]
Yeah - it should be but I don't have an exhaustive list of categories to test against. But I'm happy to make another pull request if I find more.
