### ISSUE TITLE
_Unknown error occurred_ when setting up the integration

### ISSUE THREAD

**Issue by felipecrs** [KoljaWindeler/ytube_music_player#327]
**Enable DEBUG Output**
Probably not needed, but let me know otherwise.

**Describe the bug**
I tried to setup the integation, this error happened after setting up the device with my Google account and pressing Submit.

**Version**
20240420.01

**To Reproduce**
I just tried to setup the integration:

![image](https://github.com/KoljaWindeler/ytube_music_player/assets/29582865/1c16dd42-efa4-474e-bda6-bc125fd9a18c)

**Additional context**

```
Registrador: aiohttp.server
Fonte: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
Ocorreu pela primeira vez: 11:39:49 (1 ocorrências)
Último registro: 11:39:49

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 88, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 71, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 356, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 402, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 506, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/config_flow.py", line 68, in async_step_oauth
    return self.async_show_form(step_id="finish", data_schema=vol.Schema(await async_create_form(self.hass,user_input,2)), errors=self._errors)
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/config_flow.py", line 198, in async_create_form
    for _ytm_player in hass.data[DOMAIN].values():
                       ~~~~~~~~~^^^^^^^^
KeyError: 'ytube_music_player'
```

**Comment by felipecrs** [comment]
Same error regardless of the entity name.

**Comment by KoljaWindeler** [comment]
Damn, yes you're right. I guess that happens if you never had a tube player before.
I'm currently not at home but can fix it tonight. @mang1985 do you have the time to fix it? @felipecrs if you feel capable just comment out the three line for the moment https://github.com/KoljaWindeler/ytube_music_player/blob/89a02e230b105bee093434da526e87170eb6c97d/custom_components/ytube_music_player/config_flow.py#L198

**Comment by felipecrs** [comment]
@KoljaWindeler thanks for the response. But no rush at all. Take your time. Meanwhile I'll try commenting out these lines locally.

**Comment by felipecrs** [comment]
It worked btw.

**Comment by mang1985** [comment]
I'm sorry for any inconvenience caused. I will now address this issue, but everyone will need to wait for Kolja to release the new version before we can use it. @KoljaWindeler  @felipecrs

**Comment by KoljaWindeler** [comment]
Thanks for fixing! New version isnreleased

**Comment by felipecrs** [comment]
It's no inconvenience at all. Thanks for the great integration!
