### ISSUE TITLE
music stopped working , 400 bad request

### ISSUE THREAD

**Issue by jurgenweber** [KoljaWindeler/ytube_music_player#367]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
I try to play music and

```
2024-11-12 07:10:58.560 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == ==


2024-11-12 07:10:58.572 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall media_player.turn_off (c:01JCEDKNMC4XNBSGZ81F48XCPD): entity_id=['media_player.office_vlc_speaker']>
Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1625, in async_play_media
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 1625, in <lambda>
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ytmusicapi/mixins/playlists.py", line 108, in get_playlist
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ytmusicapi/ytmusic.py", line 242, in _send_request
    raise YTMusicServerError(message + error)
ytmusicapi.exceptions.YTMusicServerError: Server returned HTTP 400: Bad Request.
Request contains an invalid argument.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 989, in entity_service_call
    raise HomeAssistantError(
```

**Version**
latest

**To Reproduce**
attempt to play some music

**Additional context**
I have tried removing and readding the integration and resetting auth

Thanks

**Comment by plonkis** [comment]
Same for me, i also did a total reinstall+cleanup of the integration and same error.
Running latest version.

**Comment by BBCorrales** [comment]
Update my HA supervisor to 2024.11.2 and my YouTube Music Player just shows Unknown Error

**Comment by jurgenweber** [comment]
Yeah, so the MusicAssistant discord server has some interesting updates and information

> Latest update: Seems Google is removing OAuth support from YT Music. I will have to re-implement cookie authentication again. I know it's cumbersome, but seems to be the only way forward to keep YT Music alive

**Comment by ParksideParade** [comment]
Po

> Yeah, so the MusicAssistant discord server has some interesting updates and information
> 
> > Latest update: Seems Google is removing OAuth support from YT Music. I will have to re-implement cookie authentication again. I know it's cumbersome, but seems to be the only way forward to keep YT Music alive

https://github.com/music-assistant/hass-music-assistant/issues/3138

**Comment by mwillems12** [comment]
Same for me. When I play music I get I think the same error. I have YT premium. I did try to fix with reinstall and re-authenticated ytube_music_player), and after it stopped working I also manually installed the pytubefix. Non helped.

My errors (I think mostly the same, but maybe useful):

2024-11-14 16:49:13.035 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

 == == == == == == = ytube_music_player Integration Error == == == == == == == == 
2024-11-14 16:49:13.035 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at
2024-11-14 16:49:13.035 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues
2024-11-14 16:49:13.035 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2024-11-14 16:49:13.037 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1625, in async_play_media
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 1625, in <lambda>
    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ytmusicapi/mixins/playlists.py", line 108, in get_playlist
    response = self._send_request(endpoint, body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ytmusicapi/ytmusic.py", line 242, in _send_request
    raise YTMusicServerError(message + error)
ytmusicapi.exceptions.YTMusicServerError: Server returned HTTP 400: Bad Request.
Request contains an invalid argument.

2024-11-14 16:49:13.037 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2024-11-14 16:49:13.038 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == == 


2024-11-14 16:49:13.063 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall media_player.media_stop (c:01JCNNTH6EDH4KJVCPPHKKNG6Z): entity_id=['media_player.vssl_pool_google']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 100, in wrapper
    return_value = func(self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 570, in media_stop
    media_controller.stop()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/media.py", line 642, in stop
    response_handler.wait_response()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/response_handler.py", line 57, in wait_response
    raise RequestFailed(self._request)
pychromecast.error.RequestFailed: Failed to execute stop.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 843, in async_media_stop
    await self.hass.async_add_executor_job(self.media_stop)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 102, in wrapper
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: CastMediaPlayerEntity.media_stop Failed: Failed to execute stop.
2024-11-14 16:49:13.065 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall media_player.media_pause (c:01JCNNTH6ZAD96527PTE86YENF): entity_id=['media_player.vssl_pool_google']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 100, in wrapper
    return_value = func(self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 564, in media_pause
    media_controller.pause()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/media.py", line 636, in pause
    response_handler.wait_response()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/response_handler.py", line 57, in wait_response
    raise RequestFailed(self._request)
pychromecast.error.RequestFailed: Failed to execute pause.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 835, in async_media_pause
    await self.hass.async_add_executor_job(self.media_pause)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 102, in wrapper
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: CastMediaPlayerEntity.media_pause Failed: Failed to execute pause.

**Comment by KoljaWindeler** [comment]
This is an YouTube change. 
I'm linking it to the issue at ytmusicapi
https://github.com/sigma67/ytmusicapi/issues/676

**Comment by jurgenweber** [comment]
So, all of these issues following this problem are reverting back to the old token authentication, can we do that with this integration? OR is there a way to use it?

**Comment by plonkis** [comment]
the old token login style works in latest MA version.

**Comment by catalinberta** [comment]
Thanks for the insight @jurgenweber, then I assume the solution is for ytube_music_player to either revert back to that old cookie authentication method or at least offer it as an option. 

I'm personally really looking forward to this update as I have some automations that depend on it #nopressure :)

**Comment by andiukas** [comment]
With last version:
![image](https://github.com/user-attachments/assets/3220398a-854b-43e7-947d-4f6f6df9530f)

**Comment by KoljaWindeler** [comment]
yes, I agree .. I was hoping that ytubemusicapi would find a way to fix the issue but currently it doesn't look like it. 
I'll have some time this evening to checkout the code that is needed to re-add the cookie method .. I'm really no fan but it looks like to only way to go forward. :|

**Comment by DravenSA** [comment]
Any news on a fix for this? Music Assistant was so bad in Beta, I really dont want to go back to it..

**Comment by KoljaWindeler** [comment]
guys, please test the new version .. i hesitated a lot and didn't want to go back to the cookie method, but it looks like there is no other way. I'm afraid that we'll also return to 10 bug ticket / week due to the complicated cookie process .. but hey .. if it's what it takes .. lets give it a shot ..

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20241125.01

**Comment by chofstaetter** [comment]
Thank you very much, your wonderful integration is working for me again.

**Comment by KoljaWindeler** [comment]
Cookie Guide 
https://ytmusicapi.readthedocs.io/en/stable/setup/browser.html

**Comment by Yorin1** [comment]
To set up your project, open a console and call:
ytmusicapi browser

I am probably going to look very stupid asking this, but what is a console and how do I open it?

**Comment by ParksideParade** [comment]
Confirming the cookie method is working for me!

To clarify the instructions:

1. Update to the latest ytube_music_player in Home Assistant - should happen automatically or force by going into HACS and Update Info

2. Follow the instructions on the page below to copy the authentication headers. You only need to follow the portion of that page under "Copy authentication headers", ignore the rest.
https://ytmusicapi.readthedocs.io/en/stable/setup/browser.html

3. On the Integration page for ytube_music_player, click Configure and then paste in the authentication headers

**Comment by KoljaWindeler** [comment]
Thanks, I've re-added the instructions also to the readme https://github.com/KoljaWindeler/ytube_music_player/blob/main/README.md#setup

**Comment by Taomyn** [comment]
> Thanks, I've re-added the instructions also to the readme https://github.com/KoljaWindeler/ytube_music_player/blob/main/README.md#setup

FYI, not sure if anyone else has the same issue

![image](https://github.com/user-attachments/assets/3f3a8c89-e4fc-446c-b547-76fded068908)

**Comment by catalinberta** [comment]
@KoljaWindeler It is working and thank you so much for fixing this and coping with YT's ever changing auth.

Gotta say, I almost burst into excitment to have some of my music automations working again, please consider adding the donate feature to your repo/github account as I'm sure your work will be supported, I for one want to.

Thanks!
