### ISSUE TITLE
Returning to the cookie file method didn't help.

### ISSUE THREAD

**Issue by booa1986** [KoljaWindeler/ytube_music_player#371]
Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 1136, in async_update_playlists self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/ytube_music_player/media_player.py", line 1136, in <lambda> self._playlists = await self.hass.async_add_executor_job(lambda: self._api.get_library_playlists(limit=self._trackLimit)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/ytmusicapi/mixins/library.py", line 33, in get_library_playlists response = self._send_request(endpoint, body) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/ytmusicapi/ytmusic.py", line 242, in _send_request raise YTMusicServerError(message + error) ytmusicapi.exceptions.YTMusicServerError: Server returned HTTP 400: Bad Request. Request contains an invalid argument.

![Zrzut ekranu 2024-11-27 234150](https://github.com/user-attachments/assets/70099758-e189-4e11-91ac-461e4c035ce8)

**Comment by ChrisODonnell25** [comment]
I was having the same issue and I had a bit of play around with the content I was pasting from the network tab. Eventually I realised that what I had copied (from Chrome) had a bunch of extra fields when compared to the setup images. Specifically:

priority
sec-ch-ua
sec-ch-ua-arch
sec-ch-ua-bitness
sec-ch-ua-form-factors
sec-ch-ua-full-version
sec-ch-ua-full-version-list
sec-ch-ua-mobile
sec-ch-ua-model
sec-ch-ua-platform
sec-ch-ua-platform-version
sec-ch-ua-wow64
x-client-data

Once I removed those, it worked. I hope this works for you too!

**Comment by booa1986** [comment]
@ChrisODonnell25 thank you for the suggestion. I went through the setup again, carefully following the publisher's instructions. 

The publisher logs into YouTube Music using an incognito window, which I hadn’t done before. Once I completed everything in an incognito window and carefully copied the cookie as instructed, YouTube finally WORKED, and I’m very happy about it!
