### ISSUE TITLE
Is there a limitation for a lengthy song?

### ISSUE THREAD

**Issue by Huiyuen07** [KoljaWindeler/ytube_music_player#373]
**Describe the bug**
I can play most of the songs but not an 8-hour song (https://www.youtube.com/watch?v=jKOJ5OoeS_k), even I put the song a playlist. I use the below script to do so.

```
alias: Play Bed Time Music
sequence:
  - action: media_player.play_media
    data:
      media_content_type: track
      media_content_id: jKOJ5OoeS_k
    enabled: true
    target:
      entity_id: media_player.ytube_music_player
mode: parallel
max: 10
```

**Enable DEBUG Output**
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 843, in async_media_stop
    await self.hass.async_add_executor_job(self.media_stop)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 102, in wrapper
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: CastMediaPlayerEntity.media_stop Failed: Failed to execute stop.
2024-11-30 10:27:11.291 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] play_media, media_type: track, media_id: jKOJ5OoeS_k
2024-11-30 10:27:11.292 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_prepare_play
2024-11-30 10:27:11.292 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2024-11-30 10:27:11.292 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current media_player.AudioHub)  [E]
2024-11-30 10:27:11.295 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_on_media_player [E]
2024-11-30 10:27:12.638 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher
2024-11-30 10:27:12.638 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.audiohub: off -> idle ... not playing [E]
2024-11-30 10:27:12.786 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.audiohub: idle -> idle ... not playing [E]
2024-11-30 10:27:12.892 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player ... media_player.audiohub: idle -> idle ... not playing [E]
2024-11-30 10:27:15.837 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_cipher
2024-11-30 10:27:15.853 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_prepare_play
2024-11-30 10:27:16.177 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] get_song(videoId=jKOJ5OoeS_k,signatureTimestamp=20052)
2024-11-30 10:27:16.178 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] _tracks_to_attribute
2024-11-30 10:27:16.178 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_extra_sensor [E]
2024-11-30 10:27:16.179 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_extra_sensor [E]
2024-11-30 10:27:16.180 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] _tracks_to_attribute
2024-11-30 10:27:16.180 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] _play,shuffle:True,shuffle_mode:Shuffle Random
2024-11-30 10:27:16.181 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_track
2024-11-30 10:27:16.181 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] auto_advance=False,keep_track_no=False,repeat=all,shuffle_mode=Shuffle Random
2024-11-30 10:27:16.181 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Press the next/pref button and shuffle is true, play random track.
2024-11-30 10:27:16.185 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url
2024-11-30 10:27:16.187 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url_self
2024-11-30 10:27:16.188 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2024-11-30 10:27:16.188 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - try to find URL on our own
2024-11-30 10:27:16.560 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] found 5 streams
2024-11-30 10:27:16.561 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - removed stream with too high bitrate of 185755
2024-11-30 10:27:16.561 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - removed stream with too high bitrate of 159237
2024-11-30 10:27:16.561 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Using stream 0/3, bitrate:175011
2024-11-30 10:27:16.561 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - found URL in api data
2024-11-30 10:27:16.561 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_url
2024-11-30 10:27:16.687 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - self decoded url return 403 status code, attempt 60/60
2024-11-30 10:27:16.688 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url_pytube
2024-11-30 10:27:16.799 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2024-11-30 10:27:16.800 ERROR (MainThread) [custom_components.ytube_music_player.media_player] jKOJ5OoeS_k is unavailable
2024-11-30 10:27:16.800 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_url
2024-11-30 10:27:16.800 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Retry with: (3)
2024-11-30 10:27:16.820 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_track
2024-11-30 10:27:16.822 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] auto_advance=False,keep_track_no=False,repeat=all,shuffle_mode=Shuffle Random
2024-11-30 10:27:16.823 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Press the next/pref button and shuffle is true, play random track.
2024-11-30 10:27:16.824 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url
2024-11-30 10:27:16.824 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url_self
2024-11-30 10:27:16.825 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2024-11-30 10:27:16.825 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - try to find URL on our own
2024-11-30 10:27:17.072 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] found 5 streams
2024-11-30 10:27:17.072 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - removed stream with too high bitrate of 185755
2024-11-30 10:27:17.072 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - removed stream with too high bitrate of 159237
2024-11-30 10:27:17.072 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Using stream 0/3, bitrate:175011
2024-11-30 10:27:17.072 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - found URL in api data
2024-11-30 10:27:17.072 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_url
2024-11-30 10:27:17.132 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - self decoded url return 403 status code, attempt 60/60
2024-11-30 10:27:17.133 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url_pytube
2024-11-30 10:27:17.260 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2024-11-30 10:27:17.262 ERROR (MainThread) [custom_components.ytube_music_player.media_player] jKOJ5OoeS_k is unavailable
2024-11-30 10:27:17.262 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_url
2024-11-30 10:27:17.262 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Retry with: (2)
2024-11-30 10:27:17.263 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_track
2024-11-30 10:27:17.263 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] auto_advance=False,keep_track_no=False,repeat=all,shuffle_mode=Shuffle Random
2024-11-30 10:27:17.263 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Press the next/pref button and shuffle is true, play random track.
2024-11-30 10:27:17.264 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url
2024-11-30 10:27:17.265 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url_self
2024-11-30 10:27:17.265 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2024-11-30 10:27:17.265 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - try to find URL on our own
2024-11-30 10:27:17.608 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] found 5 streams
2024-11-30 10:27:17.609 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - removed stream with too high bitrate of 185755
2024-11-30 10:27:17.609 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - removed stream with too high bitrate of 159237
2024-11-30 10:27:17.610 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Using stream 0/3, bitrate:175011
2024-11-30 10:27:17.610 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - found URL in api data
2024-11-30 10:27:17.610 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_url
2024-11-30 10:27:17.847 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - self decoded url return 403 status code, attempt 60/60
2024-11-30 10:27:17.847 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url_pytube
2024-11-30 10:27:18.212 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2024-11-30 10:27:18.215 ERROR (MainThread) [custom_components.ytube_music_player.media_player] jKOJ5OoeS_k is unavailable
2024-11-30 10:27:18.216 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_url
2024-11-30 10:27:18.217 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Retry with: (1)
2024-11-30 10:27:18.227 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_track
2024-11-30 10:27:18.228 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] auto_advance=False,keep_track_no=False,repeat=all,shuffle_mode=Shuffle Random
2024-11-30 10:27:18.228 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Press the next/pref button and shuffle is true, play random track.
2024-11-30 10:27:18.232 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url
2024-11-30 10:27:18.232 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url_self
2024-11-30 10:27:18.245 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api [E]
2024-11-30 10:27:18.269 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - try to find URL on our own
2024-11-30 10:27:18.664 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] found 5 streams
2024-11-30 10:27:18.665 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - removed stream with too high bitrate of 185755
2024-11-30 10:27:18.665 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - removed stream with too high bitrate of 159237
2024-11-30 10:27:18.665 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Using stream 0/3, bitrate:175011
2024-11-30 10:27:18.665 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - found URL in api data
2024-11-30 10:27:18.665 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_url
2024-11-30 10:27:18.790 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - self decoded url return 403 status code, attempt 60/60
2024-11-30 10:27:18.790 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url_pytube
2024-11-30 10:27:18.948 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get URL with YouTube methode
2024-11-30 10:27:18.958 ERROR (MainThread) [custom_components.ytube_music_player.media_player] jKOJ5OoeS_k is unavailable
2024-11-30 10:27:18.959 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_url
2024-11-30 10:27:18.960 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - get track failed to return URL, turning off
2024-11-30 10:27:18.982 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_off_media_player [E]
2024-11-30 10:27:18.983 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] play_media
2024-11-30 10:27:19.041 WARNING (SyncWorker_15) [pychromecast.controllers] STOP command requested but no session is active.
2024-11-30 10:27:19.125 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall media_player.media_stop (c:01JDXE9PSTEP3PHEY2N8QB22AY): entity_id=['media_player.audiohub']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 100, in wrapper
    return_value = func(self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 570, in media_stop
    media_controller.stop()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/media.py", line 642, in stop
    response_handler.wait_response()
  File "/usr/local/lib/python3.12/site-packages/pychromecast/response_handler.py", line 57, in wait_response
    raise RequestFailed(self._request)
pychromecast.error.RequestFailed: Failed to execute stop.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 843, in async_media_stop
    await self.hass.async_add_executor_job(self.media_stop)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 102, in wrapper
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: CastMediaPlayerEntity.media_stop Failed: Failed to execute stop.

**Version**
20241125.01

**Additional context**
My aim is to play the lullaby for my daughter to go to sleep. I also tried music assistant but it cannot play fluently. Media extractor is okay it takes quite long time to load the music every time before playing. Is there any other solutions?

**Comment by rickyxsosa** [comment]
I've been trying to figure this out too. Looks like it's something with Google cast timing out after 10 minutes 

https://community.home-assistant.io/t/google-cast-drops-home-assistant-cast-connection/197373/25

**Comment by Huiyuen07** [comment]
It was working perfectly in playing the same song in early or mid October. Not sure of why suddenly stop supporting the lengthy YouTube Music.
