### ISSUE TITLE
No longer working.

### ISSUE THREAD

**Issue by skewll** [KoljaWindeler/ytube_music_player#374]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

2024-11-30 15:28:01.577 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source(media_player.living_room_speaker)

2024-11-30 15:28:01.578 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.living_room_speaker/ current media_player.bathroom_speaker)  [E]

2024-11-30 15:28:01.578 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.living_room_speaker as player

2024-11-30 15:28:01.578 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack passed

2024-11-30 15:28:01.579 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source

2024-11-30 15:28:01.585 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source_helper

2024-11-30 15:28:01.585 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Translated friendly name living_room_speaker to entity id living_room_speaker

2024-11-30 15:28:01.585 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source_helper

2024-11-30 15:28:01.585 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source(living_room_speaker)

2024-11-30 15:28:01.585 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.living_room_speaker/ current media_player.living_room_speaker) 

2024-11-30 15:28:01.585 DEBUG (MainThread) [custom_components.ytube_music_player.media_player]  no change [E]

2024-11-30 15:28:01.585 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.living_room_speaker as player

2024-11-30 15:28:01.586 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source

2024-11-30 15:28:01.586 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source_helper

2024-11-30 15:28:01.586 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Translated friendly name living_room_speaker to entity id living_room_speaker

2024-11-30 15:28:01.586 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source_helper

2024-11-30 15:28:01.586 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source(living_room_speaker)

2024-11-30 15:28:01.586 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.living_room_speaker/ current media_player.living_room_speaker) 

2024-11-30 15:28:01.586 DEBUG (MainThread) [custom_components.ytube_music_player.media_player]  no change [E]

2024-11-30 15:28:01.586 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.living_room_speaker as player

2024-11-30 15:28:01.587 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source

2024-11-30 15:28:01.587 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source_helper

2024-11-30 15:28:01.587 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Translated friendly name living_room_speaker to entity id living_room_speaker

2024-11-30 15:28:01.587 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source_helper

2024-11-30 15:28:01.587 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_select_source(living_room_speaker)

2024-11-30 15:28:01.587 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input media_player.living_room_speaker/ current media_player.living_room_speaker) 

2024-11-30 15:28:01.587 DEBUG (MainThread) [custom_components.ytube_music_player.media_player]  no change [E]

2024-11-30 15:28:01.587 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.living_room_speaker as player

2024-11-30 15:28:01.587 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_select_source

2024-11-30 15:28:04.580 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack resub

2024-11-30 15:28:04.586 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack passed

2024-11-30 15:28:04.586 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack resub

2024-11-30 15:28:04.587 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack passed

2024-11-30 15:28:04.587 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack resub

2024-11-30 15:28:04.589 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack passed

2024-11-30 15:28:04.590 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - untrack resub

2024-11-30 15:28:30.595 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] play_media, media_type: playlist, media_id: PL2bEft5AYl_7FDyOIqFOxbr1PlkWmO38W

2024-11-30 15:28:30.595 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_prepare_play

2024-11-30 15:28:30.601 DEBUG (MainThread) [custom_components.ytube_music_player.const] - login without brand ID and credential at path /config/.storage/header_ytube_music_player.json

2024-11-30 15:28:31.368 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api ... - no valid API, try to login ... YouTube Api initialized ok, version: 1.8.0 [E]

2024-11-30 15:28:31.368 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current media_player.living_room_speaker)  [E]

2024-11-30 15:28:33.076 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher [E]

2024-11-30 15:28:33.077 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [E] async_prepare_play

2024-11-30 15:28:33.463 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] get_playlist(playlistId=PL2bEft5AYl_7FDyOIqFOxbr1PlkWmO38W)

2024-11-30 15:28:33.463 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

 == == == == == == = ytube_music_player Integration Error == == == == == == == == 

2024-11-30 15:28:33.463 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error, please open a ticket at

2024-11-30 15:28:33.463 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/KoljaWindeler/ytube_music_player/issues

2024-11-30 15:28:33.464 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2024-11-30 15:28:33.468 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):

  File "/config/custom_components/ytube_music_player/media_player.py", line 1625, in async_play_media

    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/ytube_music_player/media_player.py", line 1625, in <lambda>

    playlist_info = await self.hass.async_add_executor_job(lambda: self._api.get_playlist(media_id, limit=self._trackLimit))

                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/ytmusicapi/mixins/playlists.py", line 108, in get_playlist

    response = self._send_request(endpoint, body)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/ytmusicapi/ytmusic.py", line 242, in _send_request

    raise YTMusicServerError(message + error)

ytmusicapi.exceptions.YTMusicServerError: Server returned HTTP 400: Bad Request.

Request contains an invalid argument.

2024-11-30 15:28:33.469 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

thanks, Kolja

2024-11-30 15:28:33.469 ERROR (MainThread) [custom_components.ytube_music_player.media_player]  == == == == == == = ytube_music_player Integration Error == == == == == == == == 

2024-11-30 15:28:33.471 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_off_media_player [E]

      
      
    

**Describe the bug**
Stoppes working awhile ago. On latest v bow and still doesn't work. 

**Version**
Latest

**To Reproduce**
1. Nothing happens at all. Pretends to start and hen stops and and does nothing.

**Additional context**
Worked fine for many months.

Thanks

**Comment by skewll** [comment]
Looks like I just needed to reconfigure and set up the cookie again.
