### ISSUE TITLE
homeassistant.components.websocket_api.http.connection

### ISSUE THREAD

**Issue by xitters** [KoljaWindeler/ytube_music_player#378]
Core
2024.12.1
Supervisor
2024.11.4
Operating System
14.0
Frontend
20241127.6

Registrador: homeassistant.components.websocket_api.http.connection
Fuente: components/websocket_api/commands.py:245
integración: Home Assistant WebSocket API ([documentación](https://www.home-assistant.io/integrations/websocket_api), [problemas](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
Ocurrió por primera vez: 22:52:00 (3 ocurrencias)
Última vez registrado: 22:53:45

[140187727079760] Unexpected exception
[140188407899488] Unexpected exception
[140188788518784] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 1601, in async_play_media
    if(not(await self.async_prepare_play())):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 595, in async_prepare_play
    await self.async_get_cipher('BB2mjBuAtiQ')
  File "/config/custom_components/ytube_music_player/media_player.py", line 713, in async_get_cipher
    self._cipher = pytubefix.cipher.Cipher(js=self._js, js_url=js_url)
                   ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pytubefix/cipher.py", line 25, in __init__
    self.throttling_function_name = get_throttling_function_name(js, js_url)
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pytubefix/cipher.py", line 179, in get_throttling_function_name
    raise RegexMatchError(
        caller="get_throttling_function_name", pattern=f"multiple in {js_url}"
    )
pytubefix.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple in https://youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js

**Comment by yuickey** [comment]
got the same error.

**Comment by KoljaWindeler** [comment]
please try https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20241210.01 an reopen if still present
