### ISSUE TITLE
self decoded url return 403 status code, attempt 60/60

### ISSUE THREAD

**Issue by xitters** [KoljaWindeler/ytube_music_player#384]
Everything works fine, everything plays as expected, but I get this error when I play something through ytube music player, why is it?

Registrador: custom_components.ytube_music_player.media_player
Fuente: custom_components/ytube_music_player/media_player.py:255
integración: YouTube Music Player ([documentación](https://github.com/KoljaWindeler/ytube_music_player), [problemas](https://github.com/KoljaWindeler/ytube_music_player/issues))
Ocurrió por primera vez: 22:17:45 (1 ocurrencias)
Última vez registrado: 22:17:45

- self decoded url return 403 status code, attempt 60/60

![image](https://github.com/user-attachments/assets/0f13876b-ac6d-4fa8-82a7-c04776ee2fe3)

Thanks

**Comment by xitters** [comment]
now in Home Assistant

Core
2024.12.5
Supervisor
2024.12.0
Operating System
14.1
Frontend
20241127.8

2024-12-21 00:50:13.760 ERROR (MainThread) [custom_components.ytube_music_player.media_player] signature not found, decoding
2024-12-21 00:50:13.842 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get own(!) URL for track, further details below. Will not try YouTube method
2024-12-21 00:50:13.845 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1556, in async_get_url_self
    signature = self._cipher.get_signature(ciphered_signature=res['s'])
  File "/usr/local/lib/python3.13/site-packages/pytubefix/cipher.py", line 50, in get_signature
    return self.js_interpreter.call_function(self.signature_function_name, ciphered_signature)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pytubefix/jsinterp.py", line 1096, in call_function
    return self.extract_function(funcname)(args)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pytubefix/jsinterp.py", line 1078, in extract_function
    self.extract_function_from_code(*_fixup_n_function_code(*self.extract_function_code(funcname))),
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pytubefix/jsinterp.py", line 1072, in extract_function_code
    raise self.Exception(f'Could not find JS function "{funcname}"')
pytubefix.jsinterp.JSInterpreter.Exception: Could not find JS function "j"

2024-12-21 00:50:13.845 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Oq-vxM-1y5M
2024-12-21 00:53:22.154 ERROR (MainThread) [custom_components.ytube_music_player.media_player] signature not found, decoding
2024-12-21 00:53:22.235 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get own(!) URL for track, further details below. Will not try YouTube method
2024-12-21 00:53:22.237 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1556, in async_get_url_self
    signature = self._cipher.get_signature(ciphered_signature=res['s'])
  File "/usr/local/lib/python3.13/site-packages/pytubefix/cipher.py", line 50, in get_signature
    return self.js_interpreter.call_function(self.signature_function_name, ciphered_signature)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pytubefix/jsinterp.py", line 1096, in call_function
    return self.extract_function(funcname)(args)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pytubefix/jsinterp.py", line 1078, in extract_function
    self.extract_function_from_code(*_fixup_n_function_code(*self.extract_function_code(funcname))),
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pytubefix/jsinterp.py", line 1072, in extract_function_code
    raise self.Exception(f'Could not find JS function "{funcname}"')
pytubefix.jsinterp.JSInterpreter.Exception: Could not find JS function "j"

2024-12-21 00:53:22.237 ERROR (MainThread) [custom_components.ytube_music_player.media_player] _2hURcrRPpQ
