### ISSUE TITLE
YtubeMediaPlayer does not start

### ISSUE THREAD

**Issue by XalaTheShepard** [KoljaWindeler/ytube_music_player#385]
Dear all,

When starting a playlist from the YtubeMediaPlayer, I get the errors below:

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:2140
integration: yTubeMediaPlayer (documentation, issues)
First occurred: 10:15:26 AM (4 occurrences)
Last logged: 10:40:35 AM

== == == == == == = ytube_music_player Integration Error == == == == == == == ==

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/media_player.py:349
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:15:27 AM (4 occurrences)
Last logged: 10:40:36 AM

[139743985835536] Error handling message: Unknown error (unknown_error) Robin De Becker from 2a02:1811:2d2d:2b00:f167:b121:2387:ac64 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36)
[139744698066992] Error handling message: Unknown error (unknown_error) Robin De Becker from 2a02:1811:2d2d:2b00:634a:7bbf:c282:f2a1 (Mozilla/5.0 (Linux; Android 15; 23127PN0CG Build/AQ3A.240627.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.136 Mobile Safari/537.36 Home Assistant/2024.12.1-14604 (Android 15; 23127PN0CG))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1316, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ytube_music_player/media_player.py", line 2146, in async_browse_media
    await self.async_check_api()
  File "/config/custom_components/ytube_music_player/media_player.py", line 349, in async_check_api
    self._signatureTimestamp = await self.hass.async_add_executor_job(self._api.get_signatureTimestamp)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/ytmusicapi/mixins/browsing.py", line 891, in get_signatureTimestamp
    url = self.get_basejs_url()
  File "/usr/local/lib/python3.13/site-packages/ytmusicapi/mixins/browsing.py", line 877, in get_basejs_url
    raise YTMusicError("Could not identify the URL for base.js player.")
ytmusicapi.exceptions.YTMusicError: Could not identify the URL for base.js player.

If you need any further information, please let me know.

Thanks for looking into the issue and for the support.

Kind regards,

Robin

**Comment by XalaTheShepard** [comment]
Solved:

The cookie information was changed, so copied the new one from the developer tools
