### ISSUE TITLE
Problem with integration

### ISSUE THREAD

**Issue by chonsanova** [KoljaWindeler/ytube_music_player#39]
**What I can get working:** setting everything up, and pressing power on or play to play a random song.

**Where I'm stuck:** trying to use Mini Media Player to set up shortcut buttons to play specific channels or playlists. I get the below error when pressing on such a button.

```
- name: Name
  type: channel
  id: UCUJ3KuIIgvh8eVItvb-EdFQ
```

(For this https://music.youtube.com/channel/UCUJ3KuIIgvh8eVItvb-EdFQ)

See error log below.

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1171
Integration: YouTube Music Player (documentation, issues)
First occurred: 1:08:18 PM (1 occurrences)
Last logged: 1:08:18 PM

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 984, in play_media self._tracks = self._api.get_playlist(playlistId=media_id)['tracks'] File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 66, in get_playlist results = nav(response, SINGLE_COLUMN_TAB + SECTION_LIST)[0]['musicPlaylistShelfRenderer'] File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 167, in nav raise err File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 161, in nav root = root[k] KeyError: 'contents'

**Comment by KoljaWindeler** [comment]
Hi, this is simply bad documentation on my end ... I've just added more details here: https://github.com/KoljaWindeler/ytube_music_player/blob/main/README.md#services

There is no function to call a 'youtube music channel' so I've repurposed the 'channel' type to play a radio. Therefor you can't use a channel id with this argument. Sorry, simply not sypported by the sub-api. I guess you can create a ticket and ask for channel support at https://github.com/sigma67/ytmusicapi
Kolja
