### ISSUE TITLE
Component not working

### ISSUE THREAD

**Issue by Kobiash** [KoljaWindeler/ytube_music_player#44]
============= ytube_music_player Integration Error ================
2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player] and paste the following output:

2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 143, in check_api
self._api = ytmusicapi.YTMusic(self._header_file)
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 96, in init
self.sapisid = sapisid_from_cookie(self.headers['Cookie'])
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/helpers.py", line 57, in sapisid_from_cookie
return cookie['__Secure-3PAPISID'].value
KeyError: '__Secure-3PAPISID'

2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2021-01-07 15:30:32 ERROR (SyncWorker_18) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================

**Comment by KoljaWindeler** [comment]
Hi this is due to a bad cookie. Please repeat the cookie procedure. The next version with catch this during setup

**Comment by Kobiash** [comment]
Just repeated the process.  it is working now.
The issue is with the sample I think.
I have copied copy also the "accept: */*" where the sample image show different.

Anyway, thx.
