### ISSUE TITLE
Stop after every track

### ISSUE THREAD

**Issue by lightzhuk** [KoljaWindeler/ytube_music_player#47]
**Enable DEBUG Output**
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:306
Integration: YouTube Music Player (documentation, issues)
First occurred: 17:05:39 (1 occurrences)
Last logged: 17:05:39

self._state is: (playing).

**Describe the bug**
Traceback (most recent call last):
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ytube_music_player/media_player.py", line 433, in _sync_player
if _player.state == 'playing' and _player.attributes['media_position']>0:
TypeError: '>' not supported between instances of 'str' and 'int'

**Version**
20210106

**Additional context**
Stop after each track. If I switch the track to manual then I hear the next one. But when playing after each track, stop. I'm using speakers connected to the pi. media player mpd addon. Thank you.

Thanks

**Comment by KoljaWindeler** [comment]
Hi, thanks for raising this. Very interesting!
Can you play some music and have a look at the media_position attribute of the player that outputs the music? 
Is that attribute available and if so, what's an example value?

**Comment by lightzhuk** [comment]
at the time of playback media_position: the attribute constantly changes its value, about once every 3 seconds

**Comment by KoljaWindeler** [comment]
ok, can you post an example value .. mine is a simple second counter .. integer values. I suspect that yours loops something like "00:00:12" ?

**Comment by lightzhuk** [comment]
there is no time in the player itself. just buttons for forward, back and play

**Comment by lightzhuk** [comment]
if you go to the web interface mpd I see it 0:06 / 2:56

**Comment by KoljaWindeler** [comment]
please to to the "developer" menu in homeassistant and search for the media_player.ytube_music_player and see if you can find something there

**Comment by KoljaWindeler** [comment]
or check if your media_player (the one you are playing your music on) has that attribute

**Comment by lightzhuk** [comment]
volume_level: 0.3
is_volume_muted: false
media_content_type: music
media_position: 14
media_position_updated_at: 2021-01-10T19:43:57.745671+00:00
media_title: To the Moon & Back
media_artist: Savage Garden
media_album_name: 
shuffle: true
repeat: all
entity_picture_local: /api/media_player_proxy/media_player.ytube_music_player?token=6ce2113f2591a3b3dd5a7befe193f508ec9964e00986e27a59d88
_media_type: channel
_media_id: LM
_player_state: playing
playlists: Your Likes, Моменты, Queen хиты, Sea of Positive Pop, I Feel Good: Cheerful Soul, Post-Dubstep Laze, Traffic Busting Indie Sing-Along, Fun to Run, Pop Car Ride, Energizing EDM, Rave-Up Wake-Up: EDM Morning, Café Latino, Feel-Good Reggae, All-Time Pumped-Up Hits, Office Indie Disco, Cool Kids of the 90s, Electric Ukraine, Synthwave Time Machine, Deep Techno Concentration, Drum & Bass Anthems, Downtempo Instrumentals, Best New Chilled, Atmospheric Chilled Electronica, Dark Electro Lounging, Diving Deep Into Techno, Атмосферный электронный чилаут, Коля Маню, Free
total_tracks: 25
tracks: Savage Garden - To the Moon & Back, Alanis Morissette - Ironic, The Cranberries - Zombie, Dido - Here With Me, Dido - Thank You, Bon Jovi - Always, Bonnie Tyler - Total Eclipse of the Heart, No Doubt - It's My Life, Roxette - Spending My Time, Alanis Morissette - Thank U, Dido - Life for Rent, Roxette - Fading Like A Flower (Every Time You Leave), Sinéad O'Connor - Nothing Compares 2 U, Natalie Imbruglia - Torn, The Goo Goo Dolls - Iris, The Calling - Wherever You Will Go, The Cranberries - When You're Gone, Roxette - The Look, U2 - With Or Without You, Roxette - Listen To Your Heart, Roxette - It Must Have Been Love (From the Film "Pretty Woman"), The Cranberries - Linger, Sheryl Crow - Sweet Child O' Mine, Joan Osborne - One Of Us, The Corrs - Breathless
current_track: 0
videoId: aiGL0MaV
likeStatus: 
lyrics: No lyrics available
_player_id: media_player.mpd
friendly_name: ytube_music_player
icon: mdi:music-circle
entity_picture: https://lh3.googleusercontent.com/otK781lcTCrWss4tSglJ4-ysRk9zzTeSnb0aJwAUWN5kOaNJtdLQ2Hk8tYe48HaQ=w544
supported_features: 450493

**Comment by KoljaWindeler** [comment]
ok, can you also copy the attriubutes of media_player.mpd while playing? 



Also would you feel comfortable editing the python files to add some debug? 
If so: 

basically replace 490-494 of media_player.py
https://github.com/KoljaWindeler/ytube_music_player/blob/e45250b29d3be21d0391a85b024ec680c94fef60/custom_components/ytube_music_player/media_player.py#L490

with 

```
found_pos = False
if 'media_position' in _player.attributes:
	_LOGGER.error(_player.attributes['media_position'])
	if(isinstance(_player.attributes['media_position'],int)):
		found_pos = True
		if _player.state == 'playing' and _player.attributes['media_position']>0:
			self._allow_next = True
if not(found_pos) and _player.state == 'playing': # fix for browser mod media_player not providing the 'media_position'
	self._allow_next = True

```
I use TABS for intents

**Comment by lightzhuk** [comment]
volume_level: 0.2
is_volume_muted: false
media_content_id: https://r2---sn-4gxb5u-qo3s.googlevideo.com/videoplayback?expire=1610332303&ei=L2T7X4jTAuSA6dsP1pOA6AE&ip=46.98.128.137&id=o-ADnM6nD3gwPtpFS_Qq-cV8Mku1A1m2iKulEHEjiocC_x&itag=140&source=youtube&requiressl=yes&mh=NM&mm=31%2C29&mn=sn-4gxb5u-qo3s%2Csn-3c27snel&ms=au%2Crdu&mv=m&mvi=2&pl=16&ctier=A&pfa=5&gcr=ua&initcwndbps=1100000&hightc=yes&vprv=1&mime=audio%2Fmp4&ns=dRGu4ef5YugMsfE806yP3BYF&gir=yes&clen=3279257&dur=202.466&lmt=1570350501595401&mt=1610310028&fvip=11&keepalive=yes&c=WEB_REMIX&txp=1311222&n=vN-G8HlZaTGd_a&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgaNH6h7T8lsTBoP8XmW99QPtbhp1oJnS0bNNhuOTn4p0CIAOtYBgkEcErQIkfv69vhgSR7MAAHU1q8CCiwQXRSCnE&sig=AOq0QJ8wRQIhAKs3-QtmF8NA1gz1l1BBy70vhnIcAh2IjQDt8PaBw4pOAiARABKScVlBM1zlliPWYKfmitxaLbVOHFIKYxQY7cnoXw==
media_content_type: music
media_position: 48
media_position_updated_at: 2021-01-10T20:32:32.519372+00:00
media_title: videoplayback?expire=1610332303&ei=L2T7X4jTAuSA6dsP1pOA6AE&ip=46.98.128.137&id=o-ADnM6nD3gwPtpFS_Qq-cV8Mku1A1m2iKulEHEjiocC_x&itag=140&source=youtube&requiressl=yes&mh=NM&mm=31%2C29&mn=sn-4gxb5u-qo3s%2Csn-3c27snel&ms=au%2Crdu&mv=m&mvi=2&pl=16&ctier=A&pfa=5&gcr=ua&initcwndbps=1100000&hightc=yes&vprv=1&mime=audio%2Fmp4&ns=dRGu4ef5YugMsfE806yP3BYF&gir=yes&clen=3279257&dur=202.466&lmt=1570350501595401&mt=1610310028&fvip=11&keepalive=yes&c=WEB_REMIX&txp=1311222&n=vN-G8HlZaTGd_a&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgaNH6h7T8lsTBoP8XmW99QPtbhp1oJnS0bNNhuOTn4p0CIAOtYBgkEcErQIkfv69vhgSR7MAAHU1q8CCiwQXRSCnE&sig=AOq0QJ8wRQIhAKs3-QtmF8NA1gz1l1BBy70vhnIcAh2IjQDt8PaBw4pOAiARABKScVlBM1zlliPWYKfmitxaLbVOHFIKYxQY7cnoXw==
shuffle: false
repeat: off
friendly_name: MPD
entity_picture: /api/media_player_proxy/media_player.mpd?token=33b90d66c6c686783cc941780e288bfe2fce65daa4803ab1582ca2d0ae12de0d
supported_features: 327615

**Comment by lightzhuk** [comment]
I edited the file but it did not bring results (

**Comment by KoljaWindeler** [comment]
Hmm so you've edited the file, restarted Homeassistent and you still get the very same error? Is that correct?

Your log should now also have quite some error messages that should just contain the media_position. Could you copy some of them to this isses? It's really strange .. your post above shows that the mpd position is something like 48 which looks fine to me. "00:00:48" would totally explain the issue but 48 does not ...

**Comment by lightzhuk** [comment]
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:492
Integration: YouTube Music Player (documentation, issues)
First occurred: 0:02:58 (9 occurrences)
Last logged: 0:03:16

0
3
4
13




Logger: homeassistant.components.mpd.media_player
Source: components/mpd/media_player.py:294
Integration: mpd (documentation, issues)
First occurred: 0:02:59 (2 occurrences)
Last logged: 0:03:00

Retrieving artwork through `albumart` command failed: [50@0] {albumart} No file exists







Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:355
Integration: YouTube Music Player (documentation, issues)
First occurred: 0:02:55 (1 occurrences)
Last logged: 0:02:55

self._state is: (playing).






2021-01-11 00:02:55 ERROR (SyncWorker_3) [custom_components.ytube_music_player.media_player] self._state is: (playing).
2021-01-11 00:02:58 ERROR (SyncWorker_6) [custom_components.ytube_music_player.media_player] 0
2021-01-11 00:02:59 WARNING (MainThread) [homeassistant.components.mpd.media_player] Retrieving artwork through `albumart` command failed: [50@0] {albumart} No file exists
2021-01-11 00:03:00 ERROR (SyncWorker_9) [custom_components.ytube_music_player.media_player] 0
2021-01-11 00:03:00 WARNING (MainThread) [homeassistant.components.mpd.media_player] Retrieving artwork through `albumart` command failed: [50@0] {albumart} No file exists
2021-01-11 00:03:04 ERROR (SyncWorker_7) [custom_components.ytube_music_player.media_player] 3
2021-01-11 00:03:04 ERROR (SyncWorker_4) [custom_components.ytube_music_player.media_player] 3
2021-01-11 00:03:04 ERROR (SyncWorker_20) [custom_components.ytube_music_player.media_player] 3
2021-01-11 00:03:05 ERROR (SyncWorker_10) [custom_components.ytube_music_player.media_player] 4
2021-01-11 00:03:14 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] 13
2021-01-11 00:03:15 ERROR (SyncWorker_6) [custom_components.ytube_music_player.media_player] 13
2021-01-11 00:03:16 ERROR (SyncWorker_10) [custom_components.ytube_music_player.media_player] 13
2021-01-11 00:03:24 ERROR (SyncWorker_17) [custom_components.ytube_music_player.media_player] 23
2021-01-11 00:03:34 ERROR (SyncWorker_20) [custom_components.ytube_music_player.media_player] 33
2021-01-11 00:03:42 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.ficus_battery is taking over 10 seconds
2021-01-11 00:03:44 ERROR (SyncWorker_20) [custom_components.ytube_music_player.media_player] 43
2021-01-11 00:03:51 ERROR (SyncWorker_6) [pygatt.backends.gatttool.gatttool] Unexpected error when scanning: Set scan parameters failed: I/O error
2021-01-11 00:03:51 ERROR (SyncWorker_6) [homeassistant.components.bluetooth_le_tracker.device_tracker] Error during Bluetooth LE scan: Unexpected error when scanning: Set scan parameters failed: I/O error
2021-01-11 00:03:54 ERROR (SyncWorker_20) [custom_components.ytube_music_player.media_player] 53
2021-01-11 00:04:04 ERROR (SyncWorker_4) [custom_components.ytube_music_player.media_player] 63
2021-01-11 00:04:14 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] 73
2021-01-11 00:04:24 ERROR (SyncWorker_12) [custom_components.ytube_music_player.media_player] 83
2021-01-11 00:04:34 ERROR (SyncWorker_10) [custom_components.ytube_music_player.media_player] 93
2021-01-11 00:04:44 ERROR (SyncWorker_22) [custom_components.ytube_music_player.media_player] 103
2021-01-11 00:04:54 ERROR (SyncWorker_21) [custom_components.ytube_music_player.media_player] 113
2021-01-11 00:05:04 ERROR (SyncWorker_6) [custom_components.ytube_music_player.media_player] 123
2021-01-11 00:05:14 ERROR (SyncWorker_0) [custom_components.ytube_music_player.media_player] 133

**Comment by KoljaWindeler** [comment]
looks perfect, but still isn't moving to the next track, correct? 

do you still see the error
```
File "/config/custom_components/ytube_music_player/media_player.py", line 433, in _sync_player
if _player.state == 'playing' and _player.attributes['media_position']>0:
TypeError: '>' not supported between instances of 'str' and 'int'
```

I've uploaded another version, (https://raw.githubusercontent.com/KoljaWindeler/ytube_music_player/main/custom_components/ytube_music_player/media_player.py) but I don't think that it will do the trick

could you enable the debug information and stop the debug messages?

**Comment by lightzhuk** [comment]
I will gladly do whatever is necessary. Just don't quite understand what is needed from me ..

**Comment by KoljaWindeler** [comment]
sorry 
a) please confirm that you still see the error from above
b) enable debug log (see https://github.com/KoljaWindeler/ytube_music_player#debug-information)
and please post the log here
c) replace your media_player.py with the newest version from https://raw.githubusercontent.com/KoljaWindeler/ytube_music_player/main/custom_components/ytube_music_player/media_player.py

I don't expect that c) will help, but it is worth to try

**Comment by lightzhuk** [comment]
I don't see an error from above

**Comment by lightzhuk** [comment]
2021-01-11 22:42:18 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] Config via YAML
2021-01-11 22:42:18 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] YtubeMediaPlayer config:
2021-01-11 22:42:18 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] - Header path: /config/.storage/ytube_header.json
2021-01-11 22:42:18 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] - playlist: input_select.ytube_music_player_playlist
2021-01-11 22:42:18 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] - mediaplayer: input_select.ytube_music_player_speakers
2021-01-11 22:42:18 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] - source: input_select.ytube_music_player_source
2021-01-11 22:42:18 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] - speakerlist: ['mpd', 'remote_vlc_player', 'lg_webos_tv_sk8100pla']
2021-01-11 22:42:18 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] - playModes: input_select.ytube_music_player_playmode
2021-01-11 22:42:18 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] - playContinuous: input_boolean.ytube_music_player_playcontinuous

**Comment by lightzhuk** [comment]
Logger: homeassistant.components.mpd.media_player
Source: components/mpd/media_player.py:294
Integration: mpd (documentation, issues)
First occurred: 22:42:24 (8 occurrences)
Last logged: 22:43:09

Retrieving artwork through `albumart` command failed: [50@0] {albumart} No file exists

**Comment by lightzhuk** [comment]
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:355
Integration: YouTube Music Player (documentation, issues)
First occurred: 22:42:40 (3 occurrences)
Last logged: 22:43:03

self._state is: (playing).

**Comment by lightzhuk** [comment]
The player still stops after every track

**Comment by kombi21251** [comment]
Hello! I have the same problem.

Could it be related to mpd stream specifics?

By the way, when I select my mpd_media_player as speakers on ytube_music_player, the last one streams an link on track to mpd_media_player, which is cached.
When I click on the next track, ytube_music_player turns off and mpd_media_player gets a new link and keeps playing. Turning on ytube_music_player next turns off mpd_media_player.

The mpd integration also supports the next and previous track. This might conflict with ytube_music_player?

This is my LOG:
`
[custom_components.ytube_music_player.media_player] check_api
2021-01-11 23:08:19 DEBUG (SyncWorker_10) [custom_components.ytube_music_player.media_player] - try to find URL on our own
2021-01-11 23:08:19 DEBUG (SyncWorker_10) [custom_components.ytube_music_player.media_player] - self decoded URL via cipher
2021-01-11 23:08:19 WARNING (SyncWorker_0) [pycec] Not initialized. Waiting for init.
2021-01-11 23:08:19 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] _sync_player
2021-01-11 23:08:19 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] media_player.raspberry_pi_audio: playing -> off
2021-01-11 23:08:19 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] media player got turned off
2021-01-11 23:08:19 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] turn_off
2021-01-11 23:08:19 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] _turn_off_media_player
2021-01-11 23:08:20 WARNING (SyncWorker_0) [pycec] Not initialized. Waiting for init.
2021-01-11 23:08:21 WARNING (SyncWorker_0) [pycec] Not initialized. Waiting for init.
2021-01-11 23:08:22 WARNING (SyncWorker_0) [pycec] Not initialized. Waiting for init.
2021-01-11 23:08:22 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] TURNON
2021-01-11 23:08:22 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] prepare_play
2021-01-11 23:08:22 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] check_api
2021-01-11 23:08:22 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] _update_remote_player
2021-01-11 23:08:22 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] _turn_on_media_player
2021-01-11 23:08:22 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] _get_cipher
2021-01-11 23:08:22 DEBUG (SyncWorker_6) [custom_components.ytube_music_player.media_player] _sync_player
2021-01-11 23:08:22 DEBUG (SyncWorker_6) [custom_components.ytube_music_player.media_player] media_player.raspberry_pi_audio: off -> playing
2021-01-11 23:08:23 WARNING (SyncWorker_0) [pycec] Not initialized. Waiting for init.
2021-01-11 23:08:24 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] _load_playlist
2021-01-11 23:08:24 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] play_media, media_type: playlist, media_id: LM
2021-01-11 23:08:24 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] prepare_play
2021-01-11 23:08:24 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] check_api
2021-01-11 23:08:24 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] _update_remote_player
2021-01-11 23:08:24 ERROR (SyncWorker_3) [custom_components.ytube_music_player.media_player] self._state is: (playing).
2021-01-11 23:08:24 DEBUG (SyncWorker_3) [custom_components.ytube_music_player.media_player] _get_cipher
2021-01-11 23:08:24 DEBUG (SyncWorker_5) [custom_components.ytube_music_player.media_player] _sync_player
2021-01-11 23:08:24 DEBUG (SyncWorker_5) [custom_components.ytube_music_player.media_player] media_player.raspberry_pi_audio
`

**Comment by KoljaWindeler** [comment]
Hi, so i got curious .. and installed MPD .. _and I wasn't able to listen to music .. but after some configuration it finally did._
Turns out that the player changes from playing to off once it reaches a track ... other players usually transition from playing to idle.
That's the problem as far as i can see ..

**Comment by KoljaWindeler** [comment]
ok, can you update your integration via git (no new release for HACS available) or download and replace these two files:
https://raw.githubusercontent.com/KoljaWindeler/ytube_music_player/main/custom_components/ytube_music_player/media_player.py
https://raw.githubusercontent.com/KoljaWindeler/ytube_music_player/main/custom_components/ytube_music_player/const.py

once you've restarted HA please execute this:
Service: ytube_music_player.call_method
entity_id: media_player.ytube_music_player
command: off_is_idle

that should print in the log:
`[custom_components.ytube_music_player.media_player] Setting off_is_idle to True`

After that you can start whatever you want ... it should keep playing ..  let me know if that works
Kolja

**Comment by lightzhuk** [comment]
I did everything according to your instructions above and everything began to work. Bravo!! it's an amazing speed of problem solving. It's a pity that I didn't write earlier. In any case, thanks again for the opportunity to listen to your favorite music, and now without stopping. Super!! Great job.

**Comment by lightzhuk** [comment]
There is still an error in my log

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:356
Integration: YouTube Music Player (documentation, issues)
First occurred: 8:08:05 (3 occurrences)
Last logged: 8:17:56

self._state is: (playing).

**Comment by KoljaWindeler** [comment]
Found and change to debug. I think we're done here, right? This will be part of the next release .. unfortunately you will have to call the service after every reboot but i guess that can easily be a part of an automation.

**Comment by lightzhuk** [comment]
- alias: mpd_fix
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - delay: 00:00:12
    - service: ytube_music_player.call_method
      entity_id: media_player.ytube_music_player
      data:
        command: off_is_idle

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player/blob/main/README.md#mpd-fix
