### ISSUE TITLE
Log File Error

### ISSUE THREAD

**Issue by rjgrandy** [KoljaWindeler/ytube_music_player#50]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**

I installed the integration, added the cookie, and the full_control yaml view in the packages folder. The playlists do not seem to load and the following error shows up in the log.

2021-01-10 22:07:35 ERROR (SyncWorker_0) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 705, in _update_playlists
    self._playlists = self._api.get_library_playlists(limit = 99)
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py", line 39, in get_library_playlists
    get_continuations(results, 'gridContinuation', limit - len(playlists),
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 86, in get_continuations
    contents = get_continuation_contents(results, parse_func)
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 129, in get_continuation_contents
    return parse_func(continuation[term])
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py", line 37, in <lambda>
    parse_func = lambda contents: parse_content_list(contents, parse_playlist)
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/browsing.py", line 165, in parse_content_list
    contents.append(parse_func(result['musicTwoRowItemRenderer']))
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/browsing.py", line 202, in parse_playlist
    'title': nav(data, TITLE_TEXT),
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 167, in nav
    raise err
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 161, in nav
    root = root[k]
KeyError: 'runs'

2021-01-10 22:07:35 ERROR (SyncWorker_0) [custom_components.ytube_music_player.media_player] 

**Version**
20200110

**To Reproduce**

**Additional context**

Thanks

**Comment by KoljaWindeler** [comment]
Hi this look like a cookie problem. 
Did you install the latest version (20210110)?
No issues during the setup procedure (config_flow)?
Thanks

**Comment by rjgrandy** [comment]
Hi, yes I think it is a cookie issue too. I installed the latest value, I believe the setup goes okay, although there is no indication that it authenticates properly or anything. I am following what you wrote on your readme to get the cookie. When I do the search on /browse, I get a number of items returned, is it possible I am selecting the wrong one? In your writeup you mention you only get one return

I did the method to get the cookie in incognito mode with the same results.

**Comment by KoljaWindeler** [comment]
I've updated the setup instructions and added pictures. Can you check if that helps?

**Comment by rjgrandy** [comment]
I've updated to the latest version. However I still seem to be having issues. 

I copied your markdown.yaml to a view in my lovelace and if I fill in a playlist id I can get the mini-media-player to work and play out one of my speakers however the playlist list doesn't populate, I don't see anything in the media browser and the I am still getting an error message in the log:

```
2021-01-14 18:02:44 ERROR (SyncWorker_8) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 711, in _update_playlists
    self._playlists = self._api.get_library_playlists(limit = 99)
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py", line 39, in get_library_playlists
    get_continuations(results, 'gridContinuation', limit - len(playlists),
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 86, in get_continuations
    contents = get_continuation_contents(results, parse_func)
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 129, in get_continuation_contents
    return parse_func(continuation[term])
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/library.py", line 37, in <lambda>
    parse_func = lambda contents: parse_content_list(contents, parse_playlist)
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/browsing.py", line 165, in parse_content_list
    contents.append(parse_func(result['musicTwoRowItemRenderer']))
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/browsing.py", line 202, in parse_playlist
    'title': nav(data, TITLE_TEXT),
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 167, in nav
    raise err
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 161, in nav
    root = root[k]
KeyError: 'runs'
```

**Comment by rjgrandy** [comment]
I found where to get the media_browser view, I didn't realize I needed to open the ytube_music_player more info tab.

![image](https://user-images.githubusercontent.com/34561734/104680097-bd011980-56b4-11eb-9b54-9d0e4aa2db97.png)

**Comment by KoljaWindeler** [comment]
Hey, both should work. The drop down should fill as well as the mediabrowser should show you your music. 
I'm almost 100% certain that this is a cookie problem.
Did you check out the pictures about "how to get the cookie data"? The setup procedure should now also provide more feedback

**Comment by KoljaWindeler** [comment]
Is this still an issue?

**Comment by rjgrandy** [comment]
Yes, I think for some reason it is working now. Thanks
