### ISSUE TITLE
Failed to call service media player/play_media. 'NoneType' object has no attribute 'state'

### ISSUE THREAD

**Issue by serviceiotcc** [KoljaWindeler/ytube_music_player#52]
When trying to turn on a track, an error occurs "Failed to call service media player/play_media. 'NoneType' object has no attribute 'state'"

The track being played is not displayed, although the track history is working properly. HA has rebooted several times

**Comment by KoljaWindeler** [comment]
Please enable debug output and copy the log into this ticket

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player#debug-information

**Comment by serviceiotcc** [comment]
![image](https://user-images.githubusercontent.com/74203855/104335625-9bf9c680-5504-11eb-897c-99740615354a.png)

```
2021-01-12 18:32:53 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548046287200] 'NoneType' object has no attribute 'state'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 630, in async_play_media
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1061, in play_media
    self.prepare_play()
  File "/config/custom_components/ytube_music_player/media_player.py", line 352, in prepare_play
    if _player.state == STATE_OFF:
AttributeError: 'NoneType' object has no attribute 'state'
```

**Comment by KoljaWindeler** [comment]
thanks, please enable debug informations .. that will give a lot of DEBUG messages in the log .. otherwise I can't really help

**Comment by serviceiotcc** [comment]
This is what is written in my configuration
![image](https://user-images.githubusercontent.com/74203855/104338373-7f12c280-5507-11eb-8d6e-3b2b75a83ce2.png)

But in the core logs, besides this error, there are only other errors that are not related to the media player

![image](https://user-images.githubusercontent.com/74203855/104338662-cb5e0280-5507-11eb-870d-758ded29bd4d.png)

**Comment by KoljaWindeler** [comment]
Honestly this is so strange that I'd recommend that you reinstall the component. There is no way how the state can be None ..  at least non I could think of. 

Which version are you running? Is there an update available at HACS? Did you install via hacs?

**Comment by serviceiotcc** [comment]
I reinstalled the component, now this error occurs. The version of both the HACS and the plugin is the latest. Your plugin installed through via HACS.
![image](https://user-images.githubusercontent.com/74203855/105062838-1a69e180-5a8c-11eb-8bf7-ab928aac6ddf.png)


```
2021-01-19 19:23:33 DEBUG (SyncWorker_24) [custom_components.ytube_music_player.media_player] - self decoded URL via cipher
2021-01-19 19:23:33 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548355647808] not a valid value for dictionary value @ data['entity_id']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 630, in async_play_media
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1108, in play_media
    self._play()
  File "/config/custom_components/ytube_music_player/media_player.py", line 846, in _play
    self._get_track()
  File "/config/custom_components/ytube_music_player/media_player.py", line 942, in _get_track
    self.hass.services.call(DOMAIN_MP, SERVICE_PLAY_MEDIA, data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1357, in call
    return asyncio.run_coroutine_threadsafe(
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/core.py", line 1399, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 215, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 339, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: not a valid value for dictionary value @ data['entity_id']
```

**Comment by KoljaWindeler** [comment]
Hi, how did you configure the component? via YAML or via config flow? 
I'd recommend to use config flow and remove the yaml part.
Could you also copy the first debug messages at the very top where it shows the version and what the configuration looks like, thanks

**Comment by serviceiotcc** [comment]
I do not fully understand your question. After adding a component from the store, I rebooted the system, opened the integrations, clicking the plus there, chose your integration, then filled in all the required fields.

Here are all the logs. Moreover, this time they differ from those that were before.

![image](https://user-images.githubusercontent.com/74203855/105067653-f65ccf00-5a90-11eb-9ef1-52893036f0e5.png)
![image](https://user-images.githubusercontent.com/74203855/105067706-083e7200-5a91-11eb-951b-ae4cc0d654e4.png)

**Comment by KoljaWindeler** [comment]
Do you have anything related to Media_player: ytube_music_player in your yaml?

**Comment by KoljaWindeler** [comment]
is this still an issue?

**Comment by prithvi1974** [comment]
Facing same issue, tried re-installing from HACS and configuring it again. Still an issue

**Comment by KoljaWindeler** [comment]
Do you have anything related to Media_player: ytube_music_player in your yaml?

**Comment by KoljaWindeler** [comment]
Please also enable debug output and paste the log into this ticket. What kind of player are you using to listen to the music? E.g. chromecast / mpd / sonos ?

**Comment by prithvi1974** [comment]
Works for me now, I'd copied the cookie data from `accept: ...` to `x-goog-visitor-id: ...`
Instead I copied all the key value pairs in there and pasted it into the field in the options of the integration
Works like a charm, thanks @KoljaWindeler

**Comment by serviceiotcc** [comment]
> Do you have anything related to Media_player: ytube_music_player in your yaml?

No, there is not a single mention of ytube_music_player in the yaml

**Comment by serviceiotcc** [comment]
> Works for me now, I'd copied the cookie data from `accept: ...` to `x-goog-visitor-id: ...`
> Instead I copied all the key value pairs in there and pasted it into the field in the options of the integration

Please tell me in more detail from what place and to what place you need to copy?

**Comment by skyche21** [comment]
I have same trouble. Maybe someone knows how to fix it?

**Comment by Cyberfighter** [comment]
I had the same problem. I'm not sure if it's supposed to create the input_selects on it's own but I noticed they were missing so I added them based on the yaml that is in packages example. I ran the reload_dropdowns service but the speakers select still just had loading in there.

What finally got it working was manually adding a speaker as one of the speaker options in the input_select and then setting it to that.

I was also getting this in the logs but not sure if it's related.
![image](https://user-images.githubusercontent.com/7525038/107054300-cb5ac680-6784-11eb-840e-68aaaeb16dd9.png)

**Comment by grayac2** [comment]
> 
> 
> I had the same problem. I'm not sure if it's supposed to create the input_selects on it's own but I noticed they were missing so I added them based on the yaml that is in packages example. I ran the reload_dropdowns service but the speakers select still just had loading in there.
> 
> What finally got it working was manually adding a speaker as one of the speaker options in the input_select and then setting it to that.
> 
> I was also getting this in the logs but not sure if it's related.
> ![image](https://user-images.githubusercontent.com/7525038/107054300-cb5ac680-6784-11eb-840e-68aaaeb16dd9.png)

Exact same problem here. I can get it to work by creating the input_selects and manually inputting the speakers, but no matter what I do, the component will not update the dropdowns.

Additionally, I have been getting the same I/O warnings as you.

**Comment by KoljaWindeler** [comment]
@skyche21 / @grayac2  / @Cyberfighter 
could any of you enable the debug output and copy the complete log into this ticket (or at least all lines coming from this integration).
Thanks

**Comment by ps1x** [comment]
Getting same error, here is my traceback:
```
[140039835879024] 'NoneType' object has no attribute 'state'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 550, in async_turn_on
    await self.hass.async_add_executor_job(self.turn_on)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 316, in turn_on
    playlist  = self.hass.states.get(self._select_playlist).state
AttributeError: 'NoneType' object has no attribute 'state'
```
extra info: I'm using fedora linux as client and home assistant runs in docker on fedora server. I opened youtube muisic in incognito mode and copied headers from 'browse' query as in tutorial (how you parse this mess anyway? i think error might sit somewhere here)

**Comment by KoljaWindeler** [comment]
I'm serious .. we'll never fix this without a complete log.

**Comment by grayac2** [comment]
After messing around with it some more, I somehow got it to work a bit after I posted here. I believe I had to manually add the speakers to the list like @Cyberfighter did, and then the lists populated themselves upon reboot. Once they populated themselves that first time, it's been smooth sailing since, so I don't think I have anything of use to provide at this point.

**Comment by ps1x** [comment]
Strangely it works for me now as well after reinstalling HACS repo and re-configuring plugin.

**Comment by Cyberfighter** [comment]
It is working for me as well now. I had an update for this integration that was from 2/9/21, a HACs update and going from HA 2021.2.1 to 2021.2.3 which all of that of course required a restart so not sure which of those things fixed it but it's up and running now.

**Comment by KoljaWindeler** [comment]
alright, so we can close this now?

**Comment by skyche21** [comment]
Its always say - yTubeMediaPlayer error
You have no playlist entity_id in your config, or that entity_id is not in homeassistant. I don't know what to play and will exit. Either use the media_browser or add the playlist dropdown.
When I try to chose track it says - Failed to call service media player/play_media. 'NoneType' object has no attribute 'state'

**Comment by skyche21** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/ytube_music_player/media_player.py:371
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 7:16:54 (1 occurrences) 
Last logged: 7:16:54

[2809333072] 'NoneType' object has no attribute 'state'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 136, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 630, in async_play_media
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 1055, in play_media
    self.prepare_play()
  File "/config/custom_components/ytube_music_player/media_player.py", line 371, in prepare_play
    if _player.state == STATE_OFF:
AttributeError: 'NoneType' object has no attribute 'state'

**Comment by KoljaWindeler** [comment]
I'm serious .. we'll never fix this without a complete log. ... and by that I mean that debug information needs to be turned on. 
and the log has to cover everything from boot of homeassistant all the way to the start of the player and the error. 

you can erase all line that aren't from the ytube_music_player if you feel the need. 
Also I'll release a version with more debug. but please ENABLE DEBUG https://github.com/KoljaWindeler/ytube_music_player#debug-information

**Comment by KoljaWindeler** [comment]
the new version is released and will prevent the error .. but still not solve the problem (I guess) please post a log

**Comment by KoljaWindeler** [comment]
any update or can we close this?
