### ISSUE TITLE
Error during HA start

### ISSUE THREAD

**Issue by bobvmierlo** [KoljaWindeler/ytube_music_player#62]
```
Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:199
Integration: Media Player (documentation, issues)
First occurred: 20:00:02 (1 occurrences)
Last logged: 20:00:02

Error while setting up ytube_music_player platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 878, in shield
    inner = ensure_future(arg, loop=loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 684, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required

```

**Describe the bug**
See error above, additional debug logs do not show anything related to this error.
Error seems new since updating to HA 2021.1.5

**Version**
20210121

**Comment by samhed** [comment]
I get the same error:

```
Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:199
Integration: Mediaspelare (documentation, issues)
First occurred: 23:35:58 (1 occurrences)
Last logged: 23:35:58

Error while setting up ytube_music_player platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 878, in shield
    inner = ensure_future(arg, loop=loop)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 684, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

Version 20210121 of yTube Music Player, and version 2021.1.5 of Home Assistant, running in a docker container.

**Comment by samhed** [comment]
Furthermore, I now also get this notice from HA:

```
Issue during login: Running get_library_songs resulted in an exception, no idea why.. honestly
```

**Comment by KoljaWindeler** [comment]
> Furthermore, I now also get this notice from HA:
> 
> ```
> Issue during login: Running get_library_songs resulted in an exception, no idea why.. honestly
> ```

This happened yesterday to me as well .. please keep in mind that you cookie CAN get invalid .. .e.g. when you log out in the browser or it expires. I've just grabbed a new cookie and it works again.

**Comment by samhed** [comment]
It did indeed work to get a new cookie.
