### ISSUE TITLE
Music didn't play and traceback after upgrade to 20210207

### ISSUE THREAD

**Issue by samhed** [KoljaWindeler/ytube_music_player#66]
**Describe the bug**
After upgrading to 20210207 using HACS I couldn't start the music. I got the following traceback in the log today:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 254, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1455, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 550, in async_turn_on
    await self.hass.async_add_executor_job(self.turn_on)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ytube_music_player/media_player.py", line 346, in turn_on
    return self.play_media(media_type=self._attributes['_media_type'], media_id=self._attributes['_media_id'])
  File "/config/custom_components/ytube_music_player/media_player.py", line 1105, in play_media
    self._tracks_to_attribute()
  File "/config/custom_components/ytube_music_player/media_player.py", line 803, in _tracks_to_attribute
    info = self.extract_info(track)
  File "/config/custom_components/ytube_music_player/media_player.py", line 606, in extract_info
    if 'name' in _track['artists'][0]:
IndexError: list index out of range
```

**Version**
20210207

**To Reproduce**
Not sure, it only happened once after upgrading the ytube_music_player in HACS. The problem went away after restarting home assistant.

**Additional context**
Home Assistant 2021.2.1

I don't know, it looks in the traceback like that particular track didn't have any artist? I don't know which track it was as I started a "playlist_radio" when it happened.

**Comment by KoljaWindeler** [comment]
hmm but you can now restart the player? so it just happened for that one track?

**Comment by samhed** [comment]
Correct, now it works fine.

**Comment by samhed** [comment]
It happened again now - when switching to a new track the music stopped playing. And I got the above traceback in the log. A workaround was to simply restart the `media_player.ytube_music_player`. 

To me it seems like some type of track trigger this bugg.

**Comment by KoljaWindeler** [comment]
Please try https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20210209
and see if you can figure out which track is causing this ... your playlist should load completely but might miss the artist of that one track that causes the error.

**Comment by samhed** [comment]
Thanks, I'll apply the update now and will report back in a few days if the error is gone. Since I reported this it has happened 4 times, and I've been using ytube_music_player many hours every day.

**Comment by KoljaWindeler** [comment]
Please reopen if the error is still present

**Comment by samhed** [comment]
I haven't seen the error a single time since your update. Thanks.
