### ISSUE TITLE
Fails to get cipher

### ISSUE THREAD

**Issue by tnunamak** [KoljaWindeler/ytube_music_player#68]
**Description**

Something is going wrong when ytube_music_player initializes. Series of events that led me here:

1. I successfully installed, configured, and used ytube_music_player on a supervised install on a rpi4.
2. I took a snapshot of HA.
3. I installed HA OS on a new machine, and restored from the snapshot.
4. I saw errors like these.
5. I uninstalled the integration, thinking it was a bad snapshot restore.
6. I deleted .storage/ytube_header_json
7. I restarted HA.
8. I reinstalled ytube_music_player in HACS, and configured it per the documented instructions.
9. I restarted HA.
10. These errors persist.

**Logs**

Initializing:

```
2021-02-22 22:30:25 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] Config via Storage/UI currently not supported due to me not understanding asyncio
2021-02-22 22:30:25 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] YtubeMediaPlayer config:
2021-02-22 22:30:25 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Header path: /config/.storage/ytube_header.json
2021-02-22 22:30:25 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - playlist: input_select.ytube_music_player_playlist
2021-02-22 22:30:25 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - mediaplayer: input_select.ytube_music_player_speakers
2021-02-22 22:30:25 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - source: input_select.ytube_music_player_source
2021-02-22 22:30:25 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - speakerlist: media_player.living_room_audio
2021-02-22 22:30:25 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - playModes: input_select.ytube_music_player_playmode
2021-02-22 22:30:25 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - playContinuous: input_boolean.ytube_music_player_playcontinuous
```

A bit further down:

```
2021-02-22 22:30:31 DEBUG (SyncWorker_12) [custom_components.ytube_music_player.media_player] _get_cipher
2021-02-22 22:30:32 ERROR (SyncWorker_12) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ytube_music_player/media_player.py", line 151, in startup
self._get_cipher('BB2mjBuAtiQ')
File "/config/custom_components/ytube_music_player/media_player.py", line 497, in _get_cipher
self._cipher = Cipher(js=self._js)
File "/usr/local/lib/python3.8/site-packages/pytube/cipher.py", line 36, in __init__
var, _ = self.transform_plan[0].split(".")
ValueError: not enough values to unpack (expected 2, got 1)
```

Attempting to play something anyway:

```
2021-02-22 22:33:22 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] play_media, media_type: playlist, media_id: RDTMAK5uy_kset8DisdE7LSD4TNjEVvrKRTmG7a56sY
2021-02-22 22:33:22 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] prepare_play
2021-02-22 22:33:22 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] check_api
2021-02-22 22:33:22 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] - no valid API, try to login
2021-02-22 22:33:22 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.const] - login without brand ID
2021-02-22 22:33:22 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] - YouTube Api initialized ok, version: 0.14.2
2021-02-22 22:33:22 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] _update_remote_player
2021-02-22 22:33:22 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] (loading) is not a valid media player.
2021-02-22 22:33:23 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] - shuffle new tracklist
2021-02-22 22:33:23 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] _tracks_to_attribute
2021-02-22 22:33:23 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] _play
2021-02-22 22:33:23 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] _get_track
2021-02-22 22:33:23 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] - Playing track nr 0 / 100
2021-02-22 22:33:23 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] get_url
2021-02-22 22:33:23 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] check_api
2021-02-22 22:33:23 DEBUG (SyncWorker_2) [custom_components.ytube_music_player.media_player] - try to find URL on our own
2021-02-22 22:33:24 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] - Failed to get own(!) URL for track, further details below. Will not try YouTube method
2021-02-22 22:33:24 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1022, in get_url
signature = self._cipher.get_signature(ciphered_signature=res['s'])
AttributeError: 'yTubeMusicComponent' object has no attribute '_cipher'
2021-02-22 22:33:24 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] qQ0zxuWFxrY
2021-02-22 22:33:24 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] {'videoId': ... }
```

**Version**

Home Assistant OS 2021.2.3

**To Reproduce**
Happens after configuring the integration and restarting HA.

**Additional context**
Maybe there are some additional files I should try deleting to get a clean install of the integration?

Thanks!

**Comment by KoljaWindeler** [comment]
Hi, please update to this, just released version https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20210223
I guess that will fix the issue. Please reopen if you have further problems.

**Comment by tnunamak** [comment]
It did, thank you!
