### ISSUE TITLE
Errors when trying to run the integration

### ISSUE THREAD

**Issue by mfabiani53** [KoljaWindeler/ytube_music_player#72]
Today, after some days not trying to run the integration, i got these errors:

```
2021-03-13 18:18:33 ERROR (SyncWorker_48) [custom_components.ytube_music_player.media_player] 

============= ytube_music_player Integration Error ================
2021-03-13 18:18:33 ERROR (SyncWorker_48) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-03-13 18:18:33 ERROR (SyncWorker_48) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-03-13 18:18:33 ERROR (SyncWorker_48) [custom_components.ytube_music_player.media_player] and paste the following output:

2021-03-13 18:18:33 ERROR (SyncWorker_48) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1090, in play_media
    self._tracks = self._api.get_playlist(playlistId=media_id)['tracks']
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 66, in get_playlist
    response = self._send_request(endpoint, body)
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 129, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 404: Not Found.
Requested entity was not found.

2021-03-13 18:18:33 ERROR (SyncWorker_48) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2021-03-13 18:18:33 ERROR (SyncWorker_48) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================


2021-03-13 18:20:20 ERROR (SyncWorker_57) [custom_components.ytube_music_player.media_player] 

============= ytube_music_player Integration Error ================
2021-03-13 18:20:20 ERROR (SyncWorker_57) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-03-13 18:20:20 ERROR (SyncWorker_57) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-03-13 18:20:20 ERROR (SyncWorker_57) [custom_components.ytube_music_player.media_player] and paste the following output:

2021-03-13 18:20:20 ERROR (SyncWorker_57) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1110, in play_media
    self._tracks = self._api.get_watch_playlist(videoId=r_track['videoId'])['tracks']
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/watch.py", line 78, in get_watch_playlist
    results = nav(watchNextRenderer,
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 210, in nav
    raise err
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 204, in nav
    root = root[k]
KeyError: 'content'

2021-03-13 18:20:20 ERROR (SyncWorker_57) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2021-03-13 18:20:20 ERROR (SyncWorker_57) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================
```

And more, when restarting HA i get a warning about key manifest....

**Comment by KoljaWindeler** [comment]
Please try to renew your cookie

**Comment by KoljaWindeler** [comment]
and also please update the player to the latest version to get around the key manifest error .. 
Did this help?

**Comment by KoljaWindeler** [comment]
Closed due to inactivity
