### ISSUE TITLE
Cannot play album

### ISSUE THREAD

**Issue by slankes** [KoljaWindeler/ytube_music_player#81]
**Describe the bug**
I can play (my own) playlists fine using:

```
service: media_player.play_media
data: 
  media_content_id: PLsvuPIUkUceYnaStU5djg0AD94Vm4vFRB
  media_content_type: playlist
  entity_id: media_player.ytube_music_player
```
But when I try to play an album using the corresponding "content" id extracted from YTMusic using:

```
service: media_player.play_media
data: 
  media_content_id: OLAK5uy_kOSgSlMaj8p-IXf31_Ra6pybG9bPzG5So
  media_content_type: album
  entity_id: media_player.ytube_music_player
```
This fails.

This is the log output that is generated:
```

2021-04-05 16:47:20 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] play_media, media_type: album, media_id: OLAK5uy_kOSgSlMaj8p-IXf31_Ra6pybG9bPzG5So
2021-04-05 16:47:20 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] prepare_play
2021-04-05 16:47:20 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] check_api
2021-04-05 16:47:20 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] _update_remote_player()
2021-04-05 16:47:20 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] _get_cipher
2021-04-05 16:47:21 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] get_album(browseId=OLAK5uy_kOSgSlMaj8p-IXf31_Ra6pybG9bPzG5So)
2021-04-05 16:47:21 ERROR (SyncWorker_0) [custom_components.ytube_music_player.media_player] 

============= ytube_music_player Integration Error ================
2021-04-05 16:47:21 ERROR (SyncWorker_0) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-04-05 16:47:21 ERROR (SyncWorker_0) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-04-05 16:47:21 ERROR (SyncWorker_0) [custom_components.ytube_music_player.media_player] and paste the following output:

2021-04-05 16:47:21 ERROR (SyncWorker_0) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1100, in play_media
    self._tracks = self._api.get_album(browseId=media_id)['tracks']
  File "/config/deps/lib/python3.8/site-packages/ytmusicapi/mixins/browsing.py", line 453, in get_album
    response = self._send_request(endpoint, body)
  File "/config/deps/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 129, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 400: Bad Request.
Request contains an invalid argument.

2021-04-05 16:47:21 ERROR (SyncWorker_0) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2021-04-05 16:47:21 ERROR (SyncWorker_0) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================


2021-04-05 16:47:21 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] turn_off
2021-04-05 16:47:21 DEBUG (SyncWorker_0) [custom_components.ytube_music_player.media_player] _turn_off_media_player
2021-04-05 16:47:21 WARNING (SyncWorker_4) [pychromecast.controllers] STOP command requested but no session is active.
2021-04-05 16:47:21 DEBUG (SyncWorker_1) [custom_components.ytube_music_player.media_player] _sync_player
2021-04-05 16:47:21 DEBUG (SyncWorker_1) [custom_components.ytube_music_player.media_player] media_player.wohnzimmer: unknown -> off
```

**Version**

I am using 20210402 installed using HACS.

**Comment by KoljaWindeler** [comment]
Have you tried to play the same album via the browser and check the attributes?

**Comment by slankes** [comment]
I had not but have done so now. The error looks similar. When I click on the album in the Library view, I get a:

Media Browsing Error: Unknown error

trying to "play" that album I get the same error:

```
2021-04-05 17:03:56 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] play_media, media_type: album, media_id: MPREb_o5DXb711Nsw
2021-04-05 17:03:56 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] prepare_play
2021-04-05 17:03:56 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] check_api
2021-04-05 17:03:56 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] _update_remote_player()
2021-04-05 17:03:56 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] _turn_on_media_player
2021-04-05 17:03:56 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] _get_cipher
2021-04-05 17:03:57 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] get_album(browseId=MPREb_o5DXb711Nsw)
2021-04-05 17:03:57 ERROR (SyncWorker_11) [custom_components.ytube_music_player.media_player] 

============= ytube_music_player Integration Error ================
2021-04-05 17:03:57 ERROR (SyncWorker_11) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-04-05 17:03:57 ERROR (SyncWorker_11) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-04-05 17:03:57 ERROR (SyncWorker_11) [custom_components.ytube_music_player.media_player] and paste the following output:

2021-04-05 17:03:57 ERROR (SyncWorker_11) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1100, in play_media
    self._tracks = self._api.get_album(browseId=media_id)['tracks']
  File "/config/deps/lib/python3.8/site-packages/ytmusicapi/mixins/browsing.py", line 454, in get_album
    data = nav(response, FRAMEWORK_MUTATIONS)
  File "/config/deps/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 146, in nav
    raise err
  File "/config/deps/lib/python3.8/site-packages/ytmusicapi/parsers/utils.py", line 140, in nav
    root = root[k]
KeyError: 'frameworkUpdates'

2021-04-05 17:03:57 ERROR (SyncWorker_11) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2021-04-05 17:03:57 ERROR (SyncWorker_11) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================


2021-04-05 17:03:57 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] turn_off
2021-04-05 17:03:57 DEBUG (SyncWorker_11) [custom_components.ytube_music_player.media_player] _turn_off_media_player
2021-04-05 17:03:57 WARNING (SyncWorker_9) [pychromecast.controllers] STOP command requested but no session is active.

```

**Comment by KoljaWindeler** [comment]
Interesting ... And also good that all debug is included 👍 
@sigma76 any idea why the call fails? 
Thanks jkw

**Comment by sigma67** [comment]
Could be due to the ongoing album beta sigma67/ytmusicapi#173

**Comment by slankes** [comment]
Yes - that looks like a likely cause. 

To summarize for people only visiting this issue: Apparently google is rolling out a change in behavior and if you're bit by this issue you might be one of the lucky ones who already received the new api/implementation.

@sigma67 already has a fix that seems to work in ytmusicapi master - if you're brave you can try updating ytube_music_players instance to that and patch in the beta=True parameter.

I would suggest to leave this issue open until a fix is tested and released.

**Comment by KoljaWindeler** [comment]
agreed

**Comment by KoljaWindeler** [comment]
Hi, please test the new version and reopen if the error still occurs

**Comment by slankes** [comment]
I am not sure if it's a user error, but it doesn't work for me.

The automation does:

```
service: media_player.play_media
data:
  entity_id: media_player.ytube_music_player
  media_content_id: '{{ media_content_id }}'
  media_content_type: album
```

Where the media content id is ```OLAK5uy_nTW2hDZgp9YppM1Z-kLPWjd2qDHAIXk1A```

I get this error:
```
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] async_select_source(kinderzimmer)
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] async_update_remote_player(media_player.kinderzimmer/)
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] END async_update_remote_player
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] - Choosing media_player.kinderzimmer as player
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] END async_select_source
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] set_shuffle: False
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] _tracks_to_attribute
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] END _tracks_to_attribute
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] play_media, media_type: album, media_id: OLAK5uy_nTW2hDZgp9YppM1Z-kLPWjd2qDHAIXk1A
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] async_prepare_play
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] async_check_api
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] async_update_remote_player(/media_player.kinderzimmer)
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] END async_update_remote_player
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] async_turn_on_media_player
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] async_get_cipher
2021-05-01 15:34:34 DEBUG (MainThread) [custom_components.ytube_music_player.media_player] get_album(browseId=OLAK5uy_nTW2hDZgp9YppM1Z-kLPWjd2qDHAIXk1A)
2021-05-01 15:34:34 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 

============= ytube_music_player Integration Error ================
2021-05-01 15:34:34 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-05-01 15:34:34 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-05-01 15:34:34 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:

2021-05-01 15:34:34 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 1141, in async_play_media
    self._tracks = await self.hass.async_add_executor_job(self._api.get_album,media_id)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/deps/lib/python3.8/site-packages/ytmusicapi/mixins/browsing.py", line 469, in get_album
    response = self._send_request(endpoint, body)
  File "/config/deps/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 129, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 400: Bad Request.
Request contains an invalid argument.

2021-05-01 15:34:34 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2021-05-01 15:34:34 ERROR (MainThread) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================
```
