### ISSUE TITLE
String Value is None for dictionary value @ data['media_content_id']

### ISSUE THREAD

**Issue by scooper86** [KoljaWindeler/ytube_music_player#97]
The integration was working however appears to have stopped during one of the recent updates to HomeAssistant.

I have reinstalled the integration a number of times now, included the input_selects, copied the cookie from YouTube Music but still keep getting an error when trying to select a track/playlist/album/etc.... of String Value is None for dictionary value @ data['media_content_id']

Everything looks like it should work, album art and data is grabbed from YouTube Music but wont cast to any of my devices (mostly Google Chromecasts)

> 2021-05-11 06:00:33 ERROR (MainThread) [custom_components.ytube_music_player.media_player] END async_call_method
2021-05-11 06:00:56 ERROR (MainThread) [custom_components.ytube_music_player.media_player] turn_off
2021-05-11 06:00:56 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_off_media_player
2021-05-11 06:00:56 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_turn_off_media_player
2021-05-11 06:00:56 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player
2021-05-11 06:00:56 ERROR (MainThread) [custom_components.ytube_music_player.media_player] media_player.kitchen_display: idle -> off
2021-05-11 06:00:56 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player
2021-05-11 06:00:56 ERROR (MainThread) [custom_components.ytube_music_player.media_player] media_player.kitchen_display: idle -> off
2021-05-11 06:00:58 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] TURNON
2021-05-11 06:00:58 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] TURNON
2021-05-11 06:00:58 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] play_media, media_type: playlist, media_id: PLN5yLazvZyWsTUceWn06vDRF2GYA7-ABo
2021-05-11 06:00:58 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_prepare_play
2021-05-11 06:00:58 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api
2021-05-11 06:00:58 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - no valid API, try to login
2021-05-11 06:00:59 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - YouTube Api initialized ok, version: 0.16.0
2021-05-11 06:00:59 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_check_api
2021-05-11 06:00:59 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_update_remote_player(Input / current media_player.kitchen_display)
2021-05-11 06:00:59 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_update_remote_player
2021-05-11 06:00:59 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_turn_on_media_player
2021-05-11 06:00:59 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_turn_on_media_player
2021-05-11 06:00:59 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_cipher
2021-05-11 06:01:00 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_get_cipher
2021-05-11 06:01:00 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_prepare_play
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] get_playlist(playlistId=PLN5yLazvZyWsTUceWn06vDRF2GYA7-ABo)
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - shuffle new tracklist
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] _tracks_to_attribute
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] _tracks_to_attribute
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] _play
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_track
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Playing track nr 0 / 33
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_get_url
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_check_api
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_check_api
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - try to find URL on our own
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] media_player.kitchen_display: off -> idle
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] media_player.kitchen_display: off -> idle
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] media_player.kitchen_display: off -> idle
2021-05-11 06:01:01 ERROR (Thread-19) [homeassistant.components.cast.media_player] Failed to cast media https://www.home-assistant.io/images/cast/splash.png. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] - Failed to get own(!) URL for track, further details below. Will not try YouTube method
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1135, in async_get_url
if(streamingData[streamId].get('url') is None):
KeyError: 0
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] 1s0yma1HqHA
2021-05-11 06:01:01 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for ytube_music_player doing I/O at custom_components/ytube_music_player/media_player.py, line 1161: _LOGGER.error(self._api.get_song(videoId))
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] self._api.get_song(1s0yma1HqHA)
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
============= ytube_music_player Integration Error ================
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] and paste the following output:
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1135, in async_get_url
if(streamingData[streamId].get('url') is None):
KeyError: 0
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/ytube_music_player/media_player.py", line 1161, in async_get_url
_LOGGER.error(self._api.get_song(videoId))
File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/browsing.py", line 591, in get_song
response = requests.get(endpoint, params, headers=self.headers, proxies=self.proxies)
File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
return request('get', url, params=params, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/lib/python3.8/http/client.py", line 1252, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.8/http/client.py", line 1263, in _send_request
self.putrequest(method, url, **skips)
File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 214, in putrequest
return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
check_loop()
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/ytube_music_player/media_player.py, line 1161: _LOGGER.error(self._api.get_song(videoId))
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player]
thanks, Kolja
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] media_player.kitchen_display: idle -> idle
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_sync_player
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] media_player.kitchen_display: idle -> idle
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_sync_player
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [S] async_sync_player
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] media_player.kitchen_display: idle -> idle
2021-05-11 06:01:01 ERROR (MainThread) [custom_components.ytube_music_player.media_player] [E] async_sync_player
2021-05-11 06:01:20 ERROR (stream_worker) [libav.NULL] sps_id 2 out of range

**Comment by fabir-git** [comment]
same issue here

**Comment by mromaithi** [comment]
hello, same issue here. first time install

**Comment by KoljaWindeler** [comment]
Hmm i'm really trying to figure out what causes this.

I understand that the backup routine is running i/o code that homeassistant stops... Okay. But the backup shouldn't even be needed. But why won't the primary method return a valid streaming object .... Your cookie works fine ..  otherwise you wouldn't get that far. 

Is this happening always? Every track? Or can we narrow it down to a scenario? 
Thx

**Comment by fabir-git** [comment]
It is happening for all playlists. I can try songs later.

**Comment by KoljaWindeler** [comment]
Hmm could you set one of those playlist to public and paste the Id? 
Although I'd say it has nothing to do with the playlist ..

**Comment by fabir-git** [comment]
This would be one example: 
Happy Pop Hits
RDCLAK5uy_mfdqvCAl8wodlx2P2_Ai2gNkiRDAufkkI

**Comment by KoljaWindeler** [comment]
'gemma Bier trinken' passend zum vaddertag ... 

Works fine here ..  I'll add some more debug and fix the backup method .... But still a strange issue.

**Comment by fabir-git** [comment]
Strange, that's no song in the playlist on my end...
Would fit the day though.

**Comment by scooper86** [comment]
I have tried single songs through the media browser and they aren't working either

**Comment by da-anda** [comment]
same issue here, regardless of what I try to play

**Comment by ragaimeena** [comment]
Same issue here

**Comment by KoljaWindeler** [comment]
HI, I've just added https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20210517b01 as BETA.
This will a) add way more output regarding the missing streaming links and b) fixed the backup method (which is less reliable and slower) so you might be able to hear some music in the meantime

Could you please copy the output of the log into this ticket so we can get it fixed (it still works here as always so this is hard to understand for me)

**Comment by scooper86** [comment]
Can confirm the update is working and here is the output:

`2021-05-17 12:39:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration ytube_music_player which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-17 12:39:18 ERROR (MainThread) [homeassistant.loader] '0.20210517.b01' is not a valid version for custom integration 'ytube_music_player'. Please report this to the maintainer of 'ytube_music_player'
2021-05-17 12:39:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-17 12:39:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration fullykiosk which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-17 12:39:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-17 12:39:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-17 12:39:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-17 12:39:23 WARNING (MainThread) [homeassistant.loader] You are using a custom integration radarr_upcoming_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-17 12:39:23 WARNING (MainThread) [homeassistant.loader] You are using a custom integration sonarr_upcoming_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-17 12:39:23 WARNING (MainThread) [homeassistant.loader] You are using a custom integration google_fit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-05-17 12:39:31 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook c30691416b2d2001e7b220492e08b2b150bd83ea823132ed04a7722732dc8599 from 192.168.1.38
2021-05-17 12:39:31 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook c30691416b2d2001e7b220492e08b2b150bd83ea823132ed04a7722732dc8599 from 192.168.1.38
2021-05-17 12:39:34 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform google_fit is taking over 10 seconds.
2021-05-17 12:39:40 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook c30691416b2d2001e7b220492e08b2b150bd83ea823132ed04a7722732dc8599 from 192.168.1.46
2021-05-17 12:39:40 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook c30691416b2d2001e7b220492e08b2b150bd83ea823132ed04a7722732dc8599 from 192.168.1.46
2021-05-17 12:40:06 WARNING (MainThread) [homeassistant.config_entries] Config entry 'EPSON XP-5100 Series' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2021-05-17 12:40:07 WARNING (MainThread) [homeassistant.components.hue] ('Please check for software updates of the bridge in the Philips Hue App.', 'Signify Hue', 'hue_hub_firmware')
2021-05-17 12:40:32 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: kodi
2021-05-17 12:41:33 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: kodi
2021-05-17 12:46:10 ERROR (Thread-22) [homeassistant.components.cast.media_player] Failed to cast media https://www.home-assistant.io/images/cast/splash.png. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
2021-05-17 12:46:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player] No adaptiveFormat and no formats found
2021-05-17 12:46:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player] get_streaming_data(SQyu9vfW9Bk)
2021-05-17 12:46:11 ERROR (MainThread) [custom_components.ytube_music_player.media_player] {}
2021-05-17 12:46:16 ERROR (MainThread) [custom_components.ytube_music_player.media_player] ultimatly
2021-05-17 12:46:16 ERROR (MainThread) [custom_components.ytube_music_player.media_player] https://r4---sn-8pgbpohxqp5-ac5z.googlevideo.com/videoplayback?expire=1621273572&ei=hFeiYPPVLYjyWe_OhrgF&ip=82.23.136.107&id=o-AIpljxRBu8ihzyaX0XphlwdgZ9sGqSfw10uOhvBk6PS4&itag=251&source=youtube&requiressl=yes&mh=3U&mm=31%2C29&mn=sn-8pgbpohxqp5-ac5z%2Csn-aigl6nl7&ms=au%2Crdu&mv=m&mvi=4&pl=21&gcr=gb&initcwndbps=2083750&vprv=1&mime=audio%2Fwebm&ns=pdKWppqGvKNbaI5jW5yJxUMF&gir=yes&clen=4379836&dur=274.081&lmt=1583810969560948&mt=1621251882&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=1301222&n=BdGM7UUW1FxWtjgc&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgPkl_gUiVbN9T6ec_pb1f9XkME0oyKAaXvKUe1VA3R3ICIFH0MbAM2y7F_PYh6E8xtSRZevueHBAz7ZgjmTtQK6gS&sig=AOq0QJ8wRQIhALq8MNx93cm4OUuUhY6MYEUxu0LNMjbAgJYRlZEoY2l1AiA-y267eqIZOkSL0HPI7HUcFbXJSxSltSj9XZF_T667fA==
2021-05-17 12:46:17 ERROR (Thread-22) [homeassistant.components.cast.media_player] Failed to cast media https://r4---sn-8pgbpohxqp5-ac5z.googlevideo.com/videoplayback?expire=1621273572&ei=hFeiYPPVLYjyWe_OhrgF&ip=82.23.136.107&id=o-AIpljxRBu8ihzyaX0XphlwdgZ9sGqSfw10uOhvBk6PS4&itag=251&source=youtube&requiressl=yes&mh=3U&mm=31%2C29&mn=sn-8pgbpohxqp5-ac5z%2Csn-aigl6nl7&ms=au%2Crdu&mv=m&mvi=4&pl=21&gcr=gb&initcwndbps=2083750&vprv=1&mime=audio%2Fwebm&ns=pdKWppqGvKNbaI5jW5yJxUMF&gir=yes&clen=4379836&dur=274.081&lmt=1583810969560948&mt=1621251882&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=1301222&n=BdGM7UUW1FxWtjgc&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgPkl_gUiVbN9T6ec_pb1f9XkME0oyKAaXvKUe1VA3R3ICIFH0MbAM2y7F_PYh6E8xtSRZevueHBAz7ZgjmTtQK6gS&sig=AOq0QJ8wRQIhALq8MNx93cm4OUuUhY6MYEUxu0LNMjbAgJYRlZEoY2l1AiA-y267eqIZOkSL0HPI7HUcFbXJSxSltSj9XZF_T667fA==. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
2021-05-17 12:46:27 ERROR (stream_worker) [libav.NULL] sps_id 1 out of range`

**Comment by KoljaWindeler** [comment]
Great. At least something. I've created a ticket as this will likely be an issue in the future. 

Is this beta also fixing it for all others?

**Comment by fabir-git** [comment]
The Beta fixes the issue for me.

**Comment by mbotti93** [comment]
The beta is working also for me

**Comment by KoljaWindeler** [comment]
It would be great if you could also copy the log .. there should be a couple error log entries ...

**Comment by fabir-git** [comment]
`
Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:316
Integration: Google Cast (documentation, issues)
First occurred: 21:13:20 (2 occurrences)
Last logged: 21:13:24

Failed to cast media https://www.home-assistant.io/images/cast/splash.png. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
Failed to cast media https://r2---sn-h0jeenle.googlevideo.com/videoplayback?expire=1621300402&ei=UsCiYKzEKozb1wLCsqWYBw&ip=87.167.119.107&id=o-AKgC6ITjisknPs7yGfODwP6orxUP5X6dMkt_XYT80ma_&itag=251&source=youtube&requiressl=yes&mh=HP&mm=31%2C29&mn=sn-h0jeenle%2Csn-h0jelne7&ms=au%2Crdu&mv=m&mvi=2&pl=26&gcr=de&initcwndbps=1180000&vprv=1&mime=audio%2Fwebm&ns=tqBdUBnFG5-Op-kzkBI2SR0F&gir=yes&clen=3628771&dur=242.201&lmt=1620540685498273&mt=1621278770&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5531432&n=P9kpl1ZDD5RcdpRT&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgJ6rUzMyepxNOe4oJRAkfdWVLbLZ-59Tkp4hg7Z5UdAQCIQDqsLZ4gwOtOzl-FizQQWya3UUh3X6cGdkIfuJAwg48wQ%3D%3D&sig=AOq0QJ8wRQIgZ8CwdQnBVIhO66hOda1wleew63kyEsHwRhFPQPI5eAoCIQDeVfDP3F6pieTD_9ihEDP9kyyoM9lIzRt9msJ01ewufQ==. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address


benutzerdefinierte

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1180
Integration: YouTube Music Player (documentation, issues)
First occurred: 21:13:24 (1 occurrences)
Last logged: 21:13:24

https://r2---sn-h0jeenle.googlevideo.com/videoplayback?expire=1621300402&ei=UsCiYKzEKozb1wLCsqWYBw&ip=87.167.119.107&id=o-AKgC6ITjisknPs7yGfODwP6orxUP5X6dMkt_XYT80ma_&itag=251&source=youtube&requiressl=yes&mh=HP&mm=31%2C29&mn=sn-h0jeenle%2Csn-h0jelne7&ms=au%2Crdu&mv=m&mvi=2&pl=26&gcr=de&initcwndbps=1180000&vprv=1&mime=audio%2Fwebm&ns=tqBdUBnFG5-Op-kzkBI2SR0F&gir=yes&clen=3628771&dur=242.201&lmt=1620540685498273&mt=1621278770&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5531432&n=P9kpl1ZDD5RcdpRT&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgJ6rUzMyepxNOe4oJRAkfdWVLbLZ-59Tkp4hg7Z5UdAQCIQDqsLZ4gwOtOzl-FizQQWya3UUh3X6cGdkIfuJAwg48wQ%3D%3D&sig=AOq0QJ8wRQIgZ8CwdQnBVIhO66hOda1wleew63kyEsHwRhFPQPI5eAoCIQDeVfDP3F6pieTD_9ihEDP9kyyoM9lIzRt9msJ01ewufQ==


benutzerdefinierte

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1179
Integration: YouTube Music Player (documentation, issues)
First occurred: 21:13:24 (1 occurrences)
Last logged: 21:13:24

ultimatly



benutzerdefinierte

Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:165
Integration: YouTube Music Player (documentation, issues)
First occurred: 21:13:22 (3 occurrences)
Last logged: 21:13:22

No adaptiveFormat and no formats found
get_streaming_data(A93OQy81TYs)
{}

`

**Comment by KoljaWindeler** [comment]
Alright, perfect. So the same issue. Get_stream_data returns {}

**Comment by KoljaWindeler** [comment]
Should be fixed now with https://github.com/KoljaWindeler/ytube_music_player/releases/tag/20200519.01
Please leave a comment if a) this is true and the new version fixes the issue and b) reopen the ticket if not

**Comment by scooper86** [comment]
Looks good, thank you for the quick fix, great addition to Home Assistant!
